// Gym-Bro recipe data. Nutrition per 100 g (approximate UK supermarket values).
// ING: id -> [shopping name, aisle, kcal, protein, carbs, fat, grams per item (optional), item word (optional)]
window.BB_DATA = (function () {
  const ING = {
    "sushi-rice": ["Sushi rice", "Carbs", 358, 6.5, 79, 0.6],
    "jasmine-rice": ["Jasmine or basmati rice", "Carbs", 356, 7, 79, 0.6],
    "pasta": ["Spaghetti, linguine or pappardelle", "Carbs", 355, 12.5, 71, 1.5],
    "penne": ["Penne or rigatoni", "Carbs", 355, 12.5, 71, 1.5],
    "lasagne-sheets": ["Lasagne sheets", "Carbs", 355, 12.5, 71, 1.5],
    "oats": ["Porridge oats", "Carbs", 375, 11, 60, 8],
    "sourdough": ["Sourdough", "Carbs", 250, 9, 48, 1.5, 45, "slices"],
    "brioche": ["Brioche buns", "Carbs", 330, 9, 50, 10, 60, "buns"],
    "wrap": ["Large wraps", "Carbs", 300, 8.5, 50, 7, 62, "wraps"],
    "sub-roll": ["Sub rolls", "Carbs", 270, 9, 50, 3, 90, "rolls"],
    "pizza-base": ["Thin pizza bases", "Carbs", 270, 8, 52, 3, 150, "bases"],
    "potatoes": ["Potatoes", "Carbs", 77, 2, 17, 0.1],
    "rice-noodles": ["Rice noodles (dry)", "Carbs", 360, 6, 82, 0.6],
    "sweet-potato": ["Sweet potatoes", "Carbs", 86, 1.6, 20, 0.1],
    "digestives": ["Digestive biscuits", "Carbs", 480, 7, 62, 21, 15, "biscuits"],
    "rice-cakes": ["Rice cakes", "Carbs", 390, 8, 81, 3, 8, "rice cakes"],
    "panko": ["Panko breadcrumbs", "Carbs", 370, 12, 75, 3],
    "granola": ["Granola (lower sugar)", "Carbs", 430, 10, 60, 15],

    "chicken-breast": ["Chicken breast", "Protein", 106, 24, 0, 1.1],
    "chicken-thigh": ["Chicken thigh fillets, skinless", "Protein", 125, 20, 0, 4.9],
    "beef-mince": ["5% beef mince", "Protein", 125, 21, 0, 5],
    "lamb-mince": ["Lean lamb mince", "Protein", 150, 20, 0, 8],
    "beef-shin": ["Beef shin", "Protein", 130, 21, 0, 5],
    "steak": ["Sirloin steak, trimmed", "Protein", 150, 23, 0, 6],
    "topside": ["Beef topside joint", "Protein", 130, 23, 0, 4],
    "pork-loin": ["Pork loin joint, fat off", "Protein", 140, 22, 0, 5],
    "bacon": ["Bacon medallions", "Protein", 110, 20, 0, 3],
    "turkey-pepperoni": ["Turkey pepperoni", "Protein", 180, 22, 2, 9],
    "salmon": ["Salmon fillets", "Protein", 200, 20, 0, 13],
    "tuna": ["Tuna in spring water, drained", "Protein", 110, 25, 0, 1],
    "prawns": ["King prawns, cooked", "Protein", 70, 16, 0, 0.9],
    "whey": ["Whey protein", "Protein", 390, 78, 7, 6],

    "eggs": ["Eggs", "Dairy and eggs", 140, 12.5, 0.5, 10, 50, "eggs"],
    "egg-whites": ["Liquid egg whites", "Dairy and eggs", 50, 11, 0.5, 0.2],
    "greek-yog": ["Greek yoghurt 0%", "Dairy and eggs", 57, 10, 4, 0.2],
    "milk": ["Semi-skimmed milk", "Dairy and eggs", 47, 3.5, 4.8, 1.7],
    "skimmed-milk": ["Skimmed milk", "Dairy and eggs", 35, 3.5, 5, 0.1],
    "mozzarella": ["Light mozzarella", "Dairy and eggs", 165, 20, 1, 9],
    "parmesan": ["Parmesan", "Dairy and eggs", 390, 33, 0, 28],
    "pecorino": ["Pecorino", "Dairy and eggs", 390, 28, 0, 30],
    "quark": ["Quark", "Dairy and eggs", 70, 12, 4, 0.2],
    "cream-cheese": ["Light cream cheese", "Dairy and eggs", 150, 7, 5, 11],
    "cheese-slice": ["Light cheese slices", "Dairy and eggs", 250, 20, 5, 15, 20, "slices"],

    "onion": ["Onions", "Fruit and veg", 40, 1.1, 9, 0.1],
    "garlic": ["Garlic", "Fruit and veg", 110, 6, 24, 0.5],
    "peppers": ["Peppers", "Fruit and veg", 30, 1, 6, 0.3],
    "lettuce": ["Lettuce", "Fruit and veg", 15, 1.2, 2, 0.2],
    "cabbage": ["White cabbage", "Fruit and veg", 25, 1.3, 5, 0.1],
    "cucumber": ["Cucumber", "Fruit and veg", 15, 0.7, 3, 0.1],
    "tomato": ["Tomatoes", "Fruit and veg", 18, 0.9, 3.5, 0.2],
    "broccoli": ["Tenderstem or broccoli", "Fruit and veg", 34, 2.8, 7, 0.4],
    "greens": ["Pak choi or green veg", "Fruit and veg", 30, 3, 4, 0.4],
    "rocket": ["Rocket", "Fruit and veg", 25, 2.6, 3.6, 0.7],
    "edamame": ["Edamame beans (frozen)", "Fruit and veg", 125, 11, 7, 5],
    "peas": ["Frozen peas", "Fruit and veg", 70, 5.5, 10, 1.4],
    "pineapple": ["Pineapple chunks", "Fruit and veg", 50, 0.5, 12, 0.1],
    "berries": ["Berries (frozen is fine)", "Fruit and veg", 50, 1, 9, 0.3],
    "apple": ["Apples", "Fruit and veg", 52, 0.3, 14, 0.2, 150, "apples"],
    "beansprouts": ["Beansprouts", "Fruit and veg", 30, 3, 4, 0.2],
    "lime": ["Limes", "Fruit and veg", 30, 0.7, 10, 0.2, 65, "limes"],
    "mango": ["Mango", "Fruit and veg", 60, 0.8, 15, 0.4],
    "avocado": ["Avocado", "Fruit and veg", 160, 2, 9, 15],
    "corn": ["Sweetcorn (frozen or tin)", "Fruit and veg", 86, 3.3, 19, 1.4],
    "spinach": ["Spinach", "Fruit and veg", 23, 2.9, 3.6, 0.4],
    "kimchi": ["Kimchi", "Fruit and veg", 20, 1.5, 3, 0.5],
    "gherkins": ["Gherkins", "Fruit and veg", 20, 0.5, 4, 0.1],

    "passata": ["Passata", "Sauces and cupboard", 30, 1.4, 5, 0.2],
    "chopped-tom": ["Chopped tomatoes (tins)", "Sauces and cupboard", 22, 1.1, 3.5, 0.2],
    "olive-oil": ["Olive oil", "Sauces and cupboard", 900, 0, 0, 100],
    "sesame-oil": ["Sesame oil", "Sauces and cupboard", 900, 0, 0, 100],
    "soy": ["Light soy sauce", "Sauces and cupboard", 60, 8, 7, 0],
    "sushi-vinegar": ["Sushi seasoning or rice vinegar", "Sauces and cupboard", 150, 0, 35, 0],
    "teriyaki": ["Teriyaki sauce (reduced sugar)", "Sauces and cupboard", 120, 3, 25, 0],
    "gochujang": ["Gochujang", "Sauces and cupboard", 220, 4, 45, 2],
    "sriracha": ["Sriracha", "Sauces and cupboard", 100, 2, 20, 1],
    "light-mayo": ["Light mayo", "Sauces and cupboard", 260, 1, 8, 25],
    "ketchup": ["Ketchup", "Sauces and cupboard", 100, 1, 23, 0.1],
    "bbq": ["BBQ sauce", "Sauces and cupboard", 150, 1, 35, 0.2],
    "honey": ["Honey", "Sauces and cupboard", 304, 0.3, 82, 0],
    "peanut-butter": ["Peanut butter", "Sauces and cupboard", 600, 25, 12, 49],
    "tahini": ["Tahini", "Sauces and cupboard", 600, 17, 20, 53],
    "cornflour": ["Cornflour", "Sauces and cupboard", 350, 0.3, 88, 0.1],
    "furikake": ["Furikake or toasted sesame", "Sauces and cupboard", 400, 20, 40, 15],
    "salsa": ["Salsa (jar)", "Sauces and cupboard", 35, 1, 7, 0.2],
    "coconut-light": ["Light coconut milk", "Sauces and cupboard", 75, 0.7, 2.5, 7],
    "green-curry-paste": ["Thai green curry paste", "Sauces and cupboard", 110, 2, 12, 6],
    "curry-paste": ["Curry paste (tikka, jalfrezi or katsu)", "Sauces and cupboard", 150, 3, 15, 9],
    "fish-sauce": ["Fish sauce", "Sauces and cupboard", 35, 5, 4, 0],
    "peanuts": ["Roasted peanuts", "Sauces and cupboard", 590, 26, 13, 49],
    "kidney-beans": ["Kidney beans (tin, drained)", "Sauces and cupboard", 100, 7, 15, 0.5],
    "peri-peri": ["Peri-peri sauce", "Sauces and cupboard", 80, 1, 15, 2],
    "cocoa": ["Cocoa powder", "Sauces and cupboard", 380, 20, 12, 21],
    "dark-choc": ["Dark chocolate (85%)", "Sauces and cupboard", 600, 10, 20, 50],
    "jam": ["Reduced-sugar jam", "Sauces and cupboard", 140, 0.5, 34, 0.1],
    "gravy": ["Gravy (made up)", "Sauces and cupboard", 30, 0.5, 5, 1]
  };

  // Recipes: grams per 1 serving. prep = Sunday batch job (optional).
  const R = [
    // ---- Breakfasts ----
    { id: "bf-eggs", slot: "breakfast", name: "Eggs and sourdough", time: "10 min",
      ing: [["eggs", 200], ["egg-whites", 150], ["sourdough", 90], ["salsa", 40]],
      method: ["Scramble the eggs and whites low and slow, season well.", "Toast the sourdough.", "Serve with salsa or hot sauce."] },
    { id: "bf-oats", slot: "breakfast", name: "Protein oats with berries", time: "5 min",
      ing: [["oats", 70], ["milk", 250], ["whey", 30], ["berries", 100], ["peanut-butter", 10], ["honey", 10]],
      method: ["Cook the oats in the milk for 3–4 minutes.", "Take off the heat and stir the whey in so it doesn't go grainy.", "Top with berries, peanut butter and honey."] },

    // ---- Snack ----
    { id: "snack", slot: "snack", name: "Yoghurt bowl, plus a shake", time: "2 min",
      ing: [["greek-yog", 300], ["honey", 15], ["berries", 80], ["granola", 40], ["whey", 30], ["apple", 150]],
      method: ["Yoghurt with honey, berries and granola mid-afternoon.", "Whey shake with water and an apple after training or in the evening."] },
    { id: "s-choc-mousse", slot: "snack", name: "Chocolate protein mousse, plus a shake", time: "5 min", tag: "Sweet",
      ing: [["quark", 250], ["whey", 60], ["cocoa", 10], ["honey", 10], ["berries", 60], ["dark-choc", 10]],
      method: ["Whisk quark, half the whey, cocoa and honey until thick and smooth.", "Top with berries and grated dark chocolate. Chill 20 minutes if you can.", "Shake the rest of the whey with water later on."] },
    { id: "s-brownie", slot: "snack", name: "Protein brownies with yoghurt", time: "Batch: 25 min", tag: "Sweet",
      ing: [["oats", 30], ["whey", 30], ["cocoa", 12], ["eggs", 25], ["honey", 15], ["dark-choc", 10], ["greek-yog", 200], ["berries", 60]],
      method: ["Blitz oats to flour; mix with whey, cocoa, egg, honey and a splash of milk to a thick batter.", "Fold in chopped dark chocolate; bake in a lined tin at 180°C for 15–18 minutes, still fudgy in the middle.", "Two squares per serving with Greek yoghurt and berries."] },
    { id: "s-cheesecake", slot: "snack", name: "Berry cheesecake pot, plus a shake", time: "5 min", tag: "Sweet",
      ing: [["quark", 200], ["cream-cheese", 30], ["whey", 60], ["honey", 10], ["berries", 80], ["digestives", 15]],
      method: ["Crush a digestive into the bottom of a jar.", "Whisk quark, cream cheese, half the whey and honey; spoon over.", "Top with berries. Shake the rest of the whey with water later on."] },
    { id: "s-bark", slot: "snack", name: "Frozen yoghurt bark, plus a shake", time: "Batch: 10 min + freezing", tag: "Sweet",
      ing: [["greek-yog", 250], ["honey", 15], ["berries", 80], ["dark-choc", 15], ["granola", 20], ["whey", 30]],
      method: ["Mix yoghurt and honey; spread 1 cm thick on a lined tray.", "Scatter berries, granola and chopped dark chocolate; freeze 3 hours.", "Snap into shards. Shake the whey with water later on."] },
    { id: "s-crumble", slot: "snack", name: "Apple crumble pot with vanilla yoghurt", time: "Batch: 20 min", tag: "Sweet",
      ing: [["apple", 150], ["honey", 10], ["oats", 30], ["peanut-butter", 10], ["greek-yog", 250], ["whey", 30]],
      method: ["Dice the apple and microwave with cinnamon and half the honey for 2 minutes.", "Crumble: oats, peanut butter and the rest of the honey, toasted in a dry pan or baked at 180°C for 8 minutes.", "Stir whey (vanilla if you have it) into the yoghurt; layer apple, yoghurt and crumble."] },
    { id: "s-pbj", slot: "snack", name: "PB and jam rice cakes, plus a milkshake", time: "3 min", tag: "Sweet",
      ing: [["rice-cakes", 32], ["peanut-butter", 20], ["jam", 20], ["whey", 40], ["milk", 250]],
      method: ["Spread 4 rice cakes with peanut butter and jam.", "Blend or shake whey with cold milk and ice."] },

    // ---- Lunch bowls ----
    { id: "l-salmon-poke", slot: "lunch", name: "Salmon poke bowl", time: "15 min",
      ing: [["sushi-rice", 90], ["sushi-vinegar", 15], ["salmon", 140], ["edamame", 80], ["cucumber", 60], ["light-mayo", 10], ["sriracha", 10], ["soy", 10]],
      prep: "roast or pan-sear the salmon, portion with seasoned sushi rice",
      method: ["Season warm sushi rice with the vinegar.", "Cube the salmon; sear or roast at 200°C for 10 minutes if not sushi-grade.", "Build with edamame and cucumber; dress with soy and sriracha mayo."] },
    { id: "l-tuna-poke", slot: "lunch", name: "Tuna poke bowl", time: "10 min",
      ing: [["sushi-rice", 100], ["sushi-vinegar", 15], ["tuna", 220], ["edamame", 60], ["cucumber", 60], ["light-mayo", 15], ["sriracha", 10], ["soy", 10]],
      prep: "portion seasoned sushi rice; mix tuna with sriracha mayo on the day",
      method: ["Season warm sushi rice with the vinegar.", "Mix drained tuna with light mayo, sriracha and soy.", "Build with edamame and cucumber."] },
    { id: "l-teriyaki", slot: "lunch", name: "Teriyaki chicken bowl", time: "20 min",
      ing: [["chicken-thigh", 200], ["teriyaki", 30], ["sushi-rice", 100], ["greens", 120], ["furikake", 5]],
      prep: "cook the teriyaki thighs and greens, portion with rice",
      method: ["Grill or air-fry thighs at 200°C for 18 minutes, glazing with teriyaki for the last 5.", "Steam or wok the greens.", "Slice over rice; finish with furikake."] },
    { id: "l-bulgogi", slot: "lunch", name: "Beef bulgogi bowl", time: "15 min",
      ing: [["beef-mince", 180], ["gochujang", 20], ["soy", 15], ["honey", 5], ["garlic", 5], ["sesame-oil", 5], ["sushi-rice", 100], ["kimchi", 60]],
      prep: "cook the bulgogi mince, portion with rice; kimchi on the side",
      method: ["Brown the mince hard in a dry pan.", "Add garlic, gochujang, soy and honey; reduce until sticky.", "Finish with sesame oil; serve over rice with kimchi."] },
    { id: "l-prawn-egg", slot: "lunch", name: "Prawn and egg rice bowl", time: "10 min",
      ing: [["prawns", 150], ["eggs", 100], ["sushi-rice", 100], ["edamame", 60], ["soy", 10], ["light-mayo", 10], ["furikake", 5]],
      prep: "boil the eggs (7 minutes), portion rice; prawns go in cold",
      method: ["Jammy eggs: 7 minutes, then iced water.", "Toss prawns with soy.", "Build over rice with edamame, a little mayo and furikake."] },
    { id: "l-shawarma", slot: "lunch", name: "Chicken shawarma bowl", time: "25 min",
      ing: [["chicken-thigh", 200], ["olive-oil", 5], ["jasmine-rice", 90], ["greek-yog", 60], ["tahini", 8], ["gherkins", 30], ["cucumber", 60], ["tomato", 60]],
      prep: "roast the shawarma-spiced thighs, portion with rice",
      method: ["Marinate thighs in shawarma spice, garlic, lemon and a little oil.", "Roast at 220°C for 20 minutes; rest and slice.", "Serve over rice with pickles, salad and tahini yoghurt."] },
    { id: "l-spicy-salmon", slot: "lunch", name: "Spicy salmon rice bowl", time: "15 min",
      ing: [["salmon", 140], ["sushi-rice", 100], ["sushi-vinegar", 10], ["light-mayo", 15], ["sriracha", 15], ["cucumber", 60], ["edamame", 50], ["furikake", 5]],
      prep: "roast the salmon, flake and mix with sriracha mayo, portion with rice",
      method: ["Roast salmon at 200°C for 12 minutes and flake.", "Mix with light mayo and sriracha.", "Serve over seasoned rice with cucumber, edamame and furikake."] },
    { id: "l-onigiri", slot: "lunch", name: "Tuna-mayo onigiri and edamame", time: "15 min",
      ing: [["sushi-rice", 120], ["tuna", 150], ["light-mayo", 20], ["furikake", 5], ["edamame", 100]],
      prep: "make 3 tuna-mayo onigiri and wrap them",
      method: ["Mix tuna with light mayo.", "Shape 3 rice triangles around the filling with wet, salted hands.", "Roll edges in furikake; edamame on the side."] },


    // ---- Gym-Gyal lunches ----
    { id: "l-thai-beef-salad", slot: "lunch", name: "Thai beef salad", time: "15 min", tag: "Spicy",
      ing: [["steak", 160], ["rice-noodles", 60], ["lettuce", 80], ["cucumber", 80], ["tomato", 60], ["onion", 20], ["lime", 30], ["fish-sauce", 15], ["honey", 5], ["peanuts", 10]],
      prep: "sear and slice the steak, soak the noodles, mix the dressing in a jar",
      method: ["Sear the steak hard, rest and slice thin.", "Dressing: lime juice, fish sauce, honey, chilli and garlic.", "Toss noodles, leaves, cucumber, tomato, red onion, mint and coriander with the beef; top with crushed peanuts."] },
    { id: "l-caesar", slot: "lunch", name: "Chicken Caesar salad", time: "15 min",
      ing: [["chicken-breast", 180], ["lettuce", 120], ["sourdough", 45], ["parmesan", 15], ["greek-yog", 50], ["light-mayo", 10], ["garlic", 2]],
      prep: "grill the chicken, bake sourdough croutons, mix the dressing",
      method: ["Grill the chicken and slice.", "Cube the sourdough and bake at 200°C for 8 minutes for croutons.", "Dressing: yoghurt, light mayo, garlic, lemon, parmesan and a little anchovy if you like.", "Toss with cos lettuce; dressing on the day."] },
    { id: "l-satay-noodle", slot: "lunch", name: "Satay chicken noodle salad", time: "20 min", tag: "Asian",
      ing: [["chicken-breast", 170], ["rice-noodles", 70], ["peanut-butter", 20], ["soy", 15], ["lime", 20], ["honey", 5], ["sriracha", 5], ["cucumber", 60], ["peppers", 60], ["beansprouts", 50]],
      prep: "cook the chicken and noodles, make the satay sauce",
      method: ["Poach or grill the chicken; shred.", "Satay: peanut butter, soy, lime, honey, sriracha and hot water to loosen.", "Toss cold noodles, veg and chicken with the sauce."] },
    { id: "l-prawn-mango", slot: "lunch", name: "Prawn, mango and avocado bowl", time: "10 min", tag: "Spicy",
      ing: [["prawns", 200], ["jasmine-rice", 50], ["mango", 100], ["avocado", 40], ["lettuce", 60], ["cucumber", 60], ["lime", 20], ["sriracha", 10], ["honey", 5]],
      prep: "cook and portion the rice; dice mango and cucumber",
      method: ["Rice in the base.", "Prawns, mango, cucumber and leaves on top.", "Dress with lime, sriracha and honey; add avocado on the day so it doesn't brown."] },
    { id: "l-spicy-tuna-salad", slot: "lunch", name: "Spicy tuna rice salad", time: "10 min", tag: "Spicy",
      ing: [["tuna", 200], ["sushi-rice", 60], ["sushi-vinegar", 10], ["light-mayo", 15], ["sriracha", 15], ["lettuce", 60], ["edamame", 80], ["cucumber", 60], ["furikake", 5]],
      prep: "portion seasoned sushi rice; mix tuna with sriracha mayo on the day",
      method: ["Season the rice with sushi vinegar.", "Mix tuna with light mayo and sriracha.", "Build over leaves with edamame and cucumber; finish with furikake."] },

    // ---- Gym-Gyal dinners ----
    { id: "d-thai-green-curry", slot: "dinner", name: "Thai green chicken curry", time: "25 min", tag: "Thai",
      ing: [["chicken-thigh", 200], ["green-curry-paste", 30], ["coconut-light", 150], ["peppers", 60], ["broccoli", 60], ["fish-sauce", 10], ["lime", 15], ["jasmine-rice", 80]],
      method: ["Fry the paste for a minute; add sliced thighs and seal.", "Pour in the coconut milk and a splash of water; simmer 12 minutes with the veg.", "Season with fish sauce and lime; basil if you have it. Serve with rice."] },
    { id: "d-tikka", slot: "dinner", name: "Chicken tikka masala (lighter)", time: "35 min", tag: "Curry",
      ing: [["chicken-breast", 200], ["greek-yog", 60], ["curry-paste", 25], ["onion", 50], ["garlic", 5], ["passata", 120], ["coconut-light", 60], ["jasmine-rice", 80]],
      method: ["Marinate the chicken in yoghurt and half the paste; grill or air-fry at 220°C for 12 minutes.", "Soften onion and garlic, fry the rest of the paste, add passata and coconut milk; simmer 10 minutes.", "Blend smooth if you like, add the chicken. Serve with basmati."] },
    { id: "d-jalfrezi", slot: "dinner", name: "Chicken jalfrezi", time: "30 min", tag: "Curry",
      ing: [["chicken-breast", 200], ["curry-paste", 25], ["onion", 80], ["peppers", 100], ["chopped-tom", 150], ["olive-oil", 5], ["jasmine-rice", 80]],
      method: ["Fry chunky onion and peppers hot so they char a little; set aside.", "Fry the paste, brown the chicken, add tomatoes and green chilli.", "Simmer 12 minutes, return the veg. Serve with basmati."] },
    { id: "d-katsu-curry", slot: "dinner", name: "Chicken katsu curry", time: "35 min", tag: "Fakeaway",
      ing: [["chicken-breast", 200], ["eggs", 25], ["panko", 30], ["olive-oil", 5], ["curry-paste", 20], ["onion", 50], ["coconut-light", 80], ["jasmine-rice", 80]],
      method: ["Flatten the breast, egg and panko; air-fry at 200°C for 12–14 minutes.", "Sauce: soften onion and carrot, add katsu paste and coconut milk with water; simmer and blend.", "Slice the chicken over rice and pour the sauce alongside."] },
    { id: "d-pad-thai", slot: "dinner", name: "Prawn and chicken pad thai", time: "20 min", tag: "Thai",
      ing: [["rice-noodles", 80], ["prawns", 120], ["chicken-breast", 80], ["eggs", 50], ["beansprouts", 80], ["onion", 30], ["soy", 15], ["fish-sauce", 10], ["honey", 10], ["lime", 20], ["peanuts", 10]],
      method: ["Soak the noodles until just soft.", "Wok the chicken, then prawns; push aside and scramble the egg.", "Add noodles with fish sauce, soy, honey and lime; toss with beansprouts and spring onion. Peanuts and chilli flakes on top."] },
    { id: "d-thai-basil", slot: "dinner", name: "Thai basil beef with a fried egg", time: "15 min", tag: "Thai",
      ing: [["beef-mince", 180], ["garlic", 10], ["peppers", 60], ["soy", 15], ["fish-sauce", 10], ["honey", 5], ["eggs", 50], ["jasmine-rice", 80]],
      method: ["Pound garlic and bird's-eye chilli; fry in a hot wok.", "Add the mince and brown hard; peppers in.", "Soy, fish sauce and honey; a big handful of basil. Over rice with a crispy fried egg."] },
    { id: "d-peri-peri", slot: "dinner", name: "Peri-peri chicken and spicy rice", time: "30 min", tag: "Fakeaway",
      ing: [["chicken-thigh", 220], ["peri-peri", 30], ["jasmine-rice", 70], ["peppers", 60], ["corn", 80], ["greek-yog", 40]],
      method: ["Marinate the thighs in peri-peri sauce; grill or air-fry at 200°C for 18 minutes.", "Spicy rice: cook rice with paprika, peppers and a stock cube.", "Corn on the side; yoghurt and garlic to dip."] },
    { id: "d-burrito-bowl", slot: "dinner", name: "Chicken burrito bowl", time: "25 min", tag: "Spicy",
      ing: [["chicken-breast", 180], ["jasmine-rice", 70], ["kidney-beans", 80], ["corn", 60], ["salsa", 60], ["lettuce", 40], ["greek-yog", 40], ["mozzarella", 20], ["lime", 15]],
      method: ["Season the chicken with chipotle or fajita spice; grill and slice.", "Lime and coriander rice.", "Build with beans, corn, salsa, lettuce, a little cheese and yoghurt as soured cream."] },
    { id: "d-chilli", slot: "dinner", name: "Beef chilli con carne", time: "40 min", tag: "Spicy",
      ing: [["beef-mince", 180], ["kidney-beans", 100], ["chopped-tom", 200], ["onion", 60], ["peppers", 60], ["garlic", 5], ["jasmine-rice", 70], ["greek-yog", 40]],
      prep: "batch-cook the chilli and portion it",
      method: ["Brown the mince; soften onion, peppers and garlic.", "Add cumin, smoked paprika and chilli; tomatoes and beans.", "Simmer 30 minutes. Rice and a spoon of yoghurt."] },
    { id: "d-massaman", slot: "dinner", name: "Beef massaman curry", time: "2 h (or batch)", tag: "Thai",
      ing: [["beef-shin", 180], ["potatoes", 150], ["coconut-light", 120], ["curry-paste", 25], ["onion", 50], ["peanuts", 10], ["jasmine-rice", 50]],
      prep: "slow-cook the massaman and portion it",
      method: ["Brown the beef; fry the paste.", "Add coconut milk, water, onion and a little fish sauce and sugar; simmer low for 1½ hours.", "Add potato chunks for the last 30 minutes. Peanuts on top; a small portion of rice."] },

    // ---- Dinners ----
    { id: "d-ragu", slot: "dinner", name: "Beef ragù pappardelle", time: "20 min on the day", tag: "Italian",
      ing: [["beef-shin", 180], ["onion", 60], ["garlic", 5], ["passata", 200], ["olive-oil", 5], ["pasta", 100], ["parmesan", 15]],
      prep: "slow-cook the beef ragù and freeze in portions",
      method: ["Brown the shin in batches; soften onion and garlic.", "Add passata and a splash of stock; cook low for 3 hours (or 50 minutes in a pressure cooker).", "Shred and reduce. Toss with pappardelle, pasta water and parmesan."] },
    { id: "d-chicken-parm", slot: "dinner", name: "Chicken parmigiana", time: "30 min", tag: "Italian",
      ing: [["chicken-breast", 200], ["eggs", 25], ["panko", 30], ["olive-oil", 5], ["passata", 120], ["mozzarella", 50], ["parmesan", 10], ["pasta", 90]],
      method: ["Butterfly and flatten the breast; egg and panko.", "Air-fry at 200°C for 12 minutes, spritzed with the oil.", "Top with seasoned passata, mozzarella and parmesan; 3 more minutes.", "Serve with spaghetti tossed in the rest of the sauce."] },
    { id: "d-gyros", slot: "dinner", name: "Chicken gyros wrap and fries", time: "30 min",
      ing: [["chicken-thigh", 200], ["greek-yog", 60], ["wrap", 62], ["potatoes", 250], ["olive-oil", 5], ["onion", 30], ["lettuce", 30], ["tomato", 50]],
      method: ["Marinate thighs in oregano, garlic, lemon and paprika.", "Grill or air-fry at 200°C for 18 minutes; slice.", "Air-fry chips at 200°C for 20 minutes.", "Wrap with tzatziki-style yoghurt, salad and a few chips inside."] },
    { id: "d-honey-garlic", slot: "dinner", name: "Honey garlic chicken and rice", time: "25 min",
      ing: [["chicken-thigh", 220], ["honey", 20], ["soy", 20], ["garlic", 5], ["jasmine-rice", 90], ["broccoli", 120], ["sesame-oil", 5]],
      method: ["Sear diced thighs until coloured.", "Add garlic, honey and soy; reduce to a glaze.", "Serve with rice and charred broccoli; finish with sesame oil."] },

    { id: "d-smash", slot: "dinner", name: "Smash burgers and fries", time: "25 min", tag: "Fakeaway",
      ing: [["beef-mince", 180], ["cheese-slice", 20], ["brioche", 60], ["light-mayo", 10], ["ketchup", 10], ["gherkins", 20], ["lettuce", 20], ["onion", 20], ["potatoes", 250], ["olive-oil", 5]],
      method: ["Air-fry chips at 200°C for 20 minutes.", "Two 90 g balls; smash hard on a ripping-hot dry pan, season, 2 minutes a side.", "Cheese on, stack in a toasted bun with burger sauce (mayo and ketchup), pickles and onion."] },
    { id: "d-crispy-burger", slot: "dinner", name: "Crispy chicken burger and fries", time: "30 min", tag: "Fakeaway",
      ing: [["chicken-breast", 200], ["eggs", 25], ["panko", 30], ["brioche", 60], ["light-mayo", 15], ["sriracha", 5], ["lettuce", 30], ["potatoes", 250], ["olive-oil", 5]],
      method: ["Butterfly the breast; egg and panko with paprika and garlic salt.", "Air-fry at 200°C for 12–14 minutes, spritzed with oil.", "Air-fry chips alongside.", "Bun with sriracha mayo and lettuce."] },
    { id: "d-philly", slot: "dinner", name: "Philly cheesesteak and fries", time: "25 min", tag: "Fakeaway",
      ing: [["steak", 180], ["onion", 60], ["peppers", 60], ["cheese-slice", 40], ["sub-roll", 90], ["potatoes", 150], ["olive-oil", 5]],
      method: ["Freeze the steak 20 minutes, then slice paper-thin.", "Cook onions and peppers soft; flash-fry the steak.", "Lay cheese over in the pan to melt; pile into the toasted roll.", "Small portion of air-fryer chips."] },
    { id: "d-bbq-chicken", slot: "dinner", name: "BBQ pulled chicken bun and slaw", time: "30 min",
      ing: [["chicken-thigh", 200], ["bbq", 30], ["brioche", 60], ["cabbage", 80], ["light-mayo", 15], ["potatoes", 200], ["olive-oil", 5]],
      method: ["Poach or pressure-cook the thighs with smoked paprika; shred.", "Toss with BBQ sauce.", "Slaw: shredded cabbage, light mayo, vinegar.", "Bun, slaw and a small portion of chips."] },

    { id: "d-fried-rice", slot: "dinner", name: "Chicken fried rice", time: "20 min", tag: "Fakeaway",
      ing: [["chicken-breast", 180], ["jasmine-rice", 90], ["eggs", 100], ["peas", 60], ["onion", 30], ["soy", 20], ["sesame-oil", 7]],
      method: ["Use day-old cooked rice.", "Wok the diced chicken hard; push aside and scramble the eggs.", "Add rice, peas and spring onion; soy and sesame oil to finish."] },
    { id: "d-beef-broccoli", slot: "dinner", name: "Beef and broccoli stir-fry", time: "20 min", tag: "Fakeaway",
      ing: [["steak", 180], ["broccoli", 150], ["soy", 20], ["cornflour", 8], ["honey", 10], ["garlic", 5], ["jasmine-rice", 90], ["sesame-oil", 5]],
      method: ["Slice steak thin; toss in half the cornflour.", "Sear in batches; blanch the broccoli.", "Sauce: soy, honey, garlic, remaining cornflour and water; toss to gloss.", "Serve with rice."] },
    { id: "d-salt-pepper", slot: "dinner", name: "Salt and pepper chicken", time: "25 min", tag: "Fakeaway",
      ing: [["chicken-breast", 200], ["cornflour", 20], ["olive-oil", 8], ["peppers", 60], ["onion", 50], ["jasmine-rice", 90]],
      method: ["Dust diced chicken in cornflour; air-fry at 200°C for 12 minutes, spritzed.", "Wok the onion, peppers, garlic and chilli.", "Toss the chicken in with salt, pepper and five-spice. Serve with rice."] },
    { id: "d-sweet-sour", slot: "dinner", name: "Sweet and sour chicken", time: "25 min", tag: "Fakeaway",
      ing: [["chicken-breast", 200], ["cornflour", 20], ["olive-oil", 5], ["pineapple", 80], ["peppers", 60], ["onion", 50], ["ketchup", 25], ["honey", 10], ["jasmine-rice", 90]],
      method: ["Cornflour-dust and air-fry the chicken as for salt and pepper.", "Sauce: ketchup, honey, rice vinegar, soy and pineapple juice; thicken.", "Toss with pineapple, peppers and onion. Serve with rice."] },

    { id: "d-doner", slot: "dinner", name: "Doner kebab and chips", time: "15 min on the day", tag: "Fakeaway",
      ing: [["lamb-mince", 200], ["wrap", 62], ["greek-yog", 50], ["garlic", 3], ["lettuce", 40], ["onion", 30], ["tomato", 50], ["sriracha", 10], ["potatoes", 200], ["olive-oil", 5]],
      prep: "mix and bake the doner loaf, chill, slice thin",
      method: ["Blitz mince with garlic, cumin, oregano and paprika to a paste; bake as a tight loaf at 180°C for 50 minutes.", "Chill, then slice paper-thin and crisp in a hot pan.", "Wrap with salad, garlic yoghurt and chilli; chips on the side."] },
    { id: "d-shish", slot: "dinner", name: "Chicken shish wrap and chips", time: "30 min",
      ing: [["chicken-breast", 220], ["greek-yog", 60], ["wrap", 62], ["lettuce", 40], ["tomato", 50], ["onion", 30], ["potatoes", 250], ["olive-oil", 5]],
      method: ["Marinate chicken in yoghurt, paprika, cumin and lemon.", "Skewer and grill or air-fry at 220°C for 14 minutes.", "Wrap with salad and garlic yoghurt; chips on the side."] },
    { id: "d-kofta", slot: "dinner", name: "Lamb kofta and rice", time: "25 min",
      ing: [["lamb-mince", 200], ["onion", 30], ["jasmine-rice", 80], ["greek-yog", 60], ["tahini", 10], ["cucumber", 60], ["tomato", 60]],
      method: ["Mix mince with grated onion, cumin, coriander and parsley; shape onto skewers.", "Grill hard for 8–10 minutes.", "Rice, chopped salad and tahini yoghurt."] },
    { id: "d-kebab-fries", slot: "dinner", name: "Loaded chicken kebab fries", time: "30 min", tag: "Fakeaway",
      ing: [["chicken-thigh", 200], ["potatoes", 350], ["olive-oil", 5], ["mozzarella", 30], ["greek-yog", 60], ["garlic", 3], ["sriracha", 10], ["onion", 30], ["lettuce", 30]],
      method: ["Air-fry chips at 200°C for 22 minutes.", "Grill spiced thighs and slice.", "Chips, chicken, a little cheese to melt, then garlic yoghurt, chilli sauce, onion and lettuce."] },

    { id: "d-bigmac", slot: "dinner", name: "Big Mac bowl", time: "25 min", tag: "Fakeaway",
      ing: [["beef-mince", 200], ["onion", 30], ["potatoes", 350], ["olive-oil", 5], ["lettuce", 60], ["gherkins", 30], ["cheese-slice", 20], ["light-mayo", 20], ["ketchup", 10]],
      method: ["Air-fry cubed potatoes at 200°C for 22 minutes.", "Brown the mince with onion; season well.", "Shredded lettuce, potatoes, mince, cheese, gherkins.", "Sauce: light mayo, ketchup, mustard, gherkin brine, paprika."] },
    { id: "d-pizza", slot: "dinner", name: "Chicken and pepperoni pizza", time: "20 min", tag: "Fakeaway",
      ing: [["pizza-base", 150], ["passata", 60], ["mozzarella", 80], ["chicken-breast", 120], ["turkey-pepperoni", 40]],
      method: ["Oven at its hottest with a tray inside.", "Season passata with oregano and garlic; spread thin.", "Top with cooked sliced chicken, mozzarella and pepperoni.", "8–10 minutes until blistered."] },
    { id: "d-meatball-sub", slot: "dinner", name: "Meatball marinara sub", time: "30 min", tag: "Italian",
      ing: [["beef-mince", 180], ["panko", 15], ["eggs", 15], ["passata", 120], ["garlic", 3], ["mozzarella", 40], ["parmesan", 10], ["sub-roll", 90]],
      method: ["Mix mince, panko, egg, garlic, parmesan and herbs; roll 6 meatballs.", "Brown, then simmer in seasoned passata for 12 minutes.", "Into the toasted roll, mozzarella on top, grill to melt."] },
    { id: "d-quesadilla", slot: "dinner", name: "Chicken quesadillas", time: "20 min",
      ing: [["chicken-breast", 180], ["wrap", 124], ["mozzarella", 50], ["peppers", 60], ["onion", 40], ["salsa", 50], ["greek-yog", 40]],
      method: ["Fajita-spice the sliced chicken; cook with onions and peppers.", "Fill two wraps with the mix and cheese; fold.", "Dry pan, 2 minutes a side until crisp. Salsa and yoghurt to dip."] },

    { id: "d-carbonara", slot: "dinner", name: "High-protein carbonara", time: "20 min", tag: "Italian",
      ing: [["bacon", 120], ["eggs", 120], ["pecorino", 25], ["pasta", 110], ["chicken-breast", 100]],
      method: ["Crisp diced bacon medallions; pan-fry the sliced chicken alongside.", "Whisk 2 eggs, 1 yolk, pecorino and lots of black pepper.", "Off the heat, toss pasta with the meat, then the egg mix and pasta water until glossy."] },
    { id: "d-lasagne", slot: "dinner", name: "Lean beef lasagne", time: "15 min on the day", tag: "Italian",
      ing: [["beef-mince", 180], ["onion", 50], ["garlic", 3], ["passata", 150], ["lasagne-sheets", 70], ["skimmed-milk", 150], ["cornflour", 12], ["parmesan", 15], ["mozzarella", 30]],
      prep: "build and bake the lasagne, portion and chill or freeze",
      method: ["Ragù: brown mince, onion and garlic; passata and herbs; simmer 30 minutes.", "White sauce: skimmed milk thickened with cornflour, nutmeg and half the parmesan.", "Layer, top with mozzarella and parmesan; bake at 190°C for 40 minutes. Rest before cutting."] },
    { id: "d-prawn-linguine", slot: "dinner", name: "Prawn arrabbiata linguine", time: "20 min", tag: "Italian",
      ing: [["prawns", 200], ["chopped-tom", 200], ["garlic", 5], ["olive-oil", 10], ["pasta", 110], ["parmesan", 10]],
      method: ["Garlic and chilli in the oil; add tomatoes and reduce 10 minutes.", "Prawns in for 2 minutes.", "Toss with linguine and pasta water; parmesan and parsley."] },
    { id: "d-steak-chips", slot: "dinner", name: "Steak, chips and rocket", time: "30 min",
      ing: [["steak", 250], ["potatoes", 350], ["olive-oil", 8], ["rocket", 40], ["parmesan", 10]],
      method: ["Air-fry thick chips at 200°C for 25 minutes.", "Steak at room temperature; hot pan, 2–3 minutes a side, rest 5.", "Rocket and parmesan on the side."] },

    { id: "d-roast-chicken", slot: "dinner", name: "Roast chicken dinner", time: "1 h 20", tag: "Sunday",
      ing: [["chicken-breast", 220], ["potatoes", 350], ["olive-oil", 8], ["greens", 150], ["peas", 60], ["gravy", 100]],
      method: ["Parboil potatoes 8 minutes, rough up, roast at 200°C with the oil for 45 minutes.", "Roast the chicken until 74°C in the middle; rest.", "Greens, peas and gravy."] },
    { id: "d-roast-beef", slot: "dinner", name: "Roast beef dinner", time: "1 h 30", tag: "Sunday",
      ing: [["topside", 220], ["potatoes", 350], ["olive-oil", 8], ["greens", 150], ["gravy", 100]],
      method: ["Sear the topside; roast at 180°C to 52°C core for pink. Rest 20 minutes.", "Roast potatoes as for the chicken.", "Carve thin; greens and gravy."] },
    { id: "d-pasta-bake", slot: "dinner", name: "Chicken and bacon pasta bake", time: "35 min", tag: "Italian",
      ing: [["chicken-breast", 180], ["bacon", 60], ["penne", 100], ["passata", 150], ["garlic", 3], ["mozzarella", 50], ["parmesan", 10]],
      method: ["Cook penne 2 minutes short.", "Brown chicken and bacon; add garlic and passata.", "Mix with the pasta, top with mozzarella and parmesan; bake at 200°C for 15 minutes."] },
    { id: "d-roast-pork", slot: "dinner", name: "Roast pork dinner", time: "1 h 30", tag: "Sunday",
      ing: [["pork-loin", 200], ["potatoes", 350], ["olive-oil", 8], ["greens", 150], ["apple", 50], ["gravy", 100]],
      method: ["Roast the loin at 180°C to 63°C core; rest.", "Roast potatoes as usual.", "Quick apple sauce, greens and gravy."] }
  ];

  // Options per weekday (0 = Sunday), per app. First option is the default.
  const OPTIONS = {
    bro: {
      dinner: {
        1: ["d-ragu", "d-chicken-parm", "d-gyros", "d-honey-garlic"],
        2: ["d-smash", "d-crispy-burger", "d-philly", "d-bbq-chicken"],
        3: ["d-fried-rice", "d-beef-broccoli", "d-salt-pepper", "d-sweet-sour"],
        4: ["d-doner", "d-shish", "d-kofta", "d-kebab-fries"],
        5: ["d-bigmac", "d-pizza", "d-meatball-sub", "d-quesadilla"],
        6: ["d-carbonara", "d-lasagne", "d-prawn-linguine", "d-steak-chips"],
        0: ["d-roast-chicken", "d-roast-beef", "d-pasta-bake", "d-roast-pork"]
      },
      lunch: {
        1: ["l-salmon-poke", "l-tuna-poke", "l-teriyaki"],
        2: ["l-teriyaki", "l-shawarma", "l-bulgogi"],
        3: ["l-bulgogi", "l-teriyaki", "l-prawn-egg"],
        4: ["l-prawn-egg", "l-spicy-salmon", "l-shawarma"],
        5: ["l-shawarma", "l-bulgogi", "l-tuna-poke"],
        6: ["l-spicy-salmon", "l-salmon-poke", "l-prawn-egg"],
        0: ["l-onigiri", "l-tuna-poke", "l-teriyaki"]
      },
      breakfast: {
        1: ["bf-eggs", "bf-oats"], 2: ["bf-oats", "bf-eggs"], 3: ["bf-eggs", "bf-oats"], 4: ["bf-oats", "bf-eggs"],
        5: ["bf-eggs", "bf-oats"], 6: ["bf-oats", "bf-eggs"], 0: ["bf-eggs", "bf-oats"]
      }
    },
    gyal: {
      dinner: {
        1: ["d-thai-green-curry", "d-chicken-parm", "d-honey-garlic", "d-gyros"],
        2: ["d-peri-peri", "d-crispy-burger", "d-burrito-bowl", "d-smash"],
        3: ["d-pad-thai", "d-salt-pepper", "d-sweet-sour", "d-fried-rice"],
        4: ["d-tikka", "d-jalfrezi", "d-shish", "d-doner"],
        5: ["d-katsu-curry", "d-pizza", "d-quesadilla", "d-bigmac"],
        6: ["d-thai-basil", "d-chilli", "d-prawn-linguine", "d-steak-chips"],
        0: ["d-roast-chicken", "d-massaman", "d-roast-beef", "d-lasagne"]
      },
      lunch: {
        1: ["l-thai-beef-salad", "l-salmon-poke", "l-teriyaki"],
        2: ["l-caesar", "l-shawarma", "l-bulgogi"],
        3: ["l-satay-noodle", "l-teriyaki", "l-prawn-egg"],
        4: ["l-prawn-mango", "l-spicy-salmon", "l-shawarma"],
        5: ["l-spicy-tuna-salad", "l-tuna-poke", "l-bulgogi"],
        6: ["l-caesar", "l-thai-beef-salad", "l-salmon-poke"],
        0: ["l-satay-noodle", "l-onigiri", "l-spicy-tuna-salad"]
      },
      breakfast: {
        1: ["bf-eggs", "bf-oats"], 2: ["bf-oats", "bf-eggs"], 3: ["bf-eggs", "bf-oats"], 4: ["bf-oats", "bf-eggs"],
        5: ["bf-eggs", "bf-oats"], 6: ["bf-oats", "bf-eggs"], 0: ["bf-eggs", "bf-oats"]
      }
    }
  };
  // Snack options are the same for both apps; the first is the day's default.
  const SNACKS = { 1: "s-choc-mousse", 2: "s-brownie", 3: "s-cheesecake", 4: "s-bark", 5: "s-crumble", 6: "s-pbj", 0: "snack" };
  const ALL_SNACKS = ["s-choc-mousse", "s-brownie", "s-cheesecake", "s-bark", "s-crumble", "s-pbj", "snack"];
  ["bro", "gyal"].forEach(function (k) { OPTIONS[k].snack = {}; for (let d = 0; d < 7; d++) { OPTIONS[k].snack[d] = [SNACKS[d]].concat(ALL_SNACKS.filter(function (x) { return x !== SNACKS[d]; })); } });

  // Batch prep: [Sunday job, what's left on the day]. Mon–Sat meals are cooked on Sunday where it works.
  const PREP = {
    "l-salmon-poke": ["Per portion: season the salmon with ½ tsp salt and 1 tsp soy, roast at 200°C for 12 min, then flake. Slice the cucumber into half-moons and toss with a pinch of salt and 1 tsp rice vinegar. Sauce pot: 10 g light mayo, 10 g sriracha, 10 ml soy, ½ tsp sesame oil. Box with the edamame", "Microwave the rice until steaming, top with the cold salmon and veg, add sauce. 3 min"],
    "l-tuna-poke": ["Per portion: quick-pickle the cucumber (1 tsp rice vinegar, pinch of salt and sugar). Box rice with edamame and cucumber. Tuna pot: drained tuna mixed with 15 g light mayo, 10 g sriracha, 10 ml soy and a squeeze of lime. Make Thursday's tuna on Wednesday night", "Microwave the rice until steaming, top with tuna and veg. 3 min"],
    "l-teriyaki": ["Per portion: marinate the thighs 30 min in 15 ml teriyaki, 5 ml soy, 1 grated garlic clove and 1 tsp grated ginger. Air-fry at 200°C for 18 min, brushing with another 15 ml teriyaki for the last 5. Slice. Steam the greens 3 min, toss in a few drops of sesame oil and a pinch of salt. Box with rice, furikake in a twist of foil", "Microwave until steaming throughout. 3 min"],
    "l-bulgogi": ["For all portions: brown the mince hard in a dry pan in batches. Per portion add 1 grated garlic clove, 1 tsp grated ginger, 20 g gochujang, 15 ml soy and 5 g honey; cook down until sticky, finish with 5 ml sesame oil and sliced spring onion. Box with rice; kimchi in a separate pot", "Microwave until steaming, kimchi on top. 3 min"],
    "l-prawn-egg": ["Boil the eggs 7 min, into iced water, peel. Per portion: toss the prawns in 10 ml soy, ½ tsp sesame oil and a pinch of chilli flakes; mix 10 g light mayo with 1 tsp sriracha in a pot. Box rice with edamame; eggs and prawns in a separate tub", "Microwave the rice until steaming, add the cold prawns, halved eggs, mayo and furikake. 2 min"],
    "l-shawarma": ["Per portion marinade: 30 g Greek yoghurt, 1 tsp each cumin and smoked paprika, ½ tsp each turmeric, cinnamon and garlic granules, juice of ¼ lemon, ½ tsp salt, 5 ml olive oil. Marinate the thighs 1 hour (or overnight), roast at 220°C for 20 min, rest and slice. Tahini sauce: 30 g yoghurt, 8 g tahini, squeeze of lemon, pinch of salt. Chop cucumber and tomato with parsley; pickles in the salad pot", "Microwave chicken and rice until steaming, add the cold salad and sauce. 3 min"],
    "l-spicy-salmon": ["Per portion: season the salmon with salt and pepper, roast at 200°C for 12 min, flake and mix with 15 g light mayo, 15 g sriracha and 5 ml soy. Season the rice with the sushi vinegar. Box with sliced cucumber and edamame, furikake on top", "Microwave the rice until steaming, top with the salmon mix. 2 min"],
    "l-onigiri": ["Sunday lunch: make fresh. Season the rice with sushi vinegar; fill with tuna mixed with light mayo and a little soy; shape with wet, salted hands; roll the edges in furikake", "Eat cold. 0 min"],
    "l-thai-beef-salad": ["Per portion: rub the steak with ½ tsp salt and pepper, sear 2 min a side in a ripping-hot pan, rest 5 min, slice thin. Soak the noodles in boiling water 5 min, rinse cold, toss in a few drops of oil. Dressing jar per portion: juice of ½ lime, 15 ml fish sauce, 5 g honey, ½ chopped red chilli, ½ grated garlic clove. Slice the cucumber, tomato and red onion; pick the mint and coriander. Peanuts crushed in a separate bag", "Toss everything with the dressing, peanuts on top. 2 min"],
    "l-caesar": ["Per portion: rub the chicken with 5 ml olive oil, ½ tsp garlic granules, ½ tsp dried oregano, salt, pepper and lemon zest; grill or air-fry at 200°C for 15–18 min to 74°C inside; rest and slice. Croutons: cube the sourdough, spray with oil, pinch of salt and garlic granules, bake at 200°C for 8 min. Dressing jar: 50 g Greek yoghurt, 10 g light mayo, 1 grated garlic clove, 1 tsp Dijon, juice of ¼ lemon, a few drops of Worcestershire, 1 tbsp grated parmesan, black pepper. Wash, dry and chop the cos", "Toss lettuce, chicken and dressing, croutons and the rest of the parmesan on top. 2 min"],
    "l-satay-noodle": ["Per portion: poach the chicken in simmering water with a slice of ginger for 12 min, cool and shred. Noodles: soak 5 min, rinse cold, toss in a little oil. Satay sauce jar per portion: 20 g peanut butter, 15 ml soy, juice of ⅓ lime, 5 g honey, 5 g sriracha, ½ grated garlic clove, loosened with 2–3 tbsp hot water. Julienne the cucumber and peppers; keep the beansprouts separate", "Toss everything with the sauce, cold. Coriander if you have it. 2 min"],
    "l-prawn-mango": ["Dice the mango and cucumber and shred the lettuce. Dressing jar per portion: juice of ⅓ lime, 10 g sriracha, 5 g honey, pinch of salt, chopped coriander. Box the rice; prawns in a separate tub. Keep the avocado whole until the day", "Microwave the rice until steaming, add prawns, mango, avocado and dressing. 3 min"],
    "l-spicy-tuna-salad": ["Season the rice with the sushi vinegar and box with edamame, sliced cucumber and shredded lettuce. Sauce pot per portion: 15 g light mayo, 15 g sriracha, a squeeze of lime", "Mix the tuna with the sauce, build over the leaves and warm rice, furikake on top. 3 min"],

    "d-ragu": ["For all portions: season the shin with salt and pepper and brown hard in batches. Per portion soften 60 g diced onion, plus carrot and celery if you have them, with 1 garlic clove and a sprig of rosemary; add 1 tsp tomato purée, 200 g passata, 100 ml beef stock, a bay leaf and ½ tsp dried oregano. Cover and cook low (150°C oven) for 3 hours, or 50 min in a pressure cooker. Shred, reduce until thick, season, portion", "Reheat the ragù until piping hot, toss with the pasta, a splash of water and parmesan. 6 min"],
    "d-chicken-parm": ["Per portion: butterfly and bash the breast to 1.5 cm; season with salt, pepper and garlic granules; dip in beaten egg then panko mixed with 1 tsp dried oregano and 1 tbsp grated parmesan. Freeze raw on a lined tray, then bag. Marinara: 120 g passata simmered 10 min with ½ garlic clove, ½ tsp oregano, a pinch of chilli, salt and a few torn basil leaves; portion", "Air-fry the chicken from frozen at 200°C for 18 min, sauce and mozzarella on for 3 min; reheat the pasta in the rest of the sauce. 20 min hands-off"],
    "d-gyros": ["Per portion marinade: 30 g Greek yoghurt, juice of ¼ lemon, 1 grated garlic clove, 1 tsp dried oregano, 1 tsp smoked paprika, ½ tsp cumin, ½ tsp salt, 5 ml olive oil. Marinate the thighs 1 hour, grill or air-fry at 200°C for 18 min, slice and portion. Tzatziki: 30 g yoghurt, 30 g grated and squeezed cucumber, ½ garlic clove, a few mint leaves, salt. Slice the red onion and tomato", "Air-fry the chips 15 min; warm the chicken; build the wrap with tzatziki, salad and a few chips. 15 min"],
    "d-honey-garlic": ["Per portion: season the diced thighs with salt and pepper and sear until golden. Sauce: 20 g honey, 20 ml soy, 2 grated garlic cloves, 1 tsp rice vinegar and a pinch of chilli flakes; reduce over the chicken to a sticky glaze. Char the broccoli in a hot pan with a pinch of salt. Box with rice, sesame seeds and spring onion on top", "Microwave until steaming. 4 min"],
    "d-smash": ["Per portion: weigh 2 × 90 g balls of mince (don't season yet), freeze between squares of baking paper. Burger sauce pot: 10 g light mayo, 10 g ketchup, 1 tsp American mustard, 1 tsp chopped gherkin plus a splash of its brine, pinch of smoked paprika. Slice the onion very thin", "Air-fry the chips 15 min. Smash each ball on a ripping-hot dry pan, season with salt and pepper, 2 min, flip, cheese on, 1 min. Build in a toasted bun. 15 min"],
    "d-crispy-burger": ["Per portion: butterfly the breast; season with ½ tsp smoked paprika, ½ tsp garlic granules, ¼ tsp cayenne, salt and pepper; dip in beaten egg, then panko seasoned the same way. Freeze raw on a lined tray, then bag. Sriracha mayo pot: 15 g light mayo, 5 g sriracha, squeeze of lime", "Air-fry chicken and chips together at 200°C for 18 min; bun, lettuce and sriracha mayo. 20 min hands-off"],
    "d-philly": ["Freeze the steak 20 min, slice paper-thin and freeze flat in portion bags. Per portion: slice 60 g onion and 60 g peppers and cook slowly in a little oil with a pinch of salt for 15 min until soft and sweet; season with black pepper and a few drops of Worcestershire; portion", "Flash-fry the steak 2 min with the veg, season, lay the cheese over to melt, pile into the toasted roll. Air-fry the chips. 15 min"],
    "d-bbq-chicken": ["Per portion: rub the thighs with 1 tsp smoked paprika, ½ tsp garlic granules, ½ tsp onion powder, salt and pepper. Pressure-cook 12 min, or poach covered 25 min, in 100 ml stock. Shred and toss with 30 g BBQ sauce and a splash of the cooking liquid. Slaw: shred 80 g cabbage (plus carrot); dressing pot of 15 g light mayo, 1 tsp cider vinegar, pinch of salt", "Reheat the chicken until steaming; air-fry the chips; dress the slaw; build. 15 min"],
    "d-fried-rice": ["Cook the rice for this the day before if you can (Saturday) and chill it. Per portion: wok the diced chicken hard with salt and white pepper, push aside and scramble 2 eggs; add the cold rice, 60 g peas and chopped spring onion; season with 20 ml soy and 7 ml sesame oil. Cool fast and portion", "Microwave or stir-fry until piping hot. 4 min"],
    "d-beef-broccoli": ["Per portion: slice the steak thin and toss in 4 g cornflour, ½ tsp soy and a pinch of salt; sear in batches in a very hot wok. Blanch the broccoli 2 min. Sauce: 20 ml soy, 10 g honey, 1 grated garlic clove, 1 tsp grated ginger, 4 g cornflour and 60 ml water, simmered until glossy; toss everything together. Portion with rice", "Microwave until steaming. 4 min"],
    "d-salt-pepper": ["Per portion: dice the chicken and toss in 20 g cornflour seasoned with ½ tsp salt, ½ tsp black pepper and ¼ tsp Chinese five-spice; spray with oil and air-fry at 200°C for 12 min. Wok the sliced onion and peppers with 1 garlic clove and ½ red chilli. Mix a seasoning pot: ½ tsp salt, ½ tsp pepper, ¼ tsp five-spice, pinch of sugar. Portion the chicken, veg and rice separately", "Air-fry the chicken 5 min to re-crisp, toss with the veg and the seasoning; microwave the rice. 8 min"],
    "d-sweet-sour": ["Per portion: dice and cornflour-coat the chicken as for salt and pepper; air-fry at 200°C for 12 min. Sauce: 25 g ketchup, 10 g honey, 15 ml rice vinegar, 10 ml soy, 50 ml pineapple juice from the tin, 3 g cornflour; simmer until glossy. Wok the peppers and onion, add the pineapple and sauce, toss the chicken through. Portion with rice", "Microwave until steaming. 4 min"],
    "d-doner": ["Per portion: blitz the mince to a smooth paste with ½ tsp salt, ½ tsp cumin, ½ tsp ground coriander, ½ tsp dried oregano, ½ tsp smoked paprika, ¼ tsp chilli flakes, ½ tsp garlic granules and ½ tsp onion powder. Pack into a tight loaf, wrap in foil and bake at 180°C for 50 min, then 10 min uncovered. Chill, slice paper-thin, portion. Garlic sauce: 50 g Greek yoghurt, 1 grated garlic clove, squeeze of lemon, pinch of salt and dried mint. Slice the onion and tomato", "Crisp the doner slices in a hot dry pan 3 min; air-fry the chips; wrap with salad, garlic sauce and chilli sauce. 15 min"],
    "d-shish": ["Per portion marinade: 40 g Greek yoghurt, 1 tsp smoked paprika, ½ tsp cumin, ½ tsp chilli flakes, 1 grated garlic clove, juice of ¼ lemon, 1 tsp tomato purée, ½ tsp salt. Marinate the cubed chicken at least 2 hours, skewer and grill or air-fry at 220°C for 14 min; portion. Garlic sauce as for the doner", "Warm the chicken; air-fry the chips; wrap with salad and garlic sauce. 15 min"],
    "d-kofta": ["Per portion: mix the mince with 30 g grated and squeezed onion, 1 grated garlic clove, ½ tsp each cumin, ground coriander and smoked paprika, ¼ tsp cinnamon, ½ tsp salt and a handful of chopped parsley. Shape onto skewers and grill hard 8–10 min. Tahini yoghurt: 50 g yoghurt, 10 g tahini, lemon, salt. Chop cucumber and tomato with parsley. Portion with rice", "Microwave the koftas and rice until steaming, add salad and sauce. 5 min"],
    "d-kebab-fries": ["Per portion: marinate the thighs in 20 g yoghurt, 1 tsp smoked paprika, ½ tsp cumin, ½ tsp garlic granules, ¼ tsp chilli flakes and ½ tsp salt; grill or air-fry at 200°C for 18 min, slice. Garlic sauce: 60 g yoghurt, 1 grated garlic clove, lemon, salt, dried mint. Slice the onion and shred the lettuce", "Air-fry the chips 15 min, add the chicken and cheese for 3 min, top with sauce, chilli sauce, onion and lettuce. 18 min"],
    "d-bigmac": ["Per portion: brown the mince hard with 30 g finely diced onion, ½ tsp salt, ½ tsp black pepper, ½ tsp garlic granules and a dash of Worcestershire; portion. Big Mac sauce pot: 20 g light mayo, 10 g ketchup, 1 tsp American mustard, 1 tsp finely chopped gherkin plus a splash of brine, ¼ tsp smoked paprika, ¼ tsp onion powder. Shred the lettuce", "Air-fry the potatoes 15 min, reheat the mince until steaming, build the bowl with cheese, gherkins and sauce. 15 min"],
    "d-pizza": ["Per portion: season the chicken with ½ tsp dried oregano, ½ tsp garlic granules, salt and pepper, grill and slice. Pizza sauce pot: 60 g passata, ½ tsp dried oregano, ½ grated garlic clove, pinch of salt, sugar and chilli flakes", "Spread the sauce thin, top and bake on a hot tray at the oven's hottest for 8–10 min. 12 min"],
    "d-meatball-sub": ["Per portion: mix the mince with 15 g panko, 15 g beaten egg, 1 grated garlic clove, 10 g grated parmesan, ½ tsp dried oregano, ½ tsp salt and black pepper; roll 6 meatballs and brown. Simmer 12 min in 120 g passata with ½ garlic clove, ½ tsp oregano, a pinch of chilli flakes and torn basil. Portion", "Reheat until piping hot, fill the toasted roll, mozzarella on top, grill to melt. 8 min"],
    "d-quesadilla": ["Per portion: slice the chicken and toss in 1 tsp smoked paprika, ½ tsp cumin, ½ tsp garlic granules, ½ tsp chilli powder, ¼ tsp oregano, salt and a squeeze of lime; cook hot with the sliced peppers and onion. Cool and portion. Salsa and yoghurt in separate pots", "Fill the wraps with the cold filling and cheese; dry-fry 2 min a side. 6 min"],
    "d-carbonara": ["Per portion: dice the bacon medallions and crisp in a dry pan. Season the chicken with salt and pepper, pan-fry and slice. Box the meat together. Grate the pecorino into a separate pot", "Cook the spaghetti; whisk 2 eggs, 1 yolk, the pecorino and plenty of black pepper; off the heat toss pasta, meat, egg mix and a splash of pasta water until glossy. 12 min, best fresh"],
    "d-lasagne": ["Ragù per portion: brown the mince with 50 g onion and 1 garlic clove, add 150 g passata, 1 tsp tomato purée, ½ tsp oregano, a bay leaf, salt and pepper; simmer 30 min. White sauce per portion: 150 ml skimmed milk thickened with 12 g cornflour, a pinch of nutmeg, salt, pepper and half the parmesan. Layer ragù, sheets and white sauce; top with mozzarella and the rest of the parmesan; bake at 190°C for 40 min. Rest 15 min, cut, portion", "Microwave until piping hot. 5 min"],
    "d-prawn-linguine": ["Arrabbiata per portion: 10 ml olive oil, 2 sliced garlic cloves and ½ tsp chilli flakes warmed gently, then 200 g chopped tomatoes, a pinch of sugar and salt; simmer 15 min until thick. Portion", "Cook the linguine 9 min, reheat the sauce, prawns in for 2 min, toss with pasta water, parsley and parmesan. 12 min"],
    "d-steak-chips": ["Nothing to cook. Steak is best fresh. Take it out of the fridge 30 min before cooking", "Air-fry the chips 15 min; season the steak with salt and pepper, sear 2–3 min a side with a knob of butter, garlic and thyme for the last minute; rest 5 min. 15 min"],
    "d-roast-chicken": ["Sunday dinner: cook fresh", "Season the chicken with salt, pepper, garlic, thyme and lemon; roast to 74°C inside. About an hour"],
    "d-roast-beef": ["Sunday dinner: cook fresh", "Rub the topside with salt, pepper, mustard and rosemary; sear, roast at 180°C to 52°C inside; rest 20 min. About 1½ hours"],
    "d-roast-pork": ["Sunday dinner: cook fresh", "Score the fat, rub with salt and fennel seeds, roast to 63°C inside; rest. About 1½ hours"],
    "d-pasta-bake": ["Per portion: brown the diced chicken and bacon with salt and pepper; add 1 garlic clove, 150 g passata, ½ tsp dried oregano, a pinch of chilli flakes and torn basil; simmer 10 min. Stir through the penne (cooked 2 min short), top with mozzarella and parmesan, bake at 200°C for 15 min. Portion", "Microwave until piping hot. 5 min"],
    "d-thai-green-curry": ["Per portion: fry 30 g green curry paste in a little oil for 1 min; add the sliced thighs and seal; pour in 150 ml light coconut milk and 50 ml water; simmer 10 min with the peppers and broccoli; season with 10 ml fish sauce, juice of ¼ lime, a pinch of sugar and a handful of Thai basil. Portion with rice", "Microwave until steaming. 5 min"],
    "d-tikka": ["Per portion marinade: 40 g Greek yoghurt, half the curry paste (about 12 g), 1 grated garlic clove, juice of ¼ lemon, ½ tsp salt. Marinate the cubed chicken 1 hour, then grill or air-fry at 220°C for 12 min. Sauce: soften 50 g onion with 1 garlic clove and 1 tsp grated ginger, fry the rest of the paste 1 min, add 120 g passata and 60 ml light coconut milk; simmer 10 min, blend smooth, add the chicken and ½ tsp garam masala. Portion with rice", "Microwave until steaming, coriander on top. 5 min"],
    "d-jalfrezi": ["Per portion: char 80 g chunky onion and 100 g peppers in a hot pan with half the oil; set aside. Fry the curry paste 1 min with 1 garlic clove, 1 tsp ginger and 1 sliced green chilli; brown the chicken; add 150 g chopped tomatoes and ½ tsp salt; simmer 12 min; return the veg with ½ tsp garam masala and a squeeze of lemon. Portion with rice", "Microwave until steaming, coriander on top. 5 min"],
    "d-katsu-curry": ["Per portion: flatten the breast, season with salt and pepper, dip in egg then panko; freeze raw on a lined tray, then bag. Katsu sauce: soften 50 g onion (plus a small carrot) with 1 garlic clove and 1 tsp ginger, add 20 g curry paste and 1 tsp honey, then 80 ml light coconut milk and 100 ml water; simmer 10 min and blend smooth. Portion the sauce and rice", "Air-fry the chicken from frozen at 200°C for 18 min; reheat the sauce and rice. 20 min hands-off"],
    "d-pad-thai": ["Per portion: season and pan-fry the chicken, slice. Sauce jar: 10 ml fish sauce, 15 ml soy, 10 g honey, juice of ⅓ lime, 1 tsp rice vinegar, ¼ tsp chilli flakes (or 1 tsp tamarind paste if you have it). Slice the onion and spring onion; crush the peanuts; keep the beansprouts in their bag", "Soak the noodles 5 min; wok the prawns 2 min, push aside and scramble the egg; add noodles, chicken and sauce, toss with beansprouts; peanuts and lime on top. 10 min, best fresh"],
    "d-thai-basil": ["Per portion: pound 2 garlic cloves with 1–2 bird's-eye chillies; fry in a hot wok 30 s; add the mince and brown hard; add the sliced peppers, 15 ml soy, 10 ml fish sauce, 5 g honey and 1 tsp oyster sauce if you have it; cook until sticky, then stir in a big handful of basil. Portion with rice", "Microwave until steaming; fry an egg in a hot pan until the edges crisp and put it on top. 5 min"],
    "d-peri-peri": ["Per portion: marinate the thighs in 30 g peri-peri sauce, juice of ¼ lemon, 1 grated garlic clove and ½ tsp smoked paprika, at least 1 hour. Grill or air-fry at 200°C for 18 min. Spicy rice: cook the rice with ½ tsp smoked paprika, ¼ tsp turmeric, ½ tsp garlic granules, the diced peppers and ½ stock cube. Garlic dip: 40 g yoghurt, ½ garlic clove, lemon, salt. Portion", "Microwave until steaming; corn on the side. 5 min"],
    "d-burrito-bowl": ["Per portion: rub the chicken with 1 tsp smoked paprika, ½ tsp cumin, ½ tsp chipotle or chilli powder, ½ tsp garlic granules, ¼ tsp oregano, salt and a squeeze of lime; grill and slice. Lime rice: stir the zest and juice of ¼ lime and chopped coriander through the rice. Beans and corn: warm with a pinch of cumin and salt. Salsa and yoghurt in pots", "Microwave the chicken, rice and beans until steaming, add the cold toppings and cheese. 4 min"],
    "d-chilli": ["Per portion: brown the mince hard; add 60 g onion, 60 g peppers and 1 garlic clove; stir in 1 tsp cumin, 1 tsp smoked paprika, ½ tsp chilli powder, ½ tsp dried oregano, ¼ tsp cinnamon and 1 tsp tomato purée; add 200 g chopped tomatoes, 100 ml beef stock and the beans; simmer 30 min. A square of dark chocolate at the end deepens it. Season, portion with rice", "Microwave until steaming, yoghurt on top. 5 min"],
    "d-massaman": ["Per portion: brown the beef in batches; fry 25 g massaman (or curry) paste 1 min; add 120 ml light coconut milk, 150 ml water, 50 g onion, 5 ml fish sauce, 1 tsp honey, a cinnamon stick and a bay leaf; simmer low 1½ hours. Add the potato chunks for the last 30 min. Portion with rice; peanuts in a bag", "Microwave until steaming, peanuts on top. 5 min"],

    "s-choc-mousse": ["Per pot: whisk 250 g quark, 30 g chocolate whey, 10 g cocoa and 10 g honey until thick and smooth; spoon into a jar, berries on top, grate over the dark chocolate. Makes up to Wednesday's; make the rest Wednesday night", "Grab a pot. Shake the other 30 g whey with water later. 1 min"],
    "s-brownie": ["Per 2 squares: blitz 30 g oats to flour; mix with 30 g chocolate whey, 12 g cocoa, ½ beaten egg, 15 g honey, a pinch of salt and baking powder and enough milk for a thick batter; fold in 10 g chopped dark chocolate. Bake the whole batch in a lined tin at 180°C for 15–18 min until just set. Cool, cut, bag (fridge 5 days or freeze)", "Two squares with Greek yoghurt and berries. 1 min"],
    "s-cheesecake": ["Per pot: crush a digestive into the jar; whisk 200 g quark, 30 g light cream cheese, 30 g vanilla whey, 10 g honey and a few drops of vanilla until smooth; spoon over; top with berries. Keeps 3 days; make the rest Wednesday night", "Grab a pot. Shake the other 30 g whey with water later. 0 min"],
    "s-bark": ["For the tray: mix the Greek yoghurt with the honey and a few drops of vanilla; spread 1 cm thick on a lined tray; scatter berries, granola and chopped dark chocolate; freeze 3 hours, snap into shards and bag", "Snap off a portion; shake the whey with water. 0 min"],
    "s-crumble": ["Crumble jar per portion: rub 30 g oats with 10 g peanut butter, 5 g honey and a pinch each of cinnamon and salt; bake at 180°C for 8–10 min until golden. Apple per portion: dice and cook with 5 g honey, ½ tsp cinnamon and a splash of water for 5 min; portion. Vanilla yoghurt: stir the whey into the Greek yoghurt; portion", "Layer apple, yoghurt and crumble. 2 min"],
    "s-pbj": ["Nothing to prep", "Spread 4 rice cakes with peanut butter and jam; shake the whey with cold milk. 3 min"],
    "snack": ["Nothing to prep", "Yoghurt, honey, berries and granola; shake the whey with water. 2 min"]
  };
  // Carbs cooked in one batch on Sunday, except for these recipes (cooked on the day or built into the dish).
  const BATCH_CARBS = ["sushi-rice", "jasmine-rice", "pasta", "rice-noodles", "potatoes"];
  const NO_BATCH = ["d-carbonara", "d-prawn-linguine", "d-pad-thai", "d-massaman", "d-roast-chicken", "d-roast-beef", "d-roast-pork", "d-lasagne", "d-pasta-bake", "d-fried-rice", "l-onigiri"];

  // Ingredients some people don't eat.
  const TAGS = { pork: ["bacon", "pork-loin"] };

  const RECIPES = {};
  R.forEach(function (r) { RECIPES[r.id] = r; });
  return { ING: ING, RECIPES: RECIPES, OPTIONS: OPTIONS, TAGS: TAGS, PREP: PREP, BATCH_CARBS: BATCH_CARBS, NO_BATCH: NO_BATCH };
})();
