// Gym-Bro recipe data. Nutrition per 100 g (approximate UK supermarket values).
// ING: id -> [shopping name, aisle, kcal, protein, carbs, fat, grams per item (optional), item word (optional)]
window.BB_DATA = (function () {
  const ING = {
    "sushi-rice": ["Sushi rice", "Carbs", 358, 6.5, 79, 0.6],
    "jasmine-rice": ["Jasmine or basmati rice", "Carbs", 356, 7, 79, 0.6],
    "pasta": ["Spaghetti, linguine or pappardelle", "Carbs", 355, 12.5, 71, 1.5],
    "penne": ["Penne or rigatoni", "Carbs", 355, 12.5, 71, 1.5],
    "lasagne-sheets": ["Lasagne sheets", "Carbs", 355, 12.5, 71, 1.5],
    "oats": ["Porridge oats", "Carbs", 375, 11, 60, 8],
    "sourdough": ["Sourdough", "Carbs", 250, 9, 48, 1.5, 45, "slices"],
    "brioche": ["Brioche buns", "Carbs", 330, 9, 50, 10, 60, "buns"],
    "wrap": ["Large wraps", "Carbs", 300, 8.5, 50, 7, 62, "wraps"],
    "sub-roll": ["Sub rolls", "Carbs", 270, 9, 50, 3, 90, "rolls"],
    "pizza-base": ["Thin pizza bases", "Carbs", 270, 8, 52, 3, 150, "bases"],
    "potatoes": ["Potatoes", "Carbs", 77, 2, 17, 0.1],
    "rice-noodles": ["Rice noodles (dry)", "Carbs", 360, 6, 82, 0.6],
    "digestives": ["Digestive biscuits", "Carbs", 480, 7, 62, 21, 15, "biscuits"],
    "rice-cakes": ["Rice cakes", "Carbs", 390, 8, 81, 3, 8, "rice cakes"],
    "panko": ["Panko breadcrumbs", "Carbs", 370, 12, 75, 3],
    "granola": ["Granola (lower sugar)", "Carbs", 430, 10, 60, 15],

    "chicken-breast": ["Chicken breast", "Protein", 106, 24, 0, 1.1],
    "chicken-thigh": ["Chicken thigh fillets, skinless", "Protein", 125, 20, 0, 4.9],
    "beef-mince": ["5% beef mince", "Protein", 125, 21, 0, 5],
    "lamb-mince": ["Lean lamb mince", "Protein", 150, 20, 0, 8],
    "beef-shin": ["Beef shin", "Protein", 130, 21, 0, 5],
    "steak": ["Sirloin steak, trimmed", "Protein", 150, 23, 0, 6],
    "turkey-rashers": ["Turkey rashers", "Protein", 105, 22, 0.5, 1.5],
    "turkey-pepperoni": ["Turkey pepperoni", "Protein", 180, 22, 2, 9],
    "salmon": ["Salmon fillets", "Protein", 200, 20, 0, 13],
    "tuna": ["Tuna in spring water, drained", "Protein", 110, 25, 0, 1],
    "prawns": ["King prawns, cooked", "Protein", 70, 16, 0, 0.9],
    "whey": ["Whey protein", "Protein", 390, 78, 7, 6],

    "eggs": ["Eggs", "Dairy and eggs", 140, 12.5, 0.5, 10, 50, "eggs"],
    "egg-whites": ["Liquid egg whites", "Dairy and eggs", 50, 11, 0.5, 0.2],
    "greek-yog": ["Greek yoghurt 0%", "Dairy and eggs", 57, 10, 4, 0.2],
    "milk": ["Semi-skimmed milk", "Dairy and eggs", 47, 3.5, 4.8, 1.7],
    "skimmed-milk": ["Skimmed milk", "Dairy and eggs", 35, 3.5, 5, 0.1],
    "mozzarella": ["Light mozzarella", "Dairy and eggs", 165, 20, 1, 9],
    "parmesan": ["Parmesan", "Dairy and eggs", 390, 33, 0, 28],
    "pecorino": ["Pecorino", "Dairy and eggs", 390, 28, 0, 30],
    "skyr": ["Skyr (plain)", "Dairy and eggs", 65, 11, 4, 0.2],
    "cream-cheese": ["Light cream cheese", "Dairy and eggs", 150, 7, 5, 11],
    "cheese-slice": ["Light cheese slices", "Dairy and eggs", 250, 20, 5, 15, 20, "slices"],

    "onion": ["Onions", "Fruit and veg", 40, 1.1, 9, 0.1],
    "garlic": ["Garlic", "Fruit and veg", 110, 6, 24, 0.5],
    "peppers": ["Peppers", "Fruit and veg", 30, 1, 6, 0.3],
    "lettuce": ["Lettuce", "Fruit and veg", 15, 1.2, 2, 0.2],
    "cucumber": ["Cucumber", "Fruit and veg", 15, 0.7, 3, 0.1],
    "tomato": ["Tomatoes", "Fruit and veg", 18, 0.9, 3.5, 0.2],
    "broccoli": ["Tenderstem or broccoli", "Fruit and veg", 34, 2.8, 7, 0.4],
    "greens": ["Pak choi or green veg", "Fruit and veg", 30, 3, 4, 0.4],
    "rocket": ["Rocket", "Fruit and veg", 25, 2.6, 3.6, 0.7],
    "edamame": ["Edamame beans (frozen)", "Fruit and veg", 125, 11, 7, 5],
    "peas": ["Frozen peas", "Fruit and veg", 70, 5.5, 10, 1.4],
    "berries": ["Berries (frozen is fine)", "Fruit and veg", 50, 1, 9, 0.3],
    "apple": ["Apples", "Fruit and veg", 52, 0.3, 14, 0.2, 150, "apples"],
    "beansprouts": ["Beansprouts", "Fruit and veg", 30, 3, 4, 0.2],
    "lime": ["Limes", "Fruit and veg", 30, 0.7, 10, 0.2, 65, "limes"],
    "mango": ["Mango", "Fruit and veg", 60, 0.8, 15, 0.4],
    "avocado": ["Avocado", "Fruit and veg", 160, 2, 9, 15],
    "corn": ["Sweetcorn (frozen or tin)", "Fruit and veg", 86, 3.3, 19, 1.4],
    "spinach": ["Spinach", "Fruit and veg", 23, 2.9, 3.6, 0.4],
    "kimchi": ["Kimchi", "Fruit and veg", 20, 1.5, 3, 0.5],
    "gherkins": ["Gherkins", "Fruit and veg", 20, 0.5, 4, 0.1],

    "passata": ["Passata", "Sauces and cupboard", 30, 1.4, 5, 0.2],
    "chopped-tom": ["Chopped tomatoes (tins)", "Sauces and cupboard", 22, 1.1, 3.5, 0.2],
    "olive-oil": ["Olive oil", "Sauces and cupboard", 900, 0, 0, 100],
    "sesame-oil": ["Sesame oil", "Sauces and cupboard", 900, 0, 0, 100],
    "soy": ["Light soy sauce", "Sauces and cupboard", 60, 8, 7, 0],
    "sushi-vinegar": ["Sushi seasoning or rice vinegar", "Sauces and cupboard", 150, 0, 35, 0],
    "teriyaki": ["Teriyaki sauce (reduced sugar)", "Sauces and cupboard", 120, 3, 25, 0],
    "gochujang": ["Gochujang", "Sauces and cupboard", 220, 4, 45, 2],
    "sriracha": ["Sriracha", "Sauces and cupboard", 100, 2, 20, 1],
    "light-mayo": ["Light mayo", "Sauces and cupboard", 260, 1, 8, 25],
    "ketchup": ["Ketchup", "Sauces and cupboard", 100, 1, 23, 0.1],
    "honey": ["Honey", "Sauces and cupboard", 304, 0.3, 82, 0],
    "peanut-butter": ["Peanut butter", "Sauces and cupboard", 600, 25, 12, 49],
    "tahini": ["Tahini", "Sauces and cupboard", 600, 17, 20, 53],
    "cornflour": ["Cornflour", "Sauces and cupboard", 350, 0.3, 88, 0.1],
    "furikake": ["Furikake or toasted sesame", "Sauces and cupboard", 400, 20, 40, 15],
    "salsa": ["Salsa (jar)", "Sauces and cupboard", 35, 1, 7, 0.2],
    "coconut-light": ["Light coconut milk", "Sauces and cupboard", 75, 0.7, 2.5, 7],
    "green-curry-paste": ["Thai green curry paste", "Sauces and cupboard", 110, 2, 12, 6],
    "curry-paste": ["Curry paste (tikka, jalfrezi or katsu)", "Sauces and cupboard", 150, 3, 15, 9],
    "coffee": ["Coffee (espresso or strong brew)", "Sauces and cupboard", 2, 0.1, 0, 0, null, null, "fixed"],
    "fish-sauce": ["Fish sauce", "Sauces and cupboard", 35, 5, 4, 0],
    "peanuts": ["Roasted peanuts", "Sauces and cupboard", 590, 26, 13, 49],
    "kidney-beans": ["Kidney beans (tin, drained)", "Sauces and cupboard", 100, 7, 15, 0.5],
    "peri-peri": ["Peri-peri sauce", "Sauces and cupboard", 80, 1, 15, 2],
    "cocoa": ["Cocoa powder", "Sauces and cupboard", 380, 20, 12, 21],
    "dark-choc": ["Dark chocolate (85%)", "Sauces and cupboard", 600, 10, 20, 50],
    "jam": ["Reduced-sugar jam", "Sauces and cupboard", 140, 0.5, 34, 0.1],
    "pesto": ["Green pesto", "Sauces and cupboard", 380, 4.5, 5, 38],
    "olives": ["Black olives, pitted", "Sauces and cupboard", 150, 1, 1, 15],
    "capers": ["Capers", "Sauces and cupboard", 25, 2, 2, 0.5]
  };

  // Recipes: grams per 1 serving. Dinners carry type: fresh (cook on the night), head (Sunday head start), sunday (batch, reheat).
  // Lunches carry late: freeze | split (freeze the cooked part, fresh part cut on the day) | no (Monday to Wednesday only).
  const R = [
    // ---- Breakfasts ----
    { id: "bf-eggs", slot: "breakfast", name: "Eggs and sourdough", time: "10 min",
      ing: [["eggs", 200], ["egg-whites", 150], ["sourdough", 90], ["salsa", 40]],
      method: ["Scramble the eggs and whites low and slow, season well.", "Toast the sourdough.", "Serve with salsa or hot sauce."] },
    { id: "bf-oats", slot: "breakfast", name: "Protein oats with berries", time: "5 min",
      ing: [["oats", 70], ["milk", 250], ["whey", 30], ["berries", 100], ["peanut-butter", 10], ["honey", 10]],
      method: ["Cook the oats in the milk for 3–4 minutes.", "Take off the heat and stir the whey in so it doesn't go grainy.", "Top with berries, peanut butter and honey."] },

    // ---- Snack ----
    { id: "snack", slot: "snack", name: "Yoghurt bowl and an apple", time: "2 min",
      ing: [["greek-yog", 300], ["honey", 15], ["berries", 80], ["granola", 40], ["apple", 150]],
      method: ["Greek yoghurt with honey, berries and granola.", "An apple on the side, or sliced in."] },
    { id: "s-choc-mousse", slot: "snack", name: "Chocolate protein mousse", time: "5 min", tag: "Sweet",
      ing: [["skyr", 250], ["whey", 30], ["cocoa", 10], ["honey", 10], ["berries", 60], ["dark-choc", 10]],
      method: ["Whisk skyr, whey, cocoa and honey until thick and smooth.", "Top with berries and grated dark chocolate. Chill 20 minutes if you can."] },
    { id: "s-brownie", slot: "snack", name: "Protein brownies with yoghurt", time: "Batch: 25 min", tag: "Sweet",
      ing: [["oats", 30], ["whey", 30], ["cocoa", 12], ["eggs", 25], ["honey", 15], ["dark-choc", 10], ["greek-yog", 200], ["berries", 60]],
      method: ["Blitz oats to flour; mix with whey, cocoa, egg, honey and a splash of milk to a thick batter.", "Fold in chopped dark chocolate; bake in a lined tin at 180°C for 15–18 minutes, still fudgy in the middle.", "Two squares per serving with Greek yoghurt and berries."] },
    { id: "s-cheesecake", slot: "snack", name: "Berry cheesecake pot", time: "5 min", tag: "Sweet",
      ing: [["skyr", 200], ["cream-cheese", 30], ["whey", 30], ["honey", 10], ["berries", 80], ["digestives", 15]],
      method: ["Crush a digestive into the bottom of a jar.", "Whisk skyr, cream cheese, whey and honey; spoon over.", "Top with berries."] },
    { id: "s-bark", slot: "snack", name: "Frozen yoghurt bark", time: "Batch: 10 min + freezing", tag: "Sweet",
      ing: [["greek-yog", 300], ["honey", 15], ["berries", 80], ["dark-choc", 15], ["granola", 20]],
      method: ["Mix yoghurt and honey; spread 1 cm thick on a lined tray.", "Scatter berries, granola and chopped dark chocolate; freeze 3 hours.", "Snap into shards."] },
    { id: "s-crumble", slot: "snack", name: "Apple crumble pot with vanilla yoghurt", time: "Batch: 20 min", tag: "Sweet",
      ing: [["apple", 150], ["honey", 10], ["oats", 30], ["peanut-butter", 10], ["greek-yog", 250], ["whey", 30]],
      method: ["Dice the apple and microwave with cinnamon and half the honey for 2 minutes.", "Crumble: oats, peanut butter and the rest of the honey, toasted in a dry pan or baked at 180°C for 8 minutes.", "Stir whey (vanilla if you have it) into the yoghurt; layer apple, yoghurt and crumble."] },
    { id: "s-pbj", slot: "snack", name: "PB and jam rice cakes with yoghurt", time: "3 min", tag: "Sweet",
      ing: [["rice-cakes", 32], ["peanut-butter", 20], ["jam", 20], ["greek-yog", 200], ["berries", 50]],
      method: ["Spread 4 rice cakes with peanut butter and jam.", "Greek yoghurt with berries on the side."] },

    // ---- Morning shakes (blender, made fresh before work). Built from the same fridge staples as the sweet treats. ----
    { id: "sh-choc-pb", slot: "shake", name: "Chocolate peanut butter shake", time: "3 min", tag: "Shake",
      ing: [["milk", 300], ["skyr", 150], ["cocoa", 10], ["peanut-butter", 20], ["honey", 10], ["dark-choc", 5]],
      method: ["Into the blender: milk, skyr, cocoa, peanut butter, honey and a big handful of ice.", "Blend 30–40 seconds until thick and frothy; grate the dark chocolate on top.", "Stir in your 5 g creatine. Optional: 1 scoop chocolate whey for +24 g protein."] },
    { id: "sh-strawberry", slot: "shake", name: "Berry cheesecake shake", time: "3 min", tag: "Shake",
      ing: [["greek-yog", 200], ["milk", 200], ["berries", 150], ["cream-cheese", 20], ["digestives", 15], ["honey", 10]],
      method: ["Into the blender: yoghurt, milk, frozen berries, cream cheese, honey, a few drops of vanilla and half the digestive.", "Blend until smooth; crumble the rest of the biscuit on top.", "Stir in your 5 g creatine. Optional: 1 scoop vanilla whey for +24 g protein."] },
    { id: "sh-mocha", slot: "shake", name: "Iced mocha shake", time: "4 min", tag: "Shake",
      ing: [["coffee", 60], ["milk", 250], ["skyr", 150], ["cocoa", 8], ["honey", 15], ["dark-choc", 5]],
      method: ["Make a double espresso or 60 ml strong coffee and let it cool for a minute.", "Into the blender with milk, skyr, cocoa, honey and a big handful of ice; blend until frothy; grate the chocolate on top.", "Doubles as your pre-gym coffee. Stir in your 5 g creatine."] },
    { id: "sh-lassi", slot: "shake", name: "Mango lassi", time: "3 min", tag: "Shake",
      ing: [["greek-yog", 250], ["milk", 150], ["mango", 150], ["honey", 10], ["granola", 10]],
      method: ["Into the blender: yoghurt, milk, frozen mango, honey, a pinch of ground cardamom and a pinch of salt.", "Blend until smooth and thick; a little granola on top for crunch.", "Stir in your 5 g creatine. Optional: 1 scoop vanilla whey."] },
    { id: "sh-berry-oat", slot: "shake", name: "PB and jam oat smoothie", time: "3 min", tag: "Shake",
      ing: [["milk", 250], ["skyr", 150], ["berries", 100], ["oats", 30], ["peanut-butter", 10], ["jam", 15]],
      method: ["Into the blender: oats first, then milk, skyr, frozen berries, peanut butter and jam.", "Blend 45 seconds so the oats go smooth.", "Stir in your 5 g creatine. Optional: 1 scoop vanilla whey."] },

    // ---- Lunch bowls ----
    { id: "l-salmon-poke", slot: "lunch", late: "split", name: "Salmon poke bowl", time: "15 min",
      ing: [["sushi-rice", 90], ["sushi-vinegar", 15], ["salmon", 140], ["edamame", 80], ["cucumber", 60], ["light-mayo", 10], ["sriracha", 10], ["soy", 10]],
      method: ["Season warm sushi rice with the vinegar.", "Cube the salmon; sear or roast at 200°C for 10 minutes if not sushi-grade.", "Build with edamame and cucumber; dress with soy and sriracha mayo."] },
    { id: "l-tuna-poke", slot: "lunch", late: "split", name: "Tuna poke bowl", time: "10 min",
      ing: [["sushi-rice", 100], ["sushi-vinegar", 15], ["tuna", 220], ["edamame", 60], ["cucumber", 60], ["light-mayo", 15], ["sriracha", 10], ["soy", 10]],
      method: ["Season warm sushi rice with the vinegar.", "Mix drained tuna with light mayo, sriracha and soy.", "Build with edamame and cucumber."] },
    { id: "l-teriyaki", slot: "lunch", late: "freeze", name: "Teriyaki chicken bowl", time: "20 min",
      ing: [["chicken-thigh", 200], ["teriyaki", 30], ["sushi-rice", 100], ["greens", 120], ["furikake", 5]],
      method: ["Grill or air-fry thighs at 200°C for 18 minutes, glazing with teriyaki for the last 5.", "Steam or wok the greens.", "Slice over rice; finish with furikake."] },
    { id: "l-bulgogi", slot: "lunch", late: "freeze", name: "Beef bulgogi bowl", time: "15 min",
      ing: [["beef-mince", 180], ["gochujang", 20], ["soy", 15], ["honey", 5], ["garlic", 5], ["sesame-oil", 5], ["sushi-rice", 100], ["kimchi", 60]],
      method: ["Brown the mince hard in a dry pan.", "Add garlic, gochujang, soy and honey; reduce until sticky.", "Finish with sesame oil; serve over rice with kimchi."] },
    { id: "l-prawn-egg", slot: "lunch", late: "no", name: "Prawn and egg rice bowl", time: "10 min",
      ing: [["prawns", 150], ["eggs", 100], ["sushi-rice", 100], ["edamame", 60], ["soy", 10], ["light-mayo", 10], ["furikake", 5]],
      method: ["Jammy eggs: 7 minutes, then iced water.", "Toss prawns with soy.", "Build over rice with edamame, a little mayo and furikake."] },
    { id: "l-shawarma", slot: "lunch", late: "split", name: "Chicken shawarma bowl", time: "25 min",
      ing: [["chicken-thigh", 200], ["olive-oil", 5], ["jasmine-rice", 90], ["greek-yog", 60], ["tahini", 8], ["gherkins", 30], ["cucumber", 60], ["tomato", 60]],
      method: ["Marinate thighs in shawarma spice, garlic, lemon and a little oil.", "Roast at 220°C for 20 minutes; rest and slice.", "Serve over rice with pickles, salad and tahini yoghurt."] },
    { id: "l-spicy-salmon", slot: "lunch", late: "split", name: "Spicy salmon rice bowl", time: "15 min",
      ing: [["salmon", 140], ["sushi-rice", 100], ["sushi-vinegar", 10], ["light-mayo", 15], ["sriracha", 15], ["cucumber", 60], ["edamame", 50], ["furikake", 5]],
      method: ["Roast salmon at 200°C for 12 minutes and flake.", "Mix with light mayo and sriracha.", "Serve over seasoned rice with cucumber, edamame and furikake."] },
    { id: "l-onigiri", slot: "lunch", late: "no", name: "Tuna-mayo onigiri and edamame", time: "15 min",
      ing: [["sushi-rice", 120], ["tuna", 150], ["light-mayo", 20], ["furikake", 5], ["edamame", 100]],
      method: ["Mix tuna with light mayo.", "Shape 3 rice triangles around the filling with wet, salted hands.", "Roll edges in furikake; edamame on the side."] },


    // ---- Gym-Gyal lunches ----
    { id: "l-thai-beef-salad", slot: "lunch", late: "no", name: "Thai beef salad", time: "15 min", tag: "Spicy",
      ing: [["steak", 160], ["rice-noodles", 60], ["lettuce", 80], ["cucumber", 80], ["tomato", 60], ["onion", 20], ["lime", 30], ["fish-sauce", 15], ["honey", 5], ["peanuts", 10]],
      method: ["Sear the steak hard, rest and slice thin.", "Dressing: lime juice, fish sauce, honey, chilli and garlic.", "Toss noodles, leaves, cucumber, tomato, red onion, mint and coriander with the beef; top with crushed peanuts."] },
    { id: "l-caesar", slot: "lunch", late: "split", name: "Chicken Caesar salad", time: "15 min",
      ing: [["chicken-breast", 180], ["lettuce", 120], ["sourdough", 45], ["parmesan", 15], ["greek-yog", 50], ["light-mayo", 10], ["garlic", 2]],
      method: ["Grill the chicken and slice.", "Cube the sourdough and bake at 200°C for 8 minutes for croutons.", "Dressing: yoghurt, light mayo, garlic, lemon, parmesan and a little anchovy if you like.", "Toss with cos lettuce; dressing on the day."] },
    { id: "l-satay-noodle", slot: "lunch", late: "no", name: "Satay chicken noodle salad", time: "20 min", tag: "Asian",
      ing: [["chicken-breast", 170], ["rice-noodles", 70], ["peanut-butter", 20], ["soy", 15], ["lime", 20], ["honey", 5], ["sriracha", 5], ["cucumber", 60], ["peppers", 60], ["beansprouts", 50]],
      method: ["Poach or grill the chicken; shred.", "Satay: peanut butter, soy, lime, honey, sriracha and hot water to loosen.", "Toss cold noodles, veg and chicken with the sauce."] },
    { id: "l-prawn-mango", slot: "lunch", late: "no", name: "Prawn, mango and avocado bowl", time: "10 min", tag: "Spicy",
      ing: [["prawns", 200], ["jasmine-rice", 50], ["mango", 100], ["avocado", 40], ["lettuce", 60], ["cucumber", 60], ["lime", 20], ["sriracha", 10], ["honey", 5]],
      method: ["Rice in the base.", "Prawns, mango, cucumber and leaves on top.", "Dress with lime, sriracha and honey; add avocado on the day so it doesn't brown."] },
    { id: "l-spicy-tuna-salad", slot: "lunch", late: "split", name: "Spicy tuna rice salad", time: "10 min", tag: "Spicy",
      ing: [["tuna", 200], ["sushi-rice", 60], ["sushi-vinegar", 10], ["light-mayo", 15], ["sriracha", 15], ["lettuce", 60], ["edamame", 80], ["cucumber", 60], ["furikake", 5]],
      method: ["Season the rice with sushi vinegar.", "Mix tuna with light mayo and sriracha.", "Build over leaves with edamame and cucumber; finish with furikake."] },

    // ---- Gym-Gyal dinners ----
    { id: "l-green-curry", slot: "lunch", late: "freeze", name: "Thai green chicken curry", time: "25 min", tag: "Thai",
      ing: [["chicken-thigh", 200], ["green-curry-paste", 30], ["coconut-light", 150], ["peppers", 60], ["broccoli", 60], ["fish-sauce", 10], ["lime", 15], ["jasmine-rice", 80]],
      method: ["Fry the paste for a minute; add sliced thighs and seal.", "Pour in the coconut milk and a splash of water; simmer 12 minutes with the veg.", "Season with fish sauce and lime; basil if you have it. Serve with rice."] },
    { id: "l-tikka", slot: "lunch", late: "freeze", name: "Chicken tikka masala (lighter)", time: "35 min", tag: "Curry",
      ing: [["chicken-breast", 200], ["greek-yog", 60], ["curry-paste", 25], ["onion", 50], ["garlic", 5], ["passata", 120], ["coconut-light", 60], ["jasmine-rice", 80]],
      method: ["Marinate the chicken in yoghurt and half the paste; grill or air-fry at 220°C for 12 minutes.", "Soften onion and garlic, fry the rest of the paste, add passata and coconut milk; simmer 10 minutes.", "Blend smooth if you like, add the chicken. Serve with basmati."] },
    { id: "l-jalfrezi", slot: "lunch", late: "freeze", name: "Chicken jalfrezi", time: "30 min", tag: "Curry",
      ing: [["chicken-breast", 200], ["curry-paste", 25], ["onion", 80], ["peppers", 100], ["chopped-tom", 150], ["olive-oil", 5], ["jasmine-rice", 80]],
      method: ["Fry chunky onion and peppers hot so they char a little; set aside.", "Fry the paste, brown the chicken, add tomatoes and green chilli.", "Simmer 12 minutes, return the veg. Serve with basmati."] },
    { id: "l-katsu-curry", slot: "lunch", late: "freeze", name: "Chicken katsu curry", time: "35 min", tag: "Fakeaway",
      ing: [["chicken-breast", 200], ["eggs", 25], ["panko", 30], ["olive-oil", 5], ["curry-paste", 20], ["onion", 50], ["coconut-light", 80], ["jasmine-rice", 80]],
      method: ["Flatten the breast, egg and panko; air-fry at 200°C for 12–14 minutes.", "Sauce: soften onion and carrot, add katsu paste and coconut milk with water; simmer and blend.", "Slice the chicken over rice and pour the sauce alongside."] },
    { id: "d-pad-thai", slot: "dinner", type: "fresh", name: "Prawn and chicken pad thai", time: "25 min", tag: "Thai",
      ing: [["rice-noodles", 80], ["prawns", 120], ["chicken-breast", 80], ["eggs", 50], ["beansprouts", 80], ["onion", 30], ["soy", 15], ["fish-sauce", 10], ["honey", 10], ["lime", 20], ["peanuts", 10]],
      method: ["Soak the noodles until just soft.", "Wok the chicken, then prawns; push aside and scramble the egg.", "Add noodles with fish sauce, soy, honey and lime; toss with beansprouts and spring onion. Peanuts and chilli flakes on top."] },
    { id: "d-thai-basil", slot: "dinner", type: "fresh", name: "Thai basil beef with a fried egg", time: "20 min", tag: "Thai",
      ing: [["beef-mince", 180], ["garlic", 10], ["peppers", 60], ["soy", 15], ["fish-sauce", 10], ["honey", 5], ["eggs", 50], ["jasmine-rice", 80]],
      method: ["Pound garlic and bird's-eye chilli; fry in a hot wok.", "Add the mince and brown hard; peppers in.", "Soy, fish sauce and honey; a big handful of basil. Over rice with a crispy fried egg."] },
    { id: "d-peri-peri", slot: "dinner", type: "head", name: "Peri-peri chicken and spicy rice", time: "25 min on the day", tag: "Fakeaway",
      ing: [["chicken-thigh", 220], ["peri-peri", 30], ["jasmine-rice", 70], ["peppers", 60], ["corn", 80], ["greek-yog", 40]],
      method: ["Marinate the thighs in peri-peri sauce; grill or air-fry at 200°C for 18 minutes.", "Spicy rice: cook rice with paprika, peppers and a stock cube.", "Corn on the side; yoghurt and garlic to dip."] },
    { id: "d-burrito-bowl", slot: "dinner", type: "head", name: "Chicken burrito bowl", time: "25 min on the day", tag: "Spicy",
      ing: [["chicken-breast", 180], ["jasmine-rice", 70], ["kidney-beans", 80], ["corn", 60], ["salsa", 60], ["lettuce", 40], ["greek-yog", 40], ["mozzarella", 20], ["lime", 15]],
      method: ["Season the chicken with chipotle or fajita spice; grill and slice.", "Lime and coriander rice.", "Build with beans, corn, salsa, lettuce, a little cheese and yoghurt as soured cream."] },
    { id: "d-chilli", slot: "dinner", type: "sunday", name: "Beef chilli con carne", time: "5 min on the day", tag: "Spicy",
      ing: [["beef-mince", 180], ["kidney-beans", 100], ["chopped-tom", 200], ["onion", 60], ["peppers", 60], ["garlic", 5], ["jasmine-rice", 70], ["greek-yog", 40]],
      method: ["Brown the mince; soften onion, peppers and garlic.", "Add cumin, smoked paprika and chilli; tomatoes and beans.", "Simmer 30 minutes. Rice and a spoon of yoghurt."] },
    { id: "l-massaman", slot: "lunch", late: "freeze", name: "Beef massaman curry", time: "Sunday batch", tag: "Thai",
      ing: [["beef-shin", 180], ["potatoes", 150], ["coconut-light", 120], ["curry-paste", 25], ["onion", 50], ["peanuts", 10], ["jasmine-rice", 50]],
      method: ["Brown the beef; fry the paste.", "Add coconut milk, water, onion and a little fish sauce and sugar; simmer low for 1½ hours.", "Add potato chunks for the last 30 minutes. Peanuts on top; a small portion of rice."] },

    // ---- Dinners ----
    { id: "d-ragu", slot: "dinner", type: "sunday", name: "Beef ragù pappardelle", time: "15 min on the day", tag: "Italian",
      ing: [["beef-shin", 180], ["onion", 60], ["garlic", 5], ["passata", 200], ["olive-oil", 5], ["pasta", 100], ["parmesan", 15]],
      method: ["Brown the shin in batches; soften onion and garlic.", "Add passata and a splash of stock; cook low for 3 hours (or 50 minutes in a pressure cooker).", "Shred and reduce. Toss with pappardelle, pasta water and parmesan."] },
    { id: "d-chicken-parm", slot: "dinner", type: "head", name: "Chicken parmigiana", time: "25 min on the day", tag: "Italian",
      ing: [["chicken-breast", 200], ["eggs", 25], ["panko", 30], ["olive-oil", 5], ["passata", 120], ["mozzarella", 50], ["parmesan", 10], ["pasta", 90]],
      method: ["Butterfly and flatten the breast; egg and panko.", "Air-fry at 200°C for 12 minutes, spritzed with the oil.", "Top with seasoned passata, mozzarella and parmesan; 3 more minutes.", "Serve with spaghetti tossed in the rest of the sauce."] },
    { id: "d-gyros", slot: "dinner", type: "head", name: "Chicken gyros wrap and fries", time: "25 min on the day",
      ing: [["chicken-thigh", 200], ["greek-yog", 60], ["wrap", 62], ["potatoes", 250], ["olive-oil", 5], ["onion", 30], ["lettuce", 30], ["tomato", 50]],
      method: ["Marinate thighs in oregano, garlic, lemon and paprika.", "Grill or air-fry at 200°C for 18 minutes; slice.", "Air-fry chips at 200°C for 20 minutes.", "Wrap with tzatziki-style yoghurt, salad and a few chips inside."] },

    { id: "d-smash", slot: "dinner", type: "fresh", name: "Smash burgers and fries", time: "30 min", tag: "Fakeaway",
      ing: [["beef-mince", 180], ["cheese-slice", 20], ["brioche", 60], ["light-mayo", 10], ["ketchup", 10], ["gherkins", 20], ["lettuce", 20], ["onion", 20], ["potatoes", 250], ["olive-oil", 5]],
      method: ["Air-fry chips at 200°C for 20 minutes.", "Two 90 g balls; smash hard on a ripping-hot dry pan, season, 2 minutes a side.", "Cheese on, stack in a toasted bun with burger sauce (mayo and ketchup), pickles and onion."] },
    { id: "d-crispy-burger", slot: "dinner", type: "head", name: "Crispy chicken burger and fries", time: "25 min on the day", tag: "Fakeaway",
      ing: [["chicken-breast", 200], ["eggs", 25], ["panko", 30], ["brioche", 60], ["light-mayo", 15], ["sriracha", 5], ["lettuce", 30], ["potatoes", 250], ["olive-oil", 5]],
      method: ["Butterfly the breast; egg and panko with paprika and garlic salt.", "Air-fry at 200°C for 12–14 minutes, spritzed with oil.", "Air-fry chips alongside.", "Bun with sriracha mayo and lettuce."] },
    { id: "d-philly", slot: "dinner", type: "fresh", name: "Philly cheesesteak and fries", time: "30 min", tag: "Fakeaway",
      ing: [["steak", 180], ["onion", 60], ["peppers", 60], ["cheese-slice", 40], ["sub-roll", 90], ["potatoes", 150], ["olive-oil", 5]],
      method: ["Freeze the steak 20 minutes, then slice paper-thin.", "Cook onions and peppers soft; flash-fry the steak.", "Lay cheese over in the pan to melt; pile into the toasted roll.", "Small portion of air-fryer chips."] },

    { id: "d-fried-rice", slot: "dinner", type: "fresh", name: "Chicken fried rice", time: "25 min", tag: "Fakeaway",
      ing: [["chicken-breast", 180], ["jasmine-rice", 90], ["eggs", 100], ["peas", 60], ["onion", 30], ["soy", 20], ["sesame-oil", 7]],
      method: ["Use day-old cooked rice.", "Wok the diced chicken hard; push aside and scramble the eggs.", "Add rice, peas and spring onion; soy and sesame oil to finish."] },
    { id: "d-beef-broccoli", slot: "dinner", type: "fresh", name: "Beef and broccoli stir-fry", time: "25 min", tag: "Fakeaway",
      ing: [["steak", 180], ["broccoli", 150], ["soy", 20], ["cornflour", 8], ["honey", 10], ["garlic", 5], ["jasmine-rice", 90], ["sesame-oil", 5]],
      method: ["Slice steak thin; toss in half the cornflour.", "Sear in batches; blanch the broccoli.", "Sauce: soy, honey, garlic, remaining cornflour and water; toss to gloss.", "Serve with rice."] },

    { id: "d-doner", slot: "dinner", type: "sunday", name: "Doner kebab and chips", time: "25 min on the day", tag: "Fakeaway",
      ing: [["lamb-mince", 200], ["wrap", 62], ["greek-yog", 50], ["garlic", 3], ["lettuce", 40], ["onion", 30], ["tomato", 50], ["sriracha", 10], ["potatoes", 200], ["olive-oil", 5]],
      method: ["Blitz mince with garlic, cumin, oregano and paprika to a paste; bake as a tight loaf at 180°C for 50 minutes.", "Chill, then slice paper-thin and crisp in a hot pan.", "Wrap with salad, garlic yoghurt and chilli; chips on the side."] },

    { id: "d-bigmac", slot: "dinner", type: "fresh", name: "Big Mac bowl", time: "30 min", tag: "Fakeaway",
      ing: [["beef-mince", 200], ["onion", 30], ["potatoes", 350], ["olive-oil", 5], ["lettuce", 60], ["gherkins", 30], ["cheese-slice", 20], ["light-mayo", 20], ["ketchup", 10]],
      method: ["Air-fry cubed potatoes at 200°C for 22 minutes.", "Brown the mince with onion; season well.", "Shredded lettuce, potatoes, mince, cheese, gherkins.", "Sauce: light mayo, ketchup, mustard, gherkin brine, paprika."] },
    { id: "d-pizza", slot: "dinner", type: "fresh", name: "Chicken and pepperoni pizza", time: "25 min", tag: "Fakeaway",
      ing: [["pizza-base", 150], ["passata", 60], ["mozzarella", 80], ["chicken-breast", 120], ["turkey-pepperoni", 40]],
      method: ["Oven at its hottest with a tray inside.", "Season passata with oregano and garlic; spread thin.", "Top with cooked sliced chicken, mozzarella and pepperoni.", "8–10 minutes until blistered."] },
    { id: "d-meatball-sub", slot: "dinner", type: "sunday", name: "Meatball marinara sub", time: "10 min on the day", tag: "Italian",
      ing: [["beef-mince", 180], ["panko", 15], ["eggs", 15], ["passata", 120], ["garlic", 3], ["mozzarella", 40], ["parmesan", 10], ["sub-roll", 90]],
      method: ["Mix mince, panko, egg, garlic, parmesan and herbs; roll 6 meatballs.", "Brown, then simmer in seasoned passata for 12 minutes.", "Into the toasted roll, mozzarella on top, grill to melt."] },
    { id: "d-quesadilla", slot: "dinner", type: "fresh", name: "Chicken quesadillas", time: "25 min",
      ing: [["chicken-breast", 180], ["wrap", 124], ["mozzarella", 50], ["peppers", 60], ["onion", 40], ["salsa", 50], ["greek-yog", 40]],
      method: ["Fajita-spice the sliced chicken; cook with onions and peppers.", "Fill two wraps with the mix and cheese; fold.", "Dry pan, 2 minutes a side until crisp. Salsa and yoghurt to dip."] },

    { id: "d-carbonara", slot: "dinner", type: "fresh", name: "High-protein carbonara", time: "20 min", tag: "Italian",
      ing: [["turkey-rashers", 120], ["eggs", 120], ["pecorino", 25], ["pasta", 110], ["chicken-breast", 100]],
      method: ["Crisp the diced turkey rashers in 1 tsp oil; pan-fry the sliced chicken alongside.", "Whisk 2 eggs, 1 yolk, pecorino and lots of black pepper.", "Off the heat, toss pasta with the meat, then the egg mix and pasta water until glossy."] },
    { id: "d-lasagne", slot: "dinner", type: "sunday", name: "Lean beef lasagne", time: "5 min on the day", tag: "Italian",
      ing: [["beef-mince", 180], ["onion", 50], ["garlic", 3], ["passata", 150], ["lasagne-sheets", 70], ["skimmed-milk", 150], ["cornflour", 12], ["parmesan", 15], ["mozzarella", 30]],
      method: ["Ragù: brown mince, onion and garlic; passata and herbs; simmer 30 minutes.", "White sauce: skimmed milk thickened with cornflour, nutmeg and half the parmesan.", "Layer, top with mozzarella and parmesan; bake at 190°C for 40 minutes. Rest before cutting."] },
    { id: "d-prawn-linguine", slot: "dinner", type: "fresh", name: "Prawn arrabbiata linguine", time: "25 min", tag: "Italian",
      ing: [["prawns", 200], ["chopped-tom", 200], ["garlic", 5], ["olive-oil", 10], ["pasta", 110], ["parmesan", 10]],
      method: ["Garlic and chilli in the oil; add tomatoes and reduce 10 minutes.", "Prawns in for 2 minutes.", "Toss with linguine and pasta water; parmesan and parsley."] },
    { id: "d-steak-chips", slot: "dinner", type: "fresh", name: "Steak, chips and rocket", time: "30 min",
      ing: [["steak", 250], ["potatoes", 350], ["olive-oil", 8], ["rocket", 40], ["parmesan", 10]],
      method: ["Air-fry thick chips at 200°C for 25 minutes.", "Steak at room temperature; hot pan, 2–3 minutes a side, rest 5.", "Rocket and parmesan on the side."] },

    { id: "d-pasta-bake", slot: "dinner", type: "sunday", name: "Chicken and turkey bacon pasta bake", time: "5 min on the day", tag: "Italian",
      ing: [["chicken-breast", 180], ["turkey-rashers", 60], ["penne", 100], ["passata", 150], ["garlic", 3], ["mozzarella", 50], ["parmesan", 10]],
      method: ["Cook penne 2 minutes short.", "Brown the chicken and turkey rashers; add garlic and passata.", "Mix with the pasta, top with mozzarella and parmesan; bake at 200°C for 15 minutes."] },
    { id: "d-pesto-chicken", slot: "dinner", type: "fresh", name: "Chicken pesto pasta", time: "20 min", tag: "Italian",
      ing: [["chicken-breast", 180], ["pasta", 100], ["pesto", 25], ["tomato", 100], ["rocket", 30], ["parmesan", 10]],
      method: ["Pasta on. Season the sliced chicken and pan-fry until golden.", "Add the halved tomatoes for 2 minutes.", "Toss with the pasta, pesto and a splash of pasta water; rocket and parmesan on top."] },
    { id: "d-rigatoni", slot: "dinner", type: "fresh", name: "Creamy tomato chicken rigatoni", time: "25 min", tag: "Italian",
      ing: [["chicken-breast", 180], ["penne", 100], ["passata", 150], ["cream-cheese", 40], ["garlic", 5], ["spinach", 60], ["parmesan", 10]],
      method: ["Rigatoni on. Brown the diced chicken; add garlic and chilli.", "Add passata, simmer 8 minutes, stir in the cream cheese.", "Wilt the spinach in, toss with the pasta and pasta water; parmesan."] },
    { id: "d-puttanesca", slot: "dinner", type: "fresh", name: "Tuna puttanesca", time: "20 min", tag: "Italian",
      ing: [["tuna", 150], ["pasta", 110], ["chopped-tom", 200], ["olives", 25], ["capers", 10], ["garlic", 5], ["olive-oil", 8], ["parmesan", 10]],
      method: ["Spaghetti on. Warm garlic and chilli in the oil.", "Add tomatoes, olives and capers; reduce 10 minutes.", "Fold in the tuna, toss with the pasta and pasta water; parsley and parmesan."] },
    { id: "d-meatballs", slot: "dinner", type: "sunday", name: "Spaghetti and meatballs", time: "10 min on the day", tag: "Italian",
      ing: [["beef-mince", 180], ["panko", 15], ["eggs", 15], ["passata", 150], ["garlic", 3], ["pasta", 90], ["parmesan", 15]],
      method: ["Mix mince, panko, egg, garlic, parmesan and herbs; roll 6 meatballs.", "Brown, then simmer in seasoned passata for 12 minutes.", "Toss with spaghetti; parmesan on top."] },
    { id: "d-crispy-chilli", slot: "dinner", type: "head", name: "Crispy chilli chicken", time: "25 min on the day", tag: "Fakeaway",
      ing: [["chicken-breast", 200], ["cornflour", 20], ["olive-oil", 8], ["peppers", 80], ["onion", 50], ["ketchup", 20], ["honey", 10], ["sriracha", 10], ["soy", 10], ["jasmine-rice", 90]],
      method: ["Rice on. Toss the seasoned diced chicken in cornflour; air-fry at 200°C for 12 minutes, spritzed with the oil.", "Wok the onion and peppers hot for 3 minutes; add the sauce and bubble until glossy.", "Toss the chicken through. Serve with rice."] },
    { id: "l-pesto-pasta", slot: "lunch", late: "no", name: "Pesto chicken pasta salad", time: "20 min",
      ing: [["chicken-breast", 150], ["penne", 80], ["pesto", 20], ["tomato", 80], ["rocket", 30], ["mozzarella", 30]],
      method: ["Roast the seasoned chicken at 200°C for 18 minutes; dice.", "Cook the penne, cool, toss with pesto, lemon and halved tomatoes.", "Box with the chicken and torn mozzarella; rocket on the day."] },
    { id: "l-tuna-pasta", slot: "lunch", late: "no", name: "Lemon tuna pasta salad", time: "15 min",
      ing: [["tuna", 140], ["penne", 80], ["light-mayo", 15], ["greek-yog", 40], ["cucumber", 60], ["corn", 50]],
      method: ["Cook the penne and cool under cold water.", "Mix mayo, yoghurt, lemon zest and juice, salt and pepper.", "Fold through the pasta with the tuna, diced cucumber and corn."] },
    { id: "l-ragu-box", slot: "lunch", late: "freeze", name: "Beef ragù pasta box", time: "Sunday batch",
      ing: [["beef-shin", 150], ["onion", 50], ["garlic", 5], ["passata", 170], ["olive-oil", 5], ["pasta", 85], ["parmesan", 10]],
      method: ["Make the ragù as for the pappardelle (the same pot does both).", "Cook the pasta 2 minutes short and toss through the ragù.", "Box, cool and freeze; parmesan on after reheating."] },
    { id: "l-arrabbiata", slot: "lunch", late: "freeze", name: "Spicy arrabbiata chicken pasta", time: "25 min",
      ing: [["chicken-breast", 160], ["penne", 85], ["chopped-tom", 200], ["garlic", 5], ["olive-oil", 8], ["parmesan", 10]],
      method: ["Roast the chicken with oregano and chilli at 200°C for 18 minutes; slice.", "Arrabbiata: garlic and chilli flakes in the oil, tomatoes, reduce 15 minutes.", "Toss the penne through the sauce, chicken on top."] }
  ];

  // Options per weekday (0 = Sunday), per app. First option is the default.
  // Dinners are shared by both apps. Thursday to Saturday lunches must freeze or split (late !== "no").
  const DINNERS = {
    1: ["d-ragu", "d-chicken-parm", "d-pesto-chicken", "d-gyros"],
    2: ["d-smash", "d-crispy-burger", "d-philly", "d-rigatoni"],
    3: ["d-fried-rice", "d-beef-broccoli", "d-crispy-chilli", "d-pad-thai"],
    4: ["d-doner", "d-peri-peri", "d-burrito-bowl", "d-thai-basil"],
    5: ["d-bigmac", "d-pizza", "d-meatball-sub", "d-quesadilla"],
    6: ["d-carbonara", "d-lasagne", "d-prawn-linguine", "d-steak-chips"],
    0: ["d-meatballs", "d-pasta-bake", "d-chilli", "d-puttanesca"]
  };
  const BREAKFASTS = {
    1: ["bf-eggs", "bf-oats"], 2: ["bf-oats", "bf-eggs"], 3: ["bf-eggs", "bf-oats"], 4: ["bf-oats", "bf-eggs"],
    5: ["bf-eggs", "bf-oats"], 6: ["bf-oats", "bf-eggs"], 0: ["bf-eggs", "bf-oats"]
  };
  const OPTIONS = {
    bro: {
      dinner: DINNERS, breakfast: BREAKFASTS,
      lunch: {
        1: ["l-salmon-poke", "l-pesto-pasta", "l-tuna-poke", "l-teriyaki"],
        2: ["l-teriyaki", "l-tuna-pasta", "l-shawarma", "l-bulgogi"],
        3: ["l-bulgogi", "l-pesto-pasta", "l-prawn-egg", "l-teriyaki"],
        4: ["l-ragu-box", "l-spicy-salmon", "l-shawarma", "l-arrabbiata"],
        5: ["l-shawarma", "l-bulgogi", "l-ragu-box", "l-tuna-poke"],
        6: ["l-spicy-salmon", "l-salmon-poke", "l-arrabbiata", "l-teriyaki"],
        0: ["l-onigiri", "l-tuna-poke", "l-tuna-pasta"]
      }
    },
    gyal: {
      dinner: DINNERS, breakfast: BREAKFASTS,
      lunch: {
        1: ["l-thai-beef-salad", "l-salmon-poke", "l-pesto-pasta", "l-teriyaki"],
        2: ["l-caesar", "l-tuna-pasta", "l-shawarma", "l-bulgogi"],
        3: ["l-satay-noodle", "l-prawn-mango", "l-prawn-egg", "l-pesto-pasta"],
        4: ["l-green-curry", "l-arrabbiata", "l-spicy-salmon", "l-shawarma"],
        5: ["l-tikka", "l-jalfrezi", "l-spicy-tuna-salad", "l-bulgogi"],
        6: ["l-caesar", "l-massaman", "l-katsu-curry", "l-salmon-poke"],
        0: ["l-satay-noodle", "l-onigiri", "l-spicy-tuna-salad"]
      }
    }
  };
  // Snack options are the same for both apps; the first is the day's default.
  const SHAKES = { 1: "sh-choc-pb", 2: "sh-mocha", 3: "sh-strawberry", 4: "sh-berry-oat", 5: "sh-lassi", 6: "sh-choc-pb", 0: "sh-strawberry" };
  const ALL_SHAKES = ["sh-choc-pb", "sh-mocha", "sh-strawberry", "sh-berry-oat", "sh-lassi"];
  ["bro", "gyal"].forEach(function (k) { OPTIONS[k].shake = {}; for (let d = 0; d < 7; d++) { OPTIONS[k].shake[d] = [SHAKES[d]].concat(ALL_SHAKES.filter(function (x) { return x !== SHAKES[d]; })); } });
  const SNACKS = { 1: "s-choc-mousse", 2: "s-brownie", 3: "s-cheesecake", 4: "s-bark", 5: "s-crumble", 6: "s-pbj", 0: "snack" };
  const ALL_SNACKS = ["s-choc-mousse", "s-brownie", "s-cheesecake", "s-bark", "s-crumble", "s-pbj", "snack"];
  ["bro", "gyal"].forEach(function (k) { OPTIONS[k].snack = {}; for (let d = 0; d < 7; d++) { OPTIONS[k].snack[d] = [SNACKS[d]].concat(ALL_SNACKS.filter(function (x) { return x !== SNACKS[d]; })); } });

  // Batch prep: [Sunday job, what's left on the day]. Mon–Sat meals are cooked on Sunday where it works.
  const PREP = {
    "l-salmon-poke": ["Per portion: season the salmon with ½ tsp salt and 1 tsp soy, roast at 200°C for 12 min, then flake. Slice the cucumber into half-moons and toss with a pinch of salt and 1 tsp rice vinegar. Sauce pot: 10 g light mayo, 10 g sriracha, 10 ml soy, ½ tsp sesame oil. Box with the edamame", "Microwave the rice until steaming, top with the cold salmon and veg, add sauce. 3 min"],
    "l-tuna-poke": ["Per portion: quick-pickle the cucumber (1 tsp rice vinegar, pinch of salt and sugar). Box rice with edamame and cucumber. Tuna pot: drained tuna mixed with 15 g light mayo, 10 g sriracha, 10 ml soy and a squeeze of lime. From Thursday, mix the tuna on the day", "Microwave the rice until steaming, top with tuna and veg. 3 min"],
    "l-teriyaki": ["Per portion: marinate the thighs 30 min in 15 ml teriyaki, 5 ml soy, 1 grated garlic clove and 1 tsp grated ginger. Air-fry at 200°C for 18 min, brushing with another 15 ml teriyaki for the last 5. Slice. Steam the greens 3 min, toss in a few drops of sesame oil and a pinch of salt. Box with rice, furikake in a twist of foil", "Microwave until steaming throughout. 3 min"],
    "l-bulgogi": ["For all portions: brown the mince hard in a dry pan in batches. Per portion add 1 grated garlic clove, 1 tsp grated ginger, 20 g gochujang, 15 ml soy and 5 g honey; cook down until sticky, finish with 5 ml sesame oil and sliced spring onion. Box with rice; kimchi in a separate pot", "Microwave until steaming, kimchi on top. 3 min"],
    "l-prawn-egg": ["Boil the eggs 7 min, into iced water, peel. Per portion: toss the prawns in 10 ml soy, ½ tsp sesame oil and a pinch of chilli flakes; mix 10 g light mayo with 1 tsp sriracha in a pot. Box rice with edamame; eggs and prawns in a separate tub", "Microwave the rice until steaming, add the cold prawns, halved eggs, mayo and furikake. 2 min"],
    "l-shawarma": ["Per portion marinade: 30 g Greek yoghurt, 1 tsp each cumin and smoked paprika, ½ tsp each turmeric, cinnamon and garlic granules, juice of ¼ lemon, ½ tsp salt, 5 ml olive oil. Marinate the thighs 1 hour (or overnight), roast at 220°C for 20 min, rest and slice. Tahini sauce: 30 g yoghurt, 8 g tahini, squeeze of lemon, pinch of salt. Chop cucumber and tomato with parsley; pickles in the salad pot", "Microwave chicken and rice until steaming, add the cold salad and sauce. 3 min"],
    "l-spicy-salmon": ["Per portion: season the salmon with salt and pepper, roast at 200°C for 12 min, flake and mix with 15 g light mayo, 15 g sriracha and 5 ml soy. Season the rice with the sushi vinegar. Box with sliced cucumber and edamame, furikake on top", "Microwave the rice until steaming, top with the salmon mix. 2 min"],
    "l-onigiri": ["Sunday lunch: make fresh. Season the rice with sushi vinegar; fill with tuna mixed with light mayo and a little soy; shape with wet, salted hands; roll the edges in furikake", "Eat cold. 0 min"],
    "l-thai-beef-salad": ["Per portion: rub the steak with ½ tsp salt and pepper, sear 2 min a side in a ripping-hot pan, rest 5 min, slice thin. Soak the noodles in boiling water 5 min, rinse cold, toss in a few drops of oil. Dressing jar per portion: juice of ½ lime, 15 ml fish sauce, 5 g honey, ½ chopped red chilli, ½ grated garlic clove. Slice the cucumber, tomato and red onion; pick the mint and coriander. Peanuts crushed in a separate bag", "Toss everything with the dressing, peanuts on top. 2 min"],
    "l-caesar": ["Per portion: rub the chicken with 5 ml olive oil, ½ tsp garlic granules, ½ tsp dried oregano, salt, pepper and lemon zest; grill or air-fry at 200°C for 15–18 min to 74°C inside; rest and slice. Croutons: cube the sourdough, spray with oil, pinch of salt and garlic granules, bake at 200°C for 8 min. Dressing jar: 50 g Greek yoghurt, 10 g light mayo, 1 grated garlic clove, 1 tsp Dijon, juice of ¼ lemon, a few drops of Worcestershire, 1 tbsp grated parmesan, black pepper. Wash, dry and chop the cos", "Toss lettuce, chicken and dressing, croutons and the rest of the parmesan on top. 2 min"],
    "l-satay-noodle": ["Per portion: poach the chicken in simmering water with a slice of ginger for 12 min, cool and shred. Noodles: soak 5 min, rinse cold, toss in a little oil. Satay sauce jar per portion: 20 g peanut butter, 15 ml soy, juice of ⅓ lime, 5 g honey, 5 g sriracha, ½ grated garlic clove, loosened with 2–3 tbsp hot water. Julienne the cucumber and peppers; keep the beansprouts separate", "Toss everything with the sauce, cold. Coriander if you have it. 2 min"],
    "l-prawn-mango": ["Dice the mango and cucumber and shred the lettuce. Dressing jar per portion: juice of ⅓ lime, 10 g sriracha, 5 g honey, pinch of salt, chopped coriander. Box the rice; prawns in a separate tub. Keep the avocado whole until the day", "Microwave the rice until steaming, add prawns, mango, avocado and dressing. 3 min"],
    "l-spicy-tuna-salad": ["Season the rice with the sushi vinegar and box with edamame, sliced cucumber and shredded lettuce. Sauce pot per portion: 15 g light mayo, 15 g sriracha, a squeeze of lime", "Mix the tuna with the sauce, build over the leaves and warm rice, furikake on top. 3 min"],

    "d-ragu": ["For all portions: season the shin with salt and pepper and brown hard in batches. Per portion soften 60 g diced onion, plus carrot and celery if you have them, with 1 garlic clove and a sprig of rosemary; add 1 tsp tomato purée, 200 g passata, 100 ml beef stock, a bay leaf and ½ tsp dried oregano. Cover and cook low (150°C oven) for 3 hours, or 50 min in a pressure cooker. Shred, reduce until thick, season, portion", "Reheat the ragù until piping hot, toss with the pasta, a splash of water and parmesan. 6 min"],
    "d-doner": ["Per portion: blitz the mince to a smooth paste with ½ tsp salt, ½ tsp cumin, ½ tsp ground coriander, ½ tsp dried oregano, ½ tsp smoked paprika, ¼ tsp chilli flakes, ½ tsp garlic granules and ½ tsp onion powder. Pack into a tight loaf, wrap in foil and bake at 180°C for 50 min, then 10 min uncovered. Chill, slice paper-thin, portion. Garlic sauce: 50 g Greek yoghurt, 1 grated garlic clove, squeeze of lemon, pinch of salt and dried mint. Slice the onion and tomato", "Crisp the doner slices in a hot dry pan 3 min; air-fry the chips; wrap with salad, garlic sauce and chilli sauce. 15 min"],
    "d-meatball-sub": ["Per portion: mix the mince with 15 g panko, 15 g beaten egg, 1 grated garlic clove, 10 g grated parmesan, ½ tsp dried oregano, ½ tsp salt and black pepper; roll 6 meatballs and brown. Simmer 12 min in 120 g passata with ½ garlic clove, ½ tsp oregano, a pinch of chilli flakes and torn basil. Portion", "Reheat until piping hot, fill the toasted roll, mozzarella on top, grill to melt. 8 min"],
    "d-lasagne": ["Ragù per portion: brown the mince with 50 g onion and 1 garlic clove, add 150 g passata, 1 tsp tomato purée, ½ tsp oregano, a bay leaf, salt and pepper; simmer 30 min. White sauce per portion: 150 ml skimmed milk thickened with 12 g cornflour, a pinch of nutmeg, salt, pepper and half the parmesan. Layer ragù, sheets and white sauce; top with mozzarella and the rest of the parmesan; bake at 190°C for 40 min. Rest 15 min, cut, portion", "Microwave until piping hot. 5 min"],
    "d-pasta-bake": ["Per portion: brown the diced chicken and turkey rashers with salt and pepper; add 1 garlic clove, 150 g passata, ½ tsp dried oregano, a pinch of chilli flakes and torn basil; simmer 10 min. Stir through the penne (cooked 2 min short), top with mozzarella and parmesan, bake at 200°C for 15 min. Portion", "Microwave until piping hot. 5 min"],
    "l-green-curry": ["Per portion: fry 30 g green curry paste in a little oil for 1 min; add the sliced thighs and seal; pour in 150 ml light coconut milk and 50 ml water; simmer 10 min with the peppers and broccoli; season with 10 ml fish sauce, juice of ¼ lime, a pinch of sugar and a handful of Thai basil. Portion with rice", "Microwave until steaming. 5 min"],
    "l-tikka": ["Per portion marinade: 40 g Greek yoghurt, half the curry paste (about 12 g), 1 grated garlic clove, juice of ¼ lemon, ½ tsp salt. Marinate the cubed chicken 1 hour, then grill or air-fry at 220°C for 12 min. Sauce: soften 50 g onion with 1 garlic clove and 1 tsp grated ginger, fry the rest of the paste 1 min, add 120 g passata and 60 ml light coconut milk; simmer 10 min, blend smooth, add the chicken and ½ tsp garam masala. Portion with rice", "Microwave until steaming, coriander on top. 5 min"],
    "l-jalfrezi": ["Per portion: char 80 g chunky onion and 100 g peppers in a hot pan with half the oil; set aside. Fry the curry paste 1 min with 1 garlic clove, 1 tsp ginger and 1 sliced green chilli; brown the chicken; add 150 g chopped tomatoes and ½ tsp salt; simmer 12 min; return the veg with ½ tsp garam masala and a squeeze of lemon. Portion with rice", "Microwave until steaming, coriander on top. 5 min"],
    "l-katsu-curry": ["Per portion: flatten the breast, season with salt and pepper, dip in egg then panko; freeze raw on a lined tray, then bag. Katsu sauce: soften 50 g onion (plus a small carrot) with 1 garlic clove and 1 tsp ginger, add 20 g curry paste and 1 tsp honey, then 80 ml light coconut milk and 100 ml water; simmer 10 min and blend smooth. Portion the sauce and rice", "Air-fry the chicken from frozen at 200°C for 18 min; reheat the sauce and rice. 20 min hands-off"],
    "d-chilli": ["Per portion: brown the mince hard; add 60 g onion, 60 g peppers and 1 garlic clove; stir in 1 tsp cumin, 1 tsp smoked paprika, ½ tsp chilli powder, ½ tsp dried oregano, ¼ tsp cinnamon and 1 tsp tomato purée; add 200 g chopped tomatoes, 100 ml beef stock and the beans; simmer 30 min. A square of dark chocolate at the end deepens it. Season, portion with rice", "Microwave until steaming, yoghurt on top. 5 min"],
    "l-massaman": ["Per portion: brown the beef in batches; fry 25 g massaman (or curry) paste 1 min; add 120 ml light coconut milk, 150 ml water, 50 g onion, 5 ml fish sauce, 1 tsp honey, a cinnamon stick and a bay leaf; simmer low 1½ hours. Add the potato chunks for the last 30 min. Portion with rice; peanuts in a bag", "Microwave until steaming, peanuts on top. 5 min"],

    "s-brownie": ["Per 2 squares: blitz 30 g oats to flour; mix with 30 g chocolate whey, 12 g cocoa, ½ beaten egg, 15 g honey, a pinch of salt and baking powder and enough milk for a thick batter; fold in 10 g chopped dark chocolate. Bake the whole batch in a lined tin at 180°C for 15–18 min until just set. Cool, cut, bag (fridge 5 days or freeze)", "Two squares with Greek yoghurt and berries. 1 min"],
    "s-bark": ["For the tray: mix the Greek yoghurt with the honey and a few drops of vanilla; spread 1 cm thick on a lined tray; scatter berries, granola and chopped dark chocolate; freeze 3 hours, snap into shards and bag", "Snap off a portion. 0 min"],
    "s-crumble": ["Crumble jar per portion: rub 30 g oats with 10 g peanut butter, 5 g honey and a pinch each of cinnamon and salt; bake at 180°C for 8–10 min until golden. Apple per portion: dice and cook with 5 g honey, ½ tsp cinnamon and a splash of water for 5 min; portion. Vanilla yoghurt: stir the whey into the Greek yoghurt; portion", "Layer apple, yoghurt and crumble. 2 min"],
    "sh-choc-pb": ["Made fresh each morning", "Blend with ice 30–40 s. 3 min"],
    "sh-strawberry": ["Made fresh each morning", "Blend with ice until smooth. 3 min"],
    "sh-mocha": ["Made fresh each morning", "Brew the coffee, blend with ice until frothy. 4 min"],
    "sh-lassi": ["Made fresh each morning", "Blend until smooth and thick. 3 min"],
    "sh-berry-oat": ["Made fresh each morning", "Blend 45 s so the oats go smooth. 3 min"],
    "s-pbj": ["Nothing to prep", "Spread 4 rice cakes with peanut butter and jam; yoghurt and berries on the side. 3 min"],
    "snack": ["Nothing to prep", "Yoghurt, honey, berries and granola; an apple. 2 min"],
    "d-carbonara": ["", "Spaghetti on. Dice the turkey rashers and crisp in 1 tsp oil; season the sliced chicken with salt and pepper and pan-fry alongside. Whisk 2 eggs, 1 yolk, the grated pecorino and plenty of black pepper. Off the heat, toss the pasta with the meat, then the egg mix and a splash of pasta water until glossy"],
    "d-prawn-linguine": ["", "Linguine on. Warm 10 ml olive oil with 2 sliced garlic cloves and ½ tsp chilli flakes, add 200 g chopped tomatoes with a pinch of sugar and salt, reduce 12 min. Prawns in for 2 min, toss with the pasta and a splash of pasta water; parsley and parmesan"],
    "d-pesto-chicken": ["", "Spaghetti or linguine on. Slice the chicken, season with ½ tsp salt, black pepper and ½ tsp garlic granules, pan-fry in 1 tsp oil until golden, 6–7 min. Add the halved tomatoes for 2 min. Toss with the pasta, 25 g pesto, juice of ¼ lemon and a splash of pasta water; rocket and parmesan on top"],
    "d-rigatoni": ["", "Rigatoni on. Dice the chicken, season with ½ tsp salt, ½ tsp dried oregano and black pepper, brown in 1 tsp oil. Add 1 grated garlic clove and ¼ tsp chilli flakes for 30 s, then 150 g passata; simmer 8 min. Stir in 40 g light cream cheese until smooth, wilt in the spinach, toss with the pasta and a splash of pasta water; parmesan"],
    "d-puttanesca": ["", "Spaghetti on. Warm 8 ml olive oil with 2 sliced garlic cloves and ½ tsp chilli flakes; add 200 g chopped tomatoes, 25 g halved olives, 10 g capers and ½ tsp dried oregano; reduce 10 min. Fold in the drained tuna, toss with the pasta and a splash of pasta water; parsley and parmesan. Taste before salting"],
    "d-fried-rice": ["", "Cook the rice first, spread it on a tray and let it steam dry (day-old rice is better still). Wok the diced chicken hard with ½ tsp salt and ¼ tsp white pepper, push aside and scramble 2 eggs; add the rice, 60 g peas and the chopped onion; season with 20 ml soy and 7 ml sesame oil"],
    "d-beef-broccoli": ["", "Rice on. Slice the steak thin and toss in 4 g cornflour, ½ tsp soy and a pinch of salt; sear in batches in a very hot wok. Blanch the broccoli 2 min. Sauce: 20 ml soy, 10 g honey, 1 grated garlic clove, 1 tsp grated ginger, 4 g cornflour and 60 ml water, simmered until glossy; toss everything together with 5 ml sesame oil"],
    "d-thai-basil": ["", "Rice on. Pound 2 garlic cloves with 1–2 bird's-eye chillies; fry in a hot wok 30 s; add the mince and brown hard; add the sliced peppers, 15 ml soy, 10 ml fish sauce, 5 g honey and 1 tsp oyster sauce if you have it; cook until sticky, then stir in a big handful of basil. Fry an egg until the edges crisp and put it on top"],
    "d-pad-thai": ["", "Soak the noodles 5 min in boiling water. Sauce: 10 ml fish sauce, 15 ml soy, 10 g honey, juice of ⅓ lime, 1 tsp rice vinegar, ¼ tsp chilli flakes. Season and pan-fry the sliced chicken; add the prawns for 2 min, push aside and scramble the egg; add the sliced onion, noodles and sauce, toss with the beansprouts; crushed peanuts and lime on top"],
    "d-smash": ["", "Cut the chips, toss in 5 ml oil and salt, air-fry at 200°C for 20 min. Burger sauce: 10 g light mayo, 10 g ketchup, 1 tsp American mustard, 1 tsp chopped gherkin plus a splash of its brine, pinch of smoked paprika. Slice the onion very thin. Roll 2 × 90 g balls; smash each on a ripping-hot dry pan, season with salt and pepper, 2 min, flip, cheese on, 1 min. Build in a toasted bun with lettuce and gherkins"],
    "d-quesadilla": ["", "Slice the chicken and toss in 1 tsp smoked paprika, ½ tsp cumin, ½ tsp garlic granules, ½ tsp chilli powder, ¼ tsp oregano, ½ tsp salt and a squeeze of lime; cook hot with the sliced peppers and onion, 8 min. Fill the wraps with the filling and cheese; dry-fry 2 min a side. Salsa and yoghurt to dip"],
    "d-steak-chips": ["", "Take the steak out of the fridge 30 min ahead. Cut the chips, toss in the oil and salt, air-fry at 200°C for 20 min. Season the steak with salt and pepper, sear 2–3 min a side, with a knob of butter, garlic and thyme for the last minute; rest 5 min. Rocket and shaved parmesan alongside"],
    "d-bigmac": ["", "Dice the potatoes, toss in 5 ml oil and salt, air-fry at 200°C for 20 min. Big Mac sauce: 20 g light mayo, 10 g ketchup, 1 tsp American mustard, 1 tsp finely chopped gherkin plus a splash of brine, ¼ tsp smoked paprika, ¼ tsp onion powder. Brown the mince hard with 30 g finely diced onion, ½ tsp salt, ½ tsp black pepper, ½ tsp garlic granules and a dash of Worcestershire. Build the bowl with shredded lettuce, cheese, gherkins and sauce"],
    "d-philly": ["", "Chips into the air fryer with the oil and salt, 200°C for 20 min. Slice the onion and peppers and cook in a little oil with a pinch of salt for 12 min until soft and sweet; season with black pepper and a few drops of Worcestershire. Slice the steak as thin as you can (20 min in the freezer first helps), flash-fry 2 min with the veg, lay the cheese over to melt, pile into the toasted roll"],
    "d-pizza": ["", "Oven and a tray to the hottest setting. Season the chicken with ½ tsp dried oregano, ½ tsp garlic granules, salt and pepper; pan-fry or air-fry 10 min and slice. Sauce: 60 g passata, ½ tsp dried oregano, ½ grated garlic clove, a pinch each of salt, sugar and chilli flakes. Spread the sauce thin, top with mozzarella, chicken and pepperoni, bake on the hot tray 8–10 min"],
    "s-choc-mousse": ["", "Whisk 250 g skyr, 30 g chocolate whey, 10 g cocoa and 10 g honey until thick and smooth; berries on top, grate over the dark chocolate. 5 min"],
    "s-cheesecake": ["", "Crush a digestive into a bowl or jar; whisk 200 g skyr, 30 g light cream cheese, 30 g vanilla whey, 10 g honey and a few drops of vanilla until smooth; spoon over; top with berries. 5 min"],
    "d-gyros": ["Per portion marinade: 30 g Greek yoghurt, juice of ¼ lemon, 1 grated garlic clove, 1 tsp dried oregano, 1 tsp smoked paprika, ½ tsp cumin, ½ tsp salt, 5 ml olive oil. Bag the raw thighs in it. Tzatziki pot: 30 g yoghurt, 30 g grated and squeezed cucumber, ½ garlic clove, a pinch of dried mint and salt", "Cut the chips and air-fry at 200°C for 20 min; add the thighs for the last 18 min (or grill them). Slice the red onion, tomato and lettuce; slice the chicken and build the wrap with tzatziki and a few chips. 25 min"],
    "d-peri-peri": ["Per portion: bag the raw thighs with 30 g peri-peri sauce, juice of ¼ lemon, 1 grated garlic clove and ½ tsp smoked paprika. Garlic dip pot: 40 g yoghurt, ½ garlic clove, a squeeze of lemon, a pinch of salt", "Rice on, cooked with ½ tsp smoked paprika, ¼ tsp turmeric, ½ tsp garlic granules, the diced peppers and ½ stock cube. Air-fry or grill the thighs at 200°C for 18–20 min. Warm the corn; dip on the side. 25 min"],
    "d-burrito-bowl": ["Per portion: rub the chicken with 1 tsp smoked paprika, ½ tsp cumin, ½ tsp chilli powder, ½ tsp garlic granules, ¼ tsp oregano, ½ tsp salt and a squeeze of lime; bag it raw", "Rice on. Air-fry or grill the chicken at 200°C for 18 min, rest and slice. Warm the beans and corn with a pinch of cumin and salt. Stir the zest and juice of ¼ lime and chopped coriander through the rice. Build with shredded lettuce, salsa, yoghurt and cheese. 25 min"],
    "d-crispy-burger": ["Per portion: butterfly the breast; season with ½ tsp smoked paprika, ½ tsp garlic granules, ¼ tsp cayenne, salt and pepper; dip in beaten egg, then panko seasoned the same way. Freeze raw on a lined tray, then bag. Sriracha mayo pot: 15 g light mayo, 5 g sriracha, squeeze of lime", "Cut the chips, toss in the oil and salt; air-fry with the chicken (from frozen) at 200°C for 20 min. Toast the bun, shred the lettuce, build with the sriracha mayo. 25 min"],
    "d-chicken-parm": ["Per portion: butterfly and bash the breast to 1.5 cm; season with salt, pepper and garlic granules; dip in beaten egg then panko mixed with 1 tsp dried oregano and 1 tbsp grated parmesan. Freeze raw on a lined tray, then bag. Marinara pot: 120 g passata simmered 10 min with ½ garlic clove, ½ tsp oregano, a pinch of chilli and salt", "Pasta on. Air-fry the chicken from frozen at 200°C for 18 min; spoon over a third of the marinara, mozzarella and parmesan on top, 3 min more. Toss the pasta in the rest of the sauce. 25 min"],
    "d-crispy-chilli": ["Per portion: dice the chicken and season with ½ tsp salt, ½ tsp black pepper and ¼ tsp five-spice; bag it raw. Sauce jar: 20 g ketchup, 10 g honey, 10 g sriracha, 10 ml soy, 15 ml rice vinegar, 1 grated garlic clove, 3 g cornflour and 30 ml water, shaken", "Rice on. Toss the chicken in 17 g cornflour, spritz with the oil and air-fry at 200°C for 12 min. Wok the sliced onion and peppers hot for 3 min, add the sauce and bubble until glossy, toss the chicken through. 25 min"],
    "d-meatballs": ["Per portion: mix the mince with 15 g panko, 15 g beaten egg, 1 grated garlic clove, 10 g grated parmesan, ½ tsp dried oregano, ½ tsp salt and black pepper; roll 6 meatballs and brown at 200°C for 15 min. Simmer 12 min in 150 g passata with ½ garlic clove, ½ tsp oregano and a pinch of chilli flakes. Portion", "Spaghetti on; reheat the meatballs in their sauce until piping hot, toss together with a splash of pasta water; parmesan on top. 10 min"],
    "l-ragu-box": ["Made in the same pot as the ragù pappardelle. Per portion: brown the seasoned shin; soften 50 g diced onion with 1 garlic clove; add 1 tsp tomato purée, 170 g passata, 100 ml beef stock, a bay leaf and ½ tsp dried oregano; pressure-cook 50 min (or 3 hours at 150°C), shred and reduce. Toss through the pasta, cooked 2 min short; box and freeze", "Microwave until piping hot, parmesan on top. 5 min"],
    "l-arrabbiata": ["Per portion: rub the chicken with ½ tsp dried oregano, ¼ tsp chilli flakes and ½ tsp salt; roast at 200°C for 18 min, rest and slice. Arrabbiata: 8 ml olive oil, 2 sliced garlic cloves and ½ tsp chilli flakes warmed gently, then 200 g chopped tomatoes with a pinch of sugar and salt; simmer 15 min. Toss the penne (2 min short) through the sauce; box with the chicken on top", "Microwave until piping hot, parmesan on top. 4 min"],
    "l-pesto-pasta": ["Per portion: rub the chicken with ½ tsp garlic granules, ½ tsp salt and lemon zest; roast at 200°C for 18 min, rest and dice. Cook the penne, cool under cold water, toss with 20 g pesto and the juice of ¼ lemon. Box with the chicken, halved tomatoes and torn mozzarella; rocket in a bag", "Add the rocket and eat cold. 1 min"],
    "l-tuna-pasta": ["Per portion: cook the penne and cool under cold water. Mix 15 g light mayo, 40 g Greek yoghurt, zest and juice of ¼ lemon, salt and pepper; fold through the pasta with the drained tuna, diced cucumber and corn. Box", "Eat cold. 0 min"]
  };

  // Prep components per recipe, per standard portion. The app pools these across the week's menu
  // and groups them by station. Spice lists: "qty unit name; ..." (units: g, ml, tsp, tbsp, clove, x, pinch).
  // L long cook [label, equip ip|hob, minutes, spices, method]
  // V veg [ingredient, cut]
  // M marinade/rub [type yog|wet|dry, label, protein ingredient, spices, minutes to marinate]
  // B coat [protein ingredient, panko|cornflour, spices]
  // X shape/assemble [label, method, spices?]
  // S sauce/dressing [label, spices, simmer minutes or 0, blend true|false]
  // O oven tray [temp °C, minutes, label]
  // H hob job [label, minutes, method, spices?]
  // T treat [label, method, spices]
  // P pack [what goes in the box]
  const COMP = {
    "l-salmon-poke": [["V", "cucumber", "half-moons"], ["M", "dry", "Salt and soy", "salmon", "0.5 tsp salt; 1 tsp soy", 0], ["O", 200, 12, "Salmon fillets, then flake"],
      ["S", "Quick cucumber pickle", "1 tsp rice vinegar; 1 pinch salt", 0], ["S", "Poke sauce", "10 g light mayo; 10 g sriracha; 10 ml soy; 0.5 tsp sesame oil", 0], ["P", "rice, flaked salmon, cucumber, edamame; poke sauce pot"]],
    "l-tuna-poke": [["V", "cucumber", "half-moons"], ["S", "Quick cucumber pickle", "1 tsp rice vinegar; 1 pinch salt; 1 pinch sugar", 0],
      ["S", "Tuna mayo (stir into the drained tuna)", "15 g light mayo; 10 g sriracha; 10 ml soy; 0.125 x lime juice", 0], ["P", "rice, cucumber, edamame; tuna mayo in a sealed pot (from Thursday, mix it on the day)"]],
    "l-teriyaki": [["V", "greens", "trimmed and halved"], ["M", "wet", "Teriyaki", "chicken-thigh", "15 ml teriyaki; 5 ml soy; 1 clove garlic; 1 tsp grated ginger", 30],
      ["O", 200, 18, "Teriyaki thighs (brush with 15 ml more teriyaki per portion for the last 5 min), then slice"], ["H", "Steam the greens", 5, "Steam 3 min, toss with a few drops of sesame oil and a pinch of salt"],
      ["P", "rice, sliced teriyaki chicken, greens; furikake in a twist of foil"]],
    "l-bulgogi": [["S", "Bulgogi sauce", "1 clove garlic; 1 tsp grated ginger; 20 g gochujang; 15 ml soy; 5 g honey; 5 ml sesame oil", 0],
      ["H", "Bulgogi mince", 15, "Brown the mince hard in a dry pan in batches, add the bulgogi sauce, cook down until sticky"], ["P", "rice, bulgogi mince; kimchi in a separate pot"]],
    "l-prawn-egg": [["H", "Boil eggs", 12, "Boil 7 min, into iced water, peel"], ["S", "Prawn dressing (toss the prawns in it)", "10 ml soy; 0.5 tsp sesame oil; 1 pinch chilli flakes", 0],
      ["S", "Sriracha mayo", "10 g light mayo; 1 tsp sriracha", 0], ["P", "rice, edamame; dressed prawns and halved eggs in a separate tub; sriracha mayo pot"]],
    "l-shawarma": [["V", "cucumber", "diced"], ["V", "tomato", "diced"], ["V", "gherkins", "sliced"],
      ["M", "yog", "Shawarma", "chicken-thigh", "30 g greek yoghurt; 1 tsp cumin; 1 tsp smoked paprika; 0.5 tsp turmeric; 0.5 tsp cinnamon; 0.5 tsp garlic granules; 0.25 x lemon juice; 0.5 tsp salt; 5 ml olive oil", 60],
      ["O", 220, 20, "Shawarma thighs, rest and slice"], ["S", "Tahini yoghurt", "30 g greek yoghurt; 8 g tahini; 0.125 x lemon juice; 1 pinch salt", 0],
      ["P", "rice, shawarma chicken; cucumber, tomato and pickle pot; tahini yoghurt pot"]],
    "l-spicy-salmon": [["V", "cucumber", "sliced"], ["M", "dry", "Salt and pepper", "salmon", "0.5 tsp salt; 0.25 tsp black pepper", 0], ["O", 200, 12, "Salmon fillets, then flake into the spicy mayo"],
      ["S", "Spicy mayo", "15 g light mayo; 15 g sriracha; 5 ml soy", 0], ["P", "seasoned rice, spicy salmon, cucumber, edamame; furikake on top"]],
    "l-onigiri": [],
    "l-thai-beef-salad": [["V", "cucumber", "batons"], ["V", "tomato", "wedges"], ["V", "onion", "thinly sliced (red)"], ["V", "lettuce", "torn"],
      ["M", "dry", "Salt and pepper", "steak", "0.5 tsp salt; 0.25 tsp black pepper", 0], ["H", "Sear the salad steak", 10, "Ripping-hot pan, 2 min a side, rest 5 min, slice thin"],
      ["S", "Thai dressing", "0.5 x lime juice; 15 ml fish sauce; 5 g honey; 0.5 x red chilli; 0.5 clove garlic", 0], ["P", "noodles, sliced beef, veg, mint and coriander; dressing jar; crushed peanuts in a bag"]],
    "l-caesar": [["V", "lettuce", "washed, dried and chopped"], ["M", "dry", "Lemon and herb rub", "chicken-breast", "5 ml olive oil; 0.5 tsp garlic granules; 0.5 tsp dried oregano; 0.5 tsp salt; 0.25 x lemon zest", 0],
      ["O", 200, 18, "Caesar chicken (74°C inside), rest and slice"], ["O", 200, 8, "Croutons: cubed sourdough, oil spray, pinch of salt and garlic granules"],
      ["S", "Caesar dressing", "50 g greek yoghurt; 10 g light mayo; 1 clove garlic; 1 tsp Dijon mustard; 0.25 x lemon juice; 0.5 tsp Worcestershire; 1 tbsp grated parmesan", 0],
      ["P", "lettuce, sliced chicken; dressing jar; croutons in a bag"]],
    "l-satay-noodle": [["V", "cucumber", "julienned"], ["V", "peppers", "julienned"], ["H", "Poach the satay chicken", 15, "Simmering water with a slice of ginger, 12 min; cool and shred"],
      ["S", "Satay sauce", "20 g peanut butter; 15 ml soy; 0.33 x lime juice; 5 g honey; 5 g sriracha; 0.5 clove garlic; 2 tbsp hot water", 0], ["P", "noodles, shredded chicken, veg, beansprouts; satay jar"]],
    "l-prawn-mango": [["V", "mango", "diced"], ["V", "cucumber", "diced"], ["V", "lettuce", "shredded"], ["S", "Lime and chilli dressing", "0.33 x lime juice; 10 g sriracha; 5 g honey; 1 pinch salt", 0],
      ["P", "rice; prawns, mango, cucumber and lettuce; dressing jar; avocado stays whole until the day"]],
    "l-spicy-tuna-salad": [["V", "cucumber", "sliced"], ["V", "lettuce", "shredded"], ["S", "Sriracha mayo (stir into the tuna on the day)", "15 g light mayo; 15 g sriracha; 0.125 x lime juice", 0],
      ["P", "seasoned rice, leaves, edamame, cucumber; sauce pot"]],

    "d-ragu": [["V", "onion", "finely diced"], ["L", "Beef ragù", "ip", 50, "1 clove garlic; 1 tsp tomato purée; 200 g passata; 100 ml beef stock; 1 x bay leaf; 0.5 tsp dried oregano; 0.5 tsp salt",
      "Brown the shin in batches on Sauté, soften the onion and garlic, add everything else, pressure-cook 50 min, shred, reduce on Sauté until thick"], ["P", "ragù; pasta"]],
    "d-doner": [["V", "onion", "thinly sliced"], ["V", "tomato", "sliced"], ["V", "lettuce", "shredded"],
      ["X", "Doner loaf", "Blitz the lamb mince to a paste with the spices, pack into a tight loaf, wrap in foil", "0.5 tsp salt; 0.5 tsp cumin; 0.5 tsp ground coriander; 0.5 tsp dried oregano; 0.5 tsp smoked paprika; 0.5 tsp garlic granules; 0.5 tsp onion powder; 0.25 tsp chilli flakes"],
      ["O", 180, 60, "Doner loaf (50 min in foil, 10 min uncovered); chill, then slice paper-thin"],
      ["S", "Garlic sauce", "50 g greek yoghurt; 1 clove garlic; 0.125 x lemon juice; 1 pinch dried mint; 1 pinch salt", 0], ["P", "doner slices; garlic sauce; salad; wraps; par-boiled chips"]],
    "d-meatball-sub": [["X", "Meatballs", "Mix the mince with the panko, egg and seasoning; roll 6 per portion", "1 clove garlic; 10 g grated parmesan; 0.5 tsp dried oregano; 0.5 tsp salt"],
      ["O", 200, 15, "Meatballs, to brown"], ["S", "Meatball marinara (simmer the cooked meatballs in it)", "120 g passata; 0.5 clove garlic; 0.5 tsp dried oregano; 1 pinch chilli flakes", 12],
      ["P", "meatballs in marinara; mozzarella; rolls"]],
    "d-lasagne": [["V", "onion", "finely diced"],
      ["H", "Lasagne ragù", 30, "Brown the mince with the onion and garlic, add the passata and seasoning, simmer 30 min", "1 clove garlic; 1 tsp tomato purée; 150 g passata; 0.5 tsp dried oregano; 1 x bay leaf; 0.5 tsp salt"],
      ["S", "Lasagne white sauce (whisk over the heat until thick)", "150 ml skimmed milk; 12 g cornflour; 1 pinch nutmeg; 1 pinch salt; 8 g grated parmesan", 5],
      ["X", "Build the lasagne", "Layer ragù, sheets and white sauce; finish with mozzarella and parmesan"], ["O", 180, 45, "Lasagne; rest 15 min before cutting"], ["P", "lasagne portions"]],
    "d-pasta-bake": [["H", "Pasta bake sauce", 15, "Brown the diced chicken and turkey rashers, add the garlic, passata and seasoning, simmer 10 min", "1 clove garlic; 150 g passata; 0.5 tsp dried oregano; 1 pinch chilli flakes; 0.25 tsp salt"],
      ["X", "Build the pasta bake", "Stir the penne through the sauce; top with mozzarella and parmesan"], ["O", 200, 15, "Pasta bake"], ["P", "pasta bake portions"]],
    "l-green-curry": [["V", "peppers", "sliced"], ["V", "broccoli", "small florets"],
      ["H", "Thai green curry", 20, "Fry the paste 1 min, seal the sliced thighs, add the coconut milk and water, simmer 10 min with the veg, then season", "30 g green curry paste; 150 ml light coconut milk; 50 ml water; 10 ml fish sauce; 0.25 x lime juice; 1 pinch sugar"],
      ["P", "rice, green curry"]],
    "l-tikka": [["V", "onion", "finely diced"], ["M", "yog", "Tikka", "chicken-breast", "40 g greek yoghurt; 12 g curry paste; 1 clove garlic; 0.25 x lemon juice; 0.5 tsp salt", 60],
      ["O", 220, 12, "Tikka chicken"], ["H", "Tikka masala sauce", 20, "Soften the onion with the garlic and ginger, fry the paste 1 min, add passata and coconut milk, simmer 10 min, blend smooth, stir in the chicken and garam masala", "1 clove garlic; 1 tsp grated ginger; 13 g curry paste; 120 g passata; 60 ml light coconut milk; 0.5 tsp garam masala"],
      ["P", "rice, tikka masala"]],
    "l-jalfrezi": [["V", "onion", "chunks"], ["V", "peppers", "chunks"],
      ["H", "Jalfrezi", 25, "Char the onion and peppers in a hot pan, set aside; fry the paste with garlic, ginger and chilli, brown the chicken, add the tomatoes, simmer 12 min, return the veg", "25 g curry paste; 1 clove garlic; 1 tsp grated ginger; 1 x green chilli; 150 g chopped tomatoes; 0.5 tsp garam masala; 0.5 tsp salt"],
      ["P", "rice, jalfrezi"]],
    "l-katsu-curry": [["V", "onion", "diced"], ["B", "chicken-breast", "panko", "0.5 tsp salt; 0.25 tsp black pepper"],
      ["S", "Katsu sauce (soften the onion first, then simmer and blend)", "20 g curry paste; 1 tsp honey; 1 clove garlic; 1 tsp grated ginger; 80 ml light coconut milk; 100 ml water", 10, true],
      ["P", "breaded chicken (freeze raw); katsu sauce; rice"]],
    "d-chilli": [["V", "onion", "diced"], ["V", "peppers", "diced"],
      ["L", "Chilli con carne", "hob", 40, "1 clove garlic; 1 tsp cumin; 1 tsp smoked paprika; 0.5 tsp chilli powder; 0.5 tsp dried oregano; 0.25 tsp cinnamon; 1 tsp tomato purée; 100 ml beef stock; 0.5 tsp salt; 5 g dark chocolate",
        "Brown the mince hard, soften the onion, peppers and garlic, add the spices and purée, then tomatoes, stock and beans; simmer 30 min, stir in the chocolate"], ["P", "rice, chilli; yoghurt pot"]],
    "l-massaman": [["V", "onion", "sliced"], ["V", "potatoes", "chunks"],
      ["L", "Beef massaman", "ip", 40, "25 g curry paste; 120 ml light coconut milk; 150 ml water; 5 ml fish sauce; 1 tsp honey; 1 x cinnamon stick; 1 x bay leaf",
        "Brown the beef on Sauté, fry the paste, add everything except the potatoes, pressure-cook 25 min, add the potatoes and pressure-cook 8 min more"], ["P", "rice, massaman; peanuts in a bag"]],

    "s-brownie": [["T", "Protein brownie batter", "Blitz the oats to flour, mix everything to a thick batter, fold in the chopped chocolate, spread in a lined tin", "30 g oats; 30 g chocolate whey; 12 g cocoa; 0.5 x egg; 15 g honey; 10 g dark chocolate; 1 pinch baking powder; 2 tbsp milk"],
      ["O", 180, 16, "Protein brownies (still fudgy in the middle); cool and cut into squares"]],
    "s-bark": [["T", "Yoghurt bark", "Mix the yoghurt and honey, spread 1 cm thick on a lined tray, scatter berries, granola and chopped chocolate; freeze 3 hours, then snap and bag", "300 g greek yoghurt; 15 g honey; 80 g berries; 20 g granola; 15 g dark chocolate"]],
    "s-crumble": [["T", "Crumble topping", "Rub together and spread on a tray", "30 g oats; 10 g peanut butter; 5 g honey; 1 pinch cinnamon"], ["O", 180, 10, "Crumble topping, until golden"],
      ["H", "Cinnamon apple", 6, "Dice the apple and cook with the honey, cinnamon and a splash of water for 5 min", "1 x apple; 5 g honey; 0.5 tsp cinnamon"],
      ["T", "Vanilla yoghurt pots", "Stir the whey into the yoghurt", "250 g greek yoghurt; 30 g vanilla whey"]],
    "s-pbj": [], "snack": [],
    "d-gyros": [["M", "yog", "Gyros", "chicken-thigh", "30 g greek yoghurt; 0.25 x lemon juice; 1 clove garlic; 1 tsp dried oregano; 1 tsp smoked paprika; 0.5 tsp cumin; 0.5 tsp salt; 5 ml olive oil", 60], ["S", "Tzatziki", "30 g greek yoghurt; 30 g cucumber, grated and squeezed; 0.5 clove garlic; 1 pinch dried mint; 1 pinch salt", 0], ["P", "raw gyros thighs in their marinade, bagged flat; tzatziki pot"]],
    "d-peri-peri": [["M", "wet", "Peri-peri", "chicken-thigh", "30 g peri-peri sauce; 0.25 x lemon juice; 1 clove garlic; 0.5 tsp smoked paprika", 60], ["S", "Garlic dip", "40 g greek yoghurt; 0.5 clove garlic; 0.125 x lemon juice; 1 pinch salt", 0], ["P", "raw peri-peri thighs in their marinade, bagged flat; garlic dip pot"]],
    "d-burrito-bowl": [["M", "dry", "Burrito spice", "chicken-breast", "1 tsp smoked paprika; 0.5 tsp cumin; 0.5 tsp chilli powder; 0.5 tsp garlic granules; 0.25 tsp dried oregano; 0.5 tsp salt; 0.125 x lime juice", 0], ["P", "spice-rubbed raw chicken, bagged flat"]],
    "d-crispy-burger": [["B", "chicken-breast", "panko", "0.5 tsp smoked paprika; 0.5 tsp garlic granules; 0.25 tsp cayenne; 0.5 tsp salt"], ["S", "Sriracha mayo", "15 g light mayo; 5 g sriracha; 0.125 x lime juice", 0], ["P", "breaded chicken (freeze raw); sriracha mayo pot"]],
    "d-chicken-parm": [["B", "chicken-breast", "panko", "1 tsp dried oregano; 1 tbsp grated parmesan; 0.5 tsp garlic granules; 0.5 tsp salt"], ["S", "Marinara", "120 g passata; 0.5 clove garlic; 0.5 tsp dried oregano; 1 pinch chilli flakes; 1 pinch salt", 10], ["P", "breaded chicken (freeze raw); marinara pot"]],
    "d-crispy-chilli": [["M", "dry", "Five-spice seasoning (dice the chicken first)", "chicken-breast", "0.5 tsp salt; 0.5 tsp black pepper; 0.25 tsp five-spice", 0], ["S", "Crispy chilli sauce", "20 g ketchup; 10 g honey; 10 g sriracha; 10 ml soy; 15 ml rice vinegar; 1 clove garlic; 3 g cornflour; 30 ml water", 0], ["P", "diced seasoned raw chicken, bagged flat; sauce jar"]],
    "d-meatballs": [["X", "Meatballs", "Mix the mince with the panko, egg and seasoning; roll 6 per portion", "1 clove garlic; 10 g grated parmesan; 0.5 tsp dried oregano; 0.5 tsp salt"], ["O", 200, 15, "Meatballs, to brown"], ["S", "Meatball marinara (simmer the cooked meatballs in it)", "150 g passata; 0.5 clove garlic; 0.5 tsp dried oregano; 1 pinch chilli flakes", 12], ["P", "meatballs in marinara"]],
    "l-ragu-box": [["V", "onion", "finely diced"], ["L", "Beef ragù", "ip", 50, "1 clove garlic; 1 tsp tomato purée; 170 g passata; 100 ml beef stock; 1 x bay leaf; 0.5 tsp dried oregano; 0.5 tsp salt", "Brown the shin in batches on Sauté, soften the onion and garlic, add everything else, pressure-cook 50 min, shred, reduce on Sauté until thick"], ["P", "pasta tossed through the ragù; parmesan in a twist of foil"]],
    "l-arrabbiata": [["M", "dry", "Chilli and oregano rub", "chicken-breast", "0.5 tsp dried oregano; 0.25 tsp chilli flakes; 0.5 tsp salt", 0], ["O", 200, 18, "Arrabbiata chicken (74°C inside), rest and slice"], ["S", "Arrabbiata (toss the cooked penne through it)", "8 ml olive oil; 2 clove garlic; 0.5 tsp chilli flakes; 200 g chopped tomatoes; 1 pinch sugar; 1 pinch salt", 15], ["P", "penne in arrabbiata, sliced chicken on top; parmesan in a twist of foil"]],
    "l-pesto-pasta": [["V", "tomato", "halved"], ["M", "dry", "Lemon and garlic rub", "chicken-breast", "0.5 tsp garlic granules; 0.5 tsp salt; 0.25 x lemon zest", 0], ["O", 200, 18, "Pesto pasta chicken (74°C inside), rest and dice"], ["S", "Pesto dressing (toss through the cooled penne)", "20 g pesto; 0.25 x lemon juice", 0], ["P", "pesto penne, diced chicken, tomatoes, torn mozzarella; rocket in a bag"]],
    "l-tuna-pasta": [["V", "cucumber", "diced"], ["S", "Lemon tuna mayo (fold through the cooled penne, tuna, cucumber and corn)", "15 g light mayo; 40 g greek yoghurt; 0.25 x lemon juice; 0.25 x lemon zest; 1 pinch salt; 1 pinch black pepper", 0], ["P", "tuna pasta salad, ready mixed"]]
  };
  // Rough whole-veg weights for "about N" counts.
  const VEG_EACH = { onion: [150, "onion"], peppers: [160, "pepper"], cucumber: [300, "cucumber"], tomato: [90, "tomato"], broccoli: [350, "head of broccoli"], lettuce: [250, "lettuce"], mango: [200, "mango"], greens: [250, "bunch of pak choi or greens"] };

  // Carbs cooked in one batch on Sunday, except for these recipes (cooked on the day or built into the dish).
  const BATCH_CARBS = ["sushi-rice", "jasmine-rice", "pasta", "penne", "rice-noodles", "potatoes"];
  const NO_BATCH = ["l-onigiri"];

  // Ingredients some people don't eat.
  const TAGS = { pork: [] };

  const RECIPES = {};
  R.forEach(function (r) { RECIPES[r.id] = r; });
  return { ING: ING, RECIPES: RECIPES, OPTIONS: OPTIONS, TAGS: TAGS, PREP: PREP, BATCH_CARBS: BATCH_CARBS, NO_BATCH: NO_BATCH, COMP: COMP, VEG_EACH: VEG_EACH };
})();
