// Shared food data for Gym-Bro and Gym-Gyal. Keep this file identical in both repos.
// Generated layout, hand-edited content. Run tests/data-check.js after any change.
window.BB_DATA = (function () {
  // name, aisle, kcal, protein, carbs, fat per 100 g, [unit weight, unit name], [flag]
  // flag: "fixed" = never scaled; "aroma" = scales with the dish (garlic, ginger, citrus, herbs).
  const ING = {
    "sushi-rice": ["Sushi rice", "Carbs",358,6.5,79,0.6],
    "jasmine-rice": ["Jasmine or basmati rice", "Carbs",356,7,79,0.6],
    "pasta": ["Spaghetti, linguine or pappardelle", "Carbs",355,12.5,71,1.5],
    "penne": ["Penne or rigatoni", "Carbs",355,12.5,71,1.5],
    "lasagne-sheets": ["Lasagne sheets", "Carbs",355,12.5,71,1.5],
    "oats": ["Porridge oats", "Carbs",375,11,60,8],
    "sourdough": ["Sourdough", "Carbs",250,9,48,1.5,45,"slices"],
    "brioche": ["Brioche buns", "Carbs",330,9,50,10,60,"buns"],
    "wrap": ["Large wraps", "Carbs",300,8.5,50,7,62,"wraps"],
    "sub-roll": ["Sub rolls", "Carbs",270,9,50,3,90,"rolls"],
    "pizza-base": ["Thin pizza bases", "Carbs",270,8,52,3,150,"bases"],
    "potatoes": ["Potatoes", "Carbs",77,2,17,0.1],
    "rice-noodles": ["Rice noodles (dry)", "Carbs",360,6,82,0.6],
    "digestives": ["Digestive biscuits", "Carbs",480,7,62,21,15,"biscuits"],
    "rice-cakes": ["Rice cakes", "Carbs",390,8,81,3,8,"rice cakes"],
    "panko": ["Panko breadcrumbs", "Carbs",370,12,75,3],
    "granola": ["Granola (lower sugar)", "Carbs",430,10,60,15],
    "english-muffin": ["English muffins", "Carbs",225,9,43,1.8,68,"muffins"],
    "thin-bagel": ["Thin bagels", "Carbs",255,10,48,2,45,"bagels"],
    "mini-wrap": ["Mini wraps", "Carbs",300,8.5,50,7,31,"wraps"],
    "sr-flour": ["Self-raising flour", "Carbs",340,9.5,72,1.2],
    "oreo": ["Oreo biscuits", "Carbs",480,5,69,20,11,"biscuits"],
    "weetabix-minis": ["Weetabix Minis Chocolate Chip", "Carbs", 389, 9.9, 71, 5.3],
    "chicken-breast": ["Chicken breast", "Protein",106,24,0,1.1],
    "chicken-thigh": ["Chicken thigh fillets, skinless", "Protein",125,20,0,4.9],
    "beef-mince": ["5% beef mince", "Protein",125,21,0,5],
    "lamb-mince": ["Lean lamb mince", "Protein",150,20,0,8],
    "beef-shin": ["Beef shin", "Protein",130,21,0,5],
    "steak": ["Sirloin steak, trimmed", "Protein",150,23,0,6],
    "turkey-rashers": ["Turkey rashers", "Protein",105,22,0.5,1.5],
    "turkey-mince": ["Turkey thigh mince (7% fat)", "Protein",140,20,0,7],
    "chicken-mince": ["Chicken mince", "Protein",120,20,0,4.5],
    "turkey-ham": ["Turkey ham", "Protein",105,19,2,2.5],
    "turkey-pepperoni": ["Turkey pepperoni", "Protein",180,22,2,9],
    "salmon": ["Salmon fillets", "Protein",200,20,0,13],
    "tuna": ["Tuna in spring water, drained", "Protein",110,25,0,1],
    "prawns": ["King prawns, cooked", "Protein",70,16,0,0.9],
    "whey": ["Whey protein", "Protein",390,78,7,6],
    "eggs": ["Eggs", "Dairy and eggs",140,12.5,0.5,10,50,"eggs"],
    "egg-whites": ["Liquid egg whites", "Dairy and eggs",50,11,0.5,0.2],
    "greek-yog": ["Greek yoghurt 0%", "Dairy and eggs",57,10,4,0.2],
    "milk": ["Semi-skimmed milk", "Dairy and eggs",47,3.5,4.8,1.7],
    "skimmed-milk": ["Skimmed milk", "Dairy and eggs",35,3.5,5,0.1],
    "mozzarella": ["Light mozzarella", "Dairy and eggs",165,20,1,9],
    "parmesan": ["Parmesan", "Dairy and eggs",390,33,0,28],
    "pecorino": ["Pecorino", "Dairy and eggs",390,28,0,30],
    "skyr": ["Skyr (plain)", "Dairy and eggs",65,11,4,0.2],
    "cream-cheese": ["Light cream cheese", "Dairy and eggs",150,7,5,11],
    "cheese-slice": ["Light cheese slices", "Dairy and eggs",250,20,5,15,20,"slices"],
    "cheddar": ["Light mature cheddar", "Dairy and eggs",310,28,1,22],
    "cottage-cheese": ["Cottage cheese (low fat)", "Dairy and eggs",70,11,4,1.5],
    "squirty-cream": ["Light squirty cream", "Dairy and eggs",200,2.5,9,17],
    "cherries": ["Frozen cherries", "Fruit and veg",50,1,11,0.2],
    "strawberries": ["Frozen strawberries", "Fruit and veg",32,0.7,6,0.3],
    "onion": ["Onions", "Fruit and veg",40,1.1,9,0.1],
    "garlic": ["Garlic", "Fruit and veg",110,6,24,0.5,null,null,"aroma"],
    "peppers": ["Peppers", "Fruit and veg",30,1,6,0.3],
    "lettuce": ["Lettuce", "Fruit and veg",15,1.2,2,0.2],
    "cucumber": ["Cucumber", "Fruit and veg",15,0.7,3,0.1],
    "tomato": ["Tomatoes", "Fruit and veg",18,0.9,3.5,0.2],
    "broccoli": ["Tenderstem or broccoli", "Fruit and veg",34,2.8,7,0.4],
    "greens": ["Pak choi or green veg", "Fruit and veg",30,3,4,0.4],
    "rocket": ["Rocket", "Fruit and veg",25,2.6,3.6,0.7],
    "edamame": ["Edamame beans (frozen)", "Fruit and veg",125,11,7,5],
    "peas": ["Frozen peas", "Fruit and veg",70,5.5,10,1.4],
    "berries": ["Berries (frozen is fine)", "Fruit and veg",50,1,9,0.3],
    "apple": ["Apples", "Fruit and veg",52,0.3,14,0.2,150,"apples"],
    "beansprouts": ["Beansprouts", "Fruit and veg",30,3,4,0.2],
    "lime": ["Limes", "Fruit and veg",30,0.7,10,0.2,65,"limes", "aroma"],
    "mango": ["Mango", "Fruit and veg",60,0.8,15,0.4],
    "avocado": ["Avocado", "Fruit and veg",160,2,9,15],
    "corn": ["Sweetcorn (frozen or tin)", "Fruit and veg",86,3.3,19,1.4],
    "spinach": ["Spinach", "Fruit and veg",23,2.9,3.6,0.4],
    "kimchi": ["Kimchi", "Fruit and veg",20,1.5,3,0.5],
    "gherkins": ["Gherkins", "Fruit and veg",20,0.5,4,0.1],
    "passata": ["Passata", "Sauces and cupboard",30,1.4,5,0.2],
    "chopped-tom": ["Chopped tomatoes (tins)", "Sauces and cupboard",22,1.1,3.5,0.2],
    "olive-oil": ["Olive oil", "Sauces and cupboard",900,0,0,100],
    "sesame-oil": ["Sesame oil", "Sauces and cupboard",900,0,0,100],
    "soy": ["Light soy sauce", "Sauces and cupboard",60,8,7,0],
    "sushi-vinegar": ["Sushi seasoning or rice vinegar", "Sauces and cupboard",150,0,35,0],
    "teriyaki": ["Teriyaki sauce (reduced sugar)", "Sauces and cupboard",120,3,25,0],
    "gochujang": ["Gochujang", "Sauces and cupboard",220,4,45,2],
    "sriracha": ["Sriracha", "Sauces and cupboard",100,2,20,1],
    "light-mayo": ["Light mayo", "Sauces and cupboard",260,1,8,25],
    "ketchup": ["Ketchup", "Sauces and cupboard",100,1,23,0.1],
    "honey": ["Honey", "Sauces and cupboard",304,0.3,82,0],
    "peanut-butter": ["Peanut butter", "Sauces and cupboard",600,25,12,49],
    "tahini": ["Tahini", "Sauces and cupboard",600,17,20,53],
    "cornflour": ["Cornflour", "Sauces and cupboard",350,0.3,88,0.1],
    "furikake": ["Furikake or toasted sesame", "Sauces and cupboard",400,20,40,15],
    "salsa": ["Salsa (jar)", "Sauces and cupboard",35,1,7,0.2],
    "coconut-light": ["Light coconut milk", "Sauces and cupboard",75,0.7,2.5,7],
    "green-curry-paste": ["Thai green curry paste", "Sauces and cupboard",110,2,12,6],
    "curry-paste": ["Curry paste (tikka, jalfrezi or katsu)", "Sauces and cupboard",150,3,15,9],
    "coffee": ["Coffee (espresso or strong brew)", "Sauces and cupboard",2,0.1,0,0,null,null,"fixed"],
    "fish-sauce": ["Fish sauce", "Sauces and cupboard",35,5,4,0],
    "peanuts": ["Roasted peanuts", "Sauces and cupboard",590,26,13,49],
    "kidney-beans": ["Kidney beans (tin, drained)", "Sauces and cupboard",100,7,15,0.5],
    "peri-peri": ["Peri-peri sauce", "Sauces and cupboard",80,1,15,2],
    "pb-powder": ["Peanut butter powder", "Sauces and cupboard",375,48,25,9],
    "jalapenos": ["Pickled jalapeños (jar)", "Sauces and cupboard",20,1,3,0.5],
    "franks": ["Frank's RedHot sauce", "Sauces and cupboard",15,1,2,0.5],
    "icing-sugar": ["Icing sugar", "Sauces and cupboard",400,0,100,0],
    "lager": ["Lager", "Sauces and cupboard",40,0.3,3,0],
    "cocoa": ["Cocoa powder", "Sauces and cupboard",380,20,12,21],
    "dark-choc": ["Dark chocolate (85%)", "Sauces and cupboard",600,10,20,50],
    "jam": ["Reduced-sugar jam", "Sauces and cupboard",140,0.5,34,0.1],
    "pesto": ["Green pesto", "Sauces and cupboard",380,4.5,5,38],
    "olives": ["Black olives, pitted", "Sauces and cupboard",150,1,1,15],
    "capers": ["Capers", "Sauces and cupboard",25,2,2,0.5],
    "ginger": ["Fresh ginger", "Fruit and veg",80,1.8,18,0.8,null,null,"aroma"],
    "lemon": ["Lemons", "Fruit and veg",29,1.1,9,0.3,100,"lemons", "aroma"],
    "chilli": ["Fresh chillies", "Fruit and veg",40,2,9,0.4,15,"chillies", "aroma"],
    "spring-onion": ["Spring onions", "Fruit and veg",32,1.8,7,0.2,15,"spring onions", "aroma"],
    "basil": ["Fresh basil", "Fruit and veg",23,3,3,0.6,null,null,"aroma"],
    "coriander": ["Fresh coriander", "Fruit and veg",23,2,4,0.5,null,null,"aroma"],
    "parsley": ["Fresh parsley", "Fruit and veg",36,3,6,0.8,null,null,"aroma"],
    "mint": ["Fresh mint", "Fruit and veg",44,3.3,8,0.7,null,null,"aroma"]
  };

  // Kitchen names used in seasoning lists that are the same thing as a shopping ingredient: name -> [ingredient, grams per unit, "zest"].
  // tests/data-check.js makes sure each dish's ingredient list covers what its seasoning lists use.
  const ALIAS = {
    "garlic": ["garlic",{"clove":5}],
    "grated ginger": ["ginger",{"tsp":5}],
    "lemon juice": ["lemon",{"x":100}],
    "lemon zest": ["lemon",{"x":100},"zest"],
    "lime juice": ["lime",{"x":65}],
    "red chilli": ["chilli",{"x":15}],
    "green chilli": ["chilli",{"x":15}],
    "spring onion": ["spring-onion",{"x":15}],
    "fresh basil": ["basil",{}],
    "fresh coriander": ["coriander",{}],
    "fresh parsley": ["parsley",{}],
    "fresh mint": ["mint",{}],
    "greek yoghurt": ["greek-yog",{}],
    "light mayo": ["light-mayo",{}],
    "sriracha": ["sriracha",{"tsp":5}],
    "soy": ["soy",{"tsp":5}],
    "honey": ["honey",{"tsp":7}],
    "passata": ["passata",{}],
    "chopped tomatoes": ["chopped-tom",{}],
    "olive oil": ["olive-oil",{"tsp":5}],
    "sesame oil": ["sesame-oil",{"tsp":5}],
    "rice vinegar": ["sushi-vinegar",{"tsp":5}],
    "teriyaki": ["teriyaki",{}],
    "gochujang": ["gochujang",{}],
    "ketchup": ["ketchup",{}],
    "tahini": ["tahini",{}],
    "peri-peri sauce": ["peri-peri",{}],
    "pesto": ["pesto",{}],
    "curry paste": ["curry-paste",{}],
    "green curry paste": ["green-curry-paste",{}],
    "light coconut milk": ["coconut-light",{}],
    "fish sauce": ["fish-sauce",{}],
    "cornflour": ["cornflour",{}],
    "grated parmesan": ["parmesan",{"tbsp":5}],
    "skimmed milk": ["skimmed-milk",{}],
    "milk": ["milk",{"tbsp":15,"tsp":5}],
    "light cheese slice": ["cheese-slice",{"x":20}],
    "light cheddar": ["cheddar",{}],
    "cottage cheese": ["cottage-cheese",{}],
    "Frank's hot sauce": ["franks",{}],
    "lager": ["lager",{"tbsp":15}],
    "self-raising flour": ["sr-flour",{}],
    "frozen cherries": ["cherries",{}],
    "icing sugar": ["icing-sugar",{}],
    "Oreo": ["oreo",{"x":11}],
    "peanut butter powder": ["pb-powder",{}],
    "oats": ["oats",{}],
    "peanut butter": ["peanut-butter",{}],
    "cocoa": ["cocoa",{}],
    "dark chocolate": ["dark-choc",{}],
    "chocolate whey": ["whey",{}],
    "vanilla whey": ["whey",{}],
    "granola": ["granola",{}],
    "berries": ["berries",{}],
    "apple": ["apple",{"x":150}],
    "egg": ["eggs",{"x":50}],
    "cucumber, grated and squeezed": ["cucumber",{}],
    "skyr": ["skyr",{}],
    "light cream cheese": ["cream-cheese",{}],
    "olives": ["olives",{}],
    "capers": ["capers",{}]
  };
  // Seasonings that live in the cupboard: checked off, not bought by weight.
  const CUPBOARD = {"American mustard":"American mustard", "Dijon mustard":"Dijon mustard", "Worcestershire":"Worcestershire", "baking powder":"Baking powder", "bay leaf":"Bay leaf", "beef stock":"Beef stock (cubes)", "black pepper":"Black pepper", "butter":"Butter", "cayenne":"Cayenne", "chilli flakes":"Chilli flakes", "chilli powder":"Chilli powder", "cinnamon":"Cinnamon", "cinnamon stick":"Cinnamon stick", "cumin":"Cumin", "dried mint":"Dried mint", "dried oregano":"Dried oregano", "dried thyme":"Dried thyme", "five-spice":"Five-spice", "garam masala":"Garam masala", "garlic granules":"Garlic granules", "ground cardamom":"Ground cardamom", "ground coriander":"Ground coriander", "nutmeg":"Nutmeg", "onion powder":"Onion powder", "salt":"Salt", "smoked paprika":"Smoked paprika", "stock cube":"Stock cube", "sugar":"Sugar", "tomato purée":"Tomato purée", "turmeric":"Turmeric", "vanilla extract":"Vanilla extract", "white pepper":"White pepper", "dried sage":"Dried sage", "Italian herbs":"Italian herbs", "taco seasoning":"Taco seasoning", "sprinkles":"Sprinkles", "xanthan gum":"Xanthan gum"};
  // Buy this much more than the prepared weight (peel, trim, stones).
  const TRIM = {"onion":1.1,"garlic":1.2,"ginger":1.25,"peppers":1.15,"lettuce":1.15,"broccoli":1.1,"greens":1.1,"mango":1.45,"avocado":1.35,"potatoes":1.05,"apple":1.1,"spring-onion":1.1,"basil":1.2,"coriander":1.2,"parsley":1.2,"mint":1.2,"cucumber":1.03,"chicken-thigh":1.05,"beef-shin":1.1};
  // Typical UK pack: [grams, label]. A guide only; the weight needed is always shown.
  const PACKS = {"chopped-tom":[400,"tin"],"passata":[500,"carton"],"coconut-light":[400,"tin"],"kidney-beans":[240,"tin, drained"],"tuna":[102,"tin, drained"],"eggs":[300,"box of 6"],"beef-mince":[500,"pack"],"mozzarella":[125,"ball"],"skyr":[450,"pot"],"greek-yog":[500,"tub"],"wrap":[496,"pack of 8"],"brioche":[240,"pack of 4"],"sub-roll":[360,"pack of 4"],"pizza-base":[300,"pack of 2"],"rocket":[60,"bag"],"spinach":[200,"bag"],"beansprouts":[300,"bag"],"cream-cheese":[165,"tub"],"cheese-slice":[200,"pack of 10"],"english-muffin":[272,"pack of 4"],"thin-bagel":[270,"pack of 6"],"mini-wrap":[248,"pack of 8"],"turkey-mince":[500,"pack"],"chicken-mince":[500,"pack"],"pasta":[500,"pack"],"penne":[500,"pack"],"sushi-rice":[500,"pack"],"jasmine-rice":[1000,"bag"],"basil":[30,"pot or bunch"],"coriander":[30,"bunch"],"parsley":[30,"bunch"],"mint":[30,"bunch"],"salmon":[240,"pack of 2 fillets"]};

  // The household. Dinners and treats are shared; breakfast, shake and lunch are per person.
  // scales: p = protein and dairy, c = carbs, fats and sauces, v = fruit and veg.
  // pieces: how many this person has of a breakfast that is built in whole pieces (a recipe with pieces: true).
  const HOUSE = {
    "order": [
      "blue",
      "harriett"
    ],
    "prep": {
      "chef": "blue",
      "helper": "harriett"
    },
    "shared": [
      "dinner",
      "snack"
    ],
    "people": {
      "blue": {
        "name": "Blue",
        "pieces": 2,
        "scales": {
          "p": 1,
          "c": 0.88,
          "v": 1
        },
        "skip": [
          "curry"
        ]
      },
      "harriett": {
        "name": "Harriett",
        "pieces": 1,
        "scales": {
          "p": 0.7,
          "c": 0.45,
          "v": 1
        },
        "skip": []
      }
    }
  };
  // The menu a new week starts from (0 = Sunday).
  const DEFAULTS = {"dinner":{"0":"d-meatballs", "1":"d-ragu", "2":"d-smash", "3":"d-fried-rice", "4":"d-peri-peri", "5":"d-bigmac", "6":"d-carbonara"},"snack":{"0":"s-bark", "1":"s-brownie", "2":"s-brownie", "3":"s-brownie", "4":"s-brownie", "5":"s-bark", "6":"s-bark"},"lunch":{"blue":{"0":"l-tuna-poke", "1":"l-teriyaki", "2":"l-teriyaki", "3":"l-teriyaki", "4":"l-ragu-box", "5":"l-ragu-box", "6":"l-ragu-box"},"harriett":{"0":"l-spicy-tuna-salad", "1":"l-shawarma", "2":"l-shawarma", "3":"l-shawarma", "4":"l-green-curry", "5":"l-green-curry", "6":"l-green-curry"}},"breakfast":{"blue":{"0":"bf-weetabix", "1":"bf-mcbuffin", "2":"bf-mcbuffin", "3":"bf-mcbuffin", "4":"bf-bagel", "5":"bf-bagel", "6":"bf-bagel"},"harriett":{"0":"bf-weetabix", "1":"bf-mcbuffin", "2":"bf-mcbuffin", "3":"bf-mcbuffin", "4":"bf-bagel", "5":"bf-bagel", "6":"bf-bagel"}},"shake":{"blue":{"0":"sh-strawberry", "1":"sh-choc-pb", "2":"sh-mocha", "3":"sh-strawberry", "4":"sh-berry-oat", "5":"sh-lassi", "6":"sh-choc-pb"},"harriett":{"0":"sh-strawberry", "1":"sh-choc-pb", "2":"sh-mocha", "3":"sh-strawberry", "4":"sh-berry-oat", "5":"sh-lassi", "6":"sh-choc-pb"}}};

  // One-off weeks that start from something other than DEFAULTS. Delete an entry once its week has passed
  // (tests/data-check.js fails when one is more than two weeks old).
  // Week of 5 Oct 2026: prepped and shopped before the household update, so it keeps Blue's menu from then.
  const PRESETS = { "2026-10-05": {
    dinner: {"1": "d-gyros", "2": "d-philly", "3": "d-fried-rice", "4": "d-doner", "5": "d-bigmac", "6": "d-lasagne", "0": "d-meatballs"},
    snack: {"1": "s-choc-mousse", "2": "s-brownie", "3": "s-cheesecake", "4": "s-bark", "5": "s-crumble", "6": "s-pbj", "0": "snack"},
    breakfast: {blue: {"1": "bf-weetabix", "2": "bf-weetabix", "3": "bf-weetabix", "4": "bf-weetabix", "5": "bf-weetabix", "6": "bf-weetabix", "0": "bf-weetabix"}, harriett: {"1": "bf-weetabix", "2": "bf-weetabix", "3": "bf-weetabix", "4": "bf-weetabix", "5": "bf-weetabix", "6": "bf-weetabix", "0": "bf-weetabix"}},
    lunch: {blue: {"1": "l-teriyaki", "2": "l-bulgogi", "3": "l-prawn-egg", "4": "l-spicy-salmon", "5": "l-shawarma", "6": "l-prawn-egg", "0": "l-tuna-poke"}},
    shake: {blue: {"1": "sh-choc-pb", "2": "sh-mocha", "3": "sh-strawberry", "4": "sh-berry-oat", "5": "sh-lassi", "6": "sh-choc-pb", "0": "sh-strawberry"}}
  } };

  // Recipes: ing = grams per full portion. sea = [label, list] seasoning groups not covered by a Sunday component.
  // method = from scratch, no amounts (they are in the lists). finish = on the day, after Sunday prep.
  // Dinners: type fresh | head | sunday. Lunches: late freeze | split | no (Monday to Wednesday only).
  // Breakfasts built in whole pieces: pieces: true = small ones, ing is one piece and each person has their own number of them
  // (HOUSE pieces). whole: [ingredients] = big ones, one each: those ingredients stay whole and the filling follows the person's scales.
  // O, X and H components may end with a list of ingredients to show the weight of, instead of the dish's main protein.
  // comp = Sunday components: V veg, L long cook, M marinade, B breading, X shape, S sauce, O oven, H hob, T treat, P pack.
  // The run sheet works out what each component needs first; after = {component index: [indexes it also needs]} for the exceptions.
  const R = [
    { id: "bf-weetabix", slot: "breakfast", name: "Chocolate chip Weetabix minis", time: "1 min",
      ing: [["weetabix-minis",75], ["milk",250]],
      method: ["Weigh the minis into a bowl.", "Pour over the cold milk and eat straight away, before they go soft."] },
    { id: "bf-mcbuffin", slot: "breakfast", name: "Spicy McBuffins", time: "Batch: 35 min", pieces: true,
      ing: [["english-muffin",68], ["turkey-mince",70], ["egg-whites",60], ["cheddar",10], ["cheese-slice",30], ["milk",5], ["jalapenos",10]],
      method: ["Season the mince, press thin patties and bake at 200°C for 12 minutes, turning once.", "Bake the egg whites with the cheddar in a lined tin at 180°C for 14 minutes and cut into squares.", "Nacho sauce: tear half the cheese slices into the warm milk with the paprika and garlic granules and whisk over a low heat until smooth.", "Build on a split muffin: cheese slice, egg, patty, nacho sauce, jalapeños. Toast in the air fryer for 3 minutes."],
      finish: "Unwrap, microwave 60 to 90 seconds, then air fryer at 200°C for 3 minutes. 5 min",
      comp: [["X", "Spicy turkey patties", "Mix the seasoning through the mince and press thin patties onto a lined tray, one per sandwich or burrito", "0.125 tsp salt; 0.25 tsp garlic granules; 0.25 tsp smoked paprika; 1 pinch chilli flakes; 1 pinch black pepper",["turkey-mince"]],
        ["O",200,12,"Sausage patties, turned once",["turkey-mince","chicken-mince"]],
        ["O",180,14,"Egg white sheet: lined tin, any cheddar scattered over; cool and cut one square per sandwich",["egg-whites","cheddar"]],
        ["S", "Nacho cheese sauce", "0.5 x light cheese slice; 1 tsp milk; 1 pinch smoked paprika; 1 pinch garlic granules",3],
        ["P", "Build each one on a split muffin: cheese slice, egg square, patty, nacho sauce, jalapeños, lid. Wrap one by one"]] },
    { id: "bf-poorboy", slot: "breakfast", name: "Sage chicken McMuffins", time: "Batch: 35 min", pieces: true,
      ing: [["english-muffin",68], ["chicken-mince",70], ["egg-whites",50], ["cheddar",12], ["cheese-slice",20]],
      method: ["Mix the sage, herbs and seasoning through the mince, press thin patties and bake at 200°C for 12 minutes, turning once.", "Bake the egg whites with the cheddar in a lined tin at 180°C for 14 minutes and cut into squares.", "Build on a split muffin: patty, cheese slice, egg. Toast in the air fryer for 3 minutes."],
      finish: "Unwrap, microwave 60 to 90 seconds, then air fryer at 200°C for 3 minutes. 5 min",
      comp: [["X", "Sage chicken patties", "Mix the seasoning through the mince and press thin patties onto a lined tray, one per sandwich", "0.125 tsp salt; 0.5 tsp dried sage; 0.25 tsp Italian herbs; 1 pinch black pepper",["chicken-mince"]],
        ["O",200,12,"Sausage patties, turned once",["turkey-mince","chicken-mince"]],
        ["O",180,14,"Egg white sheet: lined tin, any cheddar scattered over; cool and cut one square per sandwich",["egg-whites","cheddar"]],
        ["P", "Build each one on a split muffin: patty, cheese slice, egg square, lid. Wrap one by one"]] },
    { id: "bf-bagel", slot: "breakfast", name: "Turkey bacon and egg bagels", time: "Batch: 25 min", pieces: true,
      ing: [["thin-bagel",45], ["turkey-rashers",50], ["egg-whites",60], ["cheese-slice",20]],
      sea: [["Seasoning", "1 pinch salt; 1 pinch black pepper"]],
      method: ["Season the egg whites, bake in a lined tin at 180°C for 14 minutes and cut into squares.", "Bake the rashers flat on a lined tray at 200°C for 10 minutes.", "Build on a split bagel: egg, cheese slice, rashers. Toast in the air fryer for 3 minutes."],
      finish: "Unwrap, microwave 60 to 90 seconds, then air fryer at 200°C for 3 minutes. 5 min",
      comp: [["O",180,14,"Egg white sheet: lined tin, any cheddar scattered over; cool and cut one square per sandwich",["egg-whites","cheddar"]],
        ["O",200,10,"Turkey rashers, flat on a lined tray",["turkey-rashers"]],
        ["P", "Build each one on a split bagel: egg square, cheese slice, two rashers, lid. Wrap one by one"]] },
    { id: "bf-tacos", slot: "breakfast", name: "Steak and cheese breakfast tacos", time: "Batch: 35 min", pieces: true,
      ing: [["mini-wrap",31], ["steak",40], ["turkey-rashers",25], ["eggs",85], ["cheddar",13], ["cheese-slice",10], ["milk",5]],
      method: ["Season the steak, sear hard for 2 to 3 minutes a side, rest and dice small.", "Bake the rashers at 200°C for 10 minutes and chop.", "Scramble the eggs low and soft.", "Nacho sauce: tear the cheese slices into the warm milk with the paprika and garlic granules and whisk over a low heat until smooth.", "Fold the steak, rashers, cheddar and sauce through the eggs, fill and fold the wraps, and crisp in a dry pan on both sides."],
      finish: "Unwrap and crisp in a dry pan for 2 minutes a side, or microwave 60 seconds then air fryer at 200°C for 3 minutes. Hot sauce on the side. 5 min",
      comp: [["H", "Sear the steak",6,"Season, sear hard for 2 to 3 minutes a side, rest, then dice small", "0.25 tsp taco seasoning; 1 pinch salt; 1 pinch garlic granules",["steak"]],
        ["O",200,10,"Turkey rashers, flat on a lined tray",["turkey-rashers"]],
        ["H", "Soft scramble",6,"Whisk, cook low and take it off while still glossy; it finishes when reheated", "1 pinch salt",["eggs","egg-whites"]],
        ["S", "Nacho cheese sauce", "0.5 x light cheese slice; 1 tsp milk; 1 pinch smoked paprika; 1 pinch garlic granules",3],
        ["P", "Fold the diced steak, chopped rashers, cheddar and nacho sauce through the scramble; fill and fold the wraps. Wrap one by one"]] },
    { id: "bf-pocket", slot: "breakfast", name: "Turkey ham breakfast pockets", time: "Batch: 40 min", whole: ["wrap"],
      ing: [["wrap",62], ["eggs",110], ["turkey-ham",55], ["cheddar",35], ["cheese-slice",20], ["milk",10], ["peppers",40], ["onion",20], ["spring-onion",5]],
      method: ["Dice the peppers and onion small and soften in a little oil; brown the diced ham in the same pan.", "Whisk the eggs and cook a thin flat omelette.", "Nacho sauce: tear the cheese slice into the warm milk with the paprika and garlic granules and whisk over a low heat until smooth.", "Lay the omelette on the wrap, add the cheddar, sauce, ham, veg and spring onion, roll tight and crisp in a dry pan."],
      finish: "Unwrap and crisp in a dry pan for 2 minutes a side, or microwave 90 seconds then air fryer at 200°C for 3 minutes. 5 min",
      comp: [["V", "peppers", "diced small"],
        ["V", "onion", "diced small"],
        ["H", "Soften the peppers and onion",8,"A little oil over a medium heat until soft and sweet; brown the diced turkey ham in the same pan at the end", "1 pinch salt",["turkey-ham"]],
        ["H", "Flat omelettes, one at a time",3,"Whisk and cook one thin flat omelette for each pocket", "1 pinch salt; 1 pinch black pepper",["eggs"]],
        ["S", "Nacho cheese sauce", "1 x light cheese slice; 2 tsp milk; 2 pinch smoked paprika; 2 pinch garlic granules",3],
        ["P", "Lay an omelette on each wrap, add the cheddar, nacho sauce, ham, veg and sliced spring onion, and roll tight. Wrap one by one"]] },
    { id: "bf-buffalo", slot: "breakfast", name: "Buffalo chicken bagels", time: "Batch: 35 min", whole: ["thin-bagel"],
      ing: [["chicken-breast",105], ["thin-bagel",45], ["turkey-rashers",50], ["cream-cheese",15], ["cheddar",15], ["franks",30], ["cheese-slice",20], ["spring-onion",5]],
      method: ["Season the chicken and bake at 200°C for 18 minutes; bake the rashers alongside for 10 minutes.", "Chop the chicken and warm it with the cream cheese, cheddar and hot sauce until it just simmers.", "Pile into a toasted bagel with the rashers, cheese slice and sliced spring onion."],
      finish: "Toast the bagel, warm the filling for 60 seconds in the microwave, and build with the rashers, cheese slice and sliced spring onion. 4 min",
      after: {"4": [1]},
      comp: [["M", "dry", "Buffalo chicken seasoning", "chicken-breast", "0.125 tsp salt; 0.25 tsp garlic granules; 0.25 tsp smoked paprika",0],
        ["O",200,18,"Chicken breasts for the buffalo filling",["chicken-breast"]],
        ["O",200,10,"Turkey rashers, flat on a lined tray",["turkey-rashers"]],
        ["V", "spring-onion", "sliced"],
        ["H", "Buffalo chicken filling",5,"Chop the chicken and warm it with the cream cheese, cheddar and hot sauce until it just simmers", "30 g Frank's hot sauce; 15 g light cream cheese; 15 g light cheddar",["chicken-breast"]],
        ["P", "Filling into tubs with the rashers alongside. Bagels, cheese slices and spring onion stay separate until the day"]] },
    { id: "bf-quesadilla", slot: "breakfast", name: "Breakfast quesadilla", time: "Batch: 5 min each", whole: ["wrap"],
      ing: [["wrap",62], ["turkey-ham",70], ["egg-whites",150], ["eggs",50], ["cheddar",30], ["cheese-slice",20], ["spring-onion",10]],
      sea: [["Seasoning", "1 pinch salt; 1 pinch black pepper"]],
      method: ["Crisp the chopped ham in a non-stick pan over a medium heat.", "Pour over the whisked egg and whites; when the top is nearly set, add the cheeses and spring onion and press the wrap on top.", "Lid on for a minute, flip to toast the wrap, then fold in half.", "Two pans at once halves the time for a batch."],
      finish: "Unwrap and crisp in a dry pan for 2 minutes a side, or microwave 60 seconds then air fryer at 200°C for 3 minutes. Hot sauce on the side. 5 min",
      comp: [["H", "Breakfast quesadillas, one at a time",5,"Crisp the chopped ham, pour over the whisked egg, add the cheeses and spring onion when nearly set and press a wrap on; flip to toast, fold in half and cool. Two pans at once halves this", "",["turkey-ham","egg-whites","eggs"]],
        ["P", "Cool flat on a rack, then wrap one by one"]] },
    { id: "bf-burrito", slot: "breakfast", name: "Classic breakfast burrito", time: "Batch: 45 min", whole: ["wrap"],
      ing: [["wrap",62], ["turkey-mince",60], ["turkey-rashers",50], ["egg-whites",150], ["cheddar",40], ["potatoes",75]],
      method: ["Season the mince, press a thin patty and bake at 200°C for 12 minutes with the rashers alongside for 10.", "Cube the potato, boil 5 minutes, steam-dry, then roast at 200°C for 20 minutes until crisp.", "Scramble the egg whites low and soft.", "Chop the patty and rashers, fold through the eggs with the cheddar and potato, and roll tight in the wrap."],
      finish: "Unwrap, microwave 90 seconds, then air fryer at 200°C for 3 minutes. Hot sauce on the side. 5 min",
      comp: [["X", "Spicy turkey patties", "Mix the seasoning through the mince and press thin patties onto a lined tray, one per sandwich or burrito", "0.125 tsp salt; 0.25 tsp garlic granules; 0.25 tsp smoked paprika; 1 pinch chilli flakes; 1 pinch black pepper",["turkey-mince"]],
        ["O",200,12,"Sausage patties, turned once",["turkey-mince","chicken-mince"]],
        ["O",200,10,"Turkey rashers, flat on a lined tray",["turkey-rashers"]],
        ["O",200,20,"Potato cubes, oiled and salted, until crisp",[]],
        ["H", "Soft egg white scramble",6,"Whisk, cook low and take it off while still glossy; it finishes when reheated", "1 pinch salt",["eggs","egg-whites"]],
        ["P", "Chop the patty and rashers, fold through the scramble with the cheddar and potato, and roll tight in the wraps. Wrap one by one"]] },
    { id: "snack", slot: "snack", name: "Yoghurt bowl and an apple", time: "2 min",
      ing: [["greek-yog",300], ["honey",15], ["berries",80], ["granola",40], ["apple",150]],
      method: ["Greek yoghurt with honey, berries and granola.", "An apple on the side, or sliced in."],
      comp: [] },
    { id: "s-choc-mousse", slot: "snack", name: "Chocolate protein mousse", time: "5 min", tag: "Sweet",
      ing: [["skyr",250], ["whey",30], ["cocoa",10], ["honey",10], ["berries",60], ["dark-choc",10]],
      sea: [["Mousse", "250 g skyr; 30 g chocolate whey; 10 g cocoa; 10 g honey"]],
      method: ["Whisk skyr, whey, cocoa and honey until thick and smooth.", "Top with berries and grated dark chocolate. Chill 20 minutes if you can."] },
    { id: "s-brownie", slot: "snack", name: "Protein brownies with yoghurt", time: "Batch: 25 min", tag: "Sweet",
      ing: [["oats",30], ["whey",30], ["cocoa",12], ["eggs",25], ["honey",15], ["dark-choc",10], ["greek-yog",200], ["berries",60], ["milk",30]],
      method: ["Blitz oats to flour; mix with whey, cocoa, egg, honey and a splash of milk to a thick batter.", "Fold in chopped dark chocolate; bake in a lined tin at 180°C for 15–18 minutes, still fudgy in the middle.", "Two squares per serving with Greek yoghurt and berries."],
      finish: "Two squares with Greek yoghurt and berries. 1 min",
      comp: [["T", "Protein brownie batter", "Blitz the oats to flour, mix everything to a thick batter, fold in the chopped chocolate, spread in a lined tin", "30 g oats; 30 g chocolate whey; 12 g cocoa; 0.5 x egg; 15 g honey; 10 g dark chocolate; 1 pinch baking powder; 2 tbsp milk"],
        ["O",180,16,"Protein brownies (still fudgy in the middle); cool and cut into squares"]] },
    { id: "s-cheesecake", slot: "snack", name: "Berry cheesecake pot", time: "5 min", tag: "Sweet",
      ing: [["skyr",200], ["cream-cheese",30], ["whey",30], ["honey",10], ["berries",80], ["digestives",15]],
      sea: [["Filling", "200 g skyr; 30 g light cream cheese; 30 g vanilla whey; 10 g honey; 0.25 tsp vanilla extract"]],
      method: ["Crush a digestive into the bottom of a jar.", "Whisk skyr, cream cheese, whey and honey; spoon over.", "Top with berries."] },
    { id: "s-bark", slot: "snack", name: "Frozen yoghurt bark", time: "Batch: 10 min + freezing", tag: "Sweet",
      ing: [["greek-yog",300], ["honey",15], ["berries",80], ["dark-choc",15], ["granola",20]],
      sea: [["Flavouring", "0.25 tsp vanilla extract"]],
      method: ["Mix yoghurt and honey; spread 1 cm thick on a lined tray.", "Scatter berries, granola and chopped dark chocolate; freeze 3 hours.", "Snap into shards."],
      finish: "Snap off a portion. 0 min",
      comp: [["T", "Yoghurt bark", "Mix the yoghurt and honey, spread 1 cm thick on a lined tray, scatter berries, granola and chopped chocolate; freeze 3 hours, then snap and bag", "300 g greek yoghurt; 15 g honey; 80 g berries; 20 g granola; 15 g dark chocolate"]] },
    { id: "s-crumble", slot: "snack", name: "Apple crumble pot with vanilla yoghurt", time: "Batch: 20 min", tag: "Sweet",
      ing: [["apple",150], ["honey",10], ["oats",30], ["peanut-butter",10], ["greek-yog",250], ["whey",30]],
      method: ["Dice the apple and microwave with cinnamon and half the honey for 2 minutes.", "Crumble: oats, peanut butter and the rest of the honey, toasted in a dry pan or baked at 180°C for 8 minutes.", "Stir whey (vanilla if you have it) into the yoghurt; layer apple, yoghurt and crumble."],
      finish: "Layer apple, yoghurt and crumble. 2 min",
      comp: [["T", "Crumble topping", "Rub together and spread on a tray", "30 g oats; 10 g peanut butter; 5 g honey; 1 pinch cinnamon"],
        ["O",180,10,"Crumble topping, until golden"],
        ["H", "Cinnamon apple",6,"Dice the apple and cook with the honey, cinnamon and a splash of water for 5 min", "1 x apple; 5 g honey; 0.5 tsp cinnamon"],
        ["T", "Vanilla yoghurt pots", "Stir the whey into the yoghurt", "250 g greek yoghurt; 30 g vanilla whey"]] },
    { id: "s-pbj", slot: "snack", name: "PB and jam rice cakes with yoghurt", time: "3 min", tag: "Sweet",
      ing: [["rice-cakes",32], ["peanut-butter",20], ["jam",20], ["greek-yog",200], ["berries",50]],
      method: ["Spread 4 rice cakes with peanut butter and jam.", "Greek yoghurt with berries on the side."],
      comp: [] },
    { id: "s-cherry-cheesecake", slot: "snack", name: "Cherry crumble cheesecake", time: "Batch: 30 min + chilling", tag: "Sweet",
      ing: [["cream-cheese",50], ["skyr",150], ["eggs",25], ["whey",15], ["honey",20], ["milk",10], ["cherries",60], ["digestives",15]],
      method: ["Blend the cream cheese, skyr, egg, whey, honey, milk and vanilla until smooth.", "Bake in a lined tin at 180°C for about 20 minutes, until just wobbling in the middle. Cool, then chill for 2 hours.", "Simmer the cherries with a little honey until syrupy.", "Spoon the cherries over a slice and crumble the digestive on top."],
      finish: "Cut a slice, spoon over the cherries and crumble the digestive on top. 1 min",
      comp: [["T", "Cheesecake batter", "Blend until smooth and pour into a lined tin; one tin does every cheesecake this week", "50 g light cream cheese; 150 g skyr; 0.5 x egg; 15 g vanilla whey; 15 g honey; 2 tsp milk; 0.25 tsp vanilla extract"],
        ["O",180,20,"Baked cheesecake, until just wobbling in the middle; cool, then chill"],
        ["H", "Cherry compote",5,"Simmer the cherries with the honey until syrupy; cool and box", "60 g frozen cherries; 5 g honey"]] },
    { id: "s-bday-cheesecake", slot: "snack", name: "Birthday cake cheesecake", time: "Batch: 30 min + chilling", tag: "Sweet",
      ing: [["cream-cheese",50], ["skyr",150], ["eggs",25], ["whey",15], ["honey",15], ["milk",15], ["icing-sugar",10]],
      sea: [["Icing", "10 g icing sugar; 1 tsp milk; 1 tsp sprinkles"]],
      method: ["Blend the cream cheese, skyr, egg, whey, honey, milk and vanilla until smooth.", "Bake in a lined tin at 180°C for about 20 minutes, until just wobbling in the middle. Cool, then chill for 2 hours.", "Stir the icing sugar and milk to a thick icing, spread over a slice and finish with sprinkles."],
      finish: "Cut a slice, spread with the icing and finish with sprinkles. 2 min",
      comp: [["T", "Cheesecake batter", "Blend until smooth and pour into a lined tin; one tin does every cheesecake this week", "50 g light cream cheese; 150 g skyr; 0.5 x egg; 15 g vanilla whey; 15 g honey; 2 tsp milk; 0.25 tsp vanilla extract"],
        ["O",180,20,"Baked cheesecake, until just wobbling in the middle; cool, then chill"]] },
    { id: "s-oreo-cheesecake", slot: "snack", name: "Oreo cheesecake", time: "Batch: 30 min + chilling", tag: "Sweet",
      ing: [["cream-cheese",60], ["skyr",180], ["eggs",25], ["whey",15], ["honey",15], ["milk",10], ["oreo",11]],
      sea: [["Topping", "30 g skyr; 10 g light cream cheese; 1 x Oreo; 1 tsp sprinkles"]],
      method: ["Blend the cream cheese, skyr, egg, whey, honey, milk and vanilla until smooth.", "Bake in a lined tin at 180°C for about 20 minutes, until just wobbling in the middle. Cool, then chill for 2 hours.", "Whisk the topping skyr and cream cheese, fold in the crushed Oreo, spread over a slice and finish with sprinkles."],
      finish: "Cut a slice, whisk the topping with the crushed Oreo, spread over and finish with sprinkles. 2 min",
      comp: [["T", "Cheesecake batter", "Blend until smooth and pour into a lined tin; one tin does every cheesecake this week", "50 g light cream cheese; 150 g skyr; 0.5 x egg; 15 g vanilla whey; 15 g honey; 2 tsp milk; 0.25 tsp vanilla extract"],
        ["O",180,20,"Baked cheesecake, until just wobbling in the middle; cool, then chill"]] },
    { id: "s-pretzel", slot: "snack", name: "Pretzel bites with beer cheese", time: "Batch: 30 min", tag: "Savoury",
      ing: [["sr-flour",60], ["skyr",75], ["cottage-cheese",55], ["cheddar",20], ["cream-cheese",15], ["lager",15]],
      method: ["Bring the flour, skyr and salt together into a dough, roll into ropes and cut into 2 cm bites.", "Bake on a lined tray at 200°C for 12 minutes until deep golden.", "Blend the cottage cheese, cheddar, cream cheese, lager and mustard, then stir over a medium heat for 5 minutes until melted and smooth."],
      finish: "Bites back in the air fryer at 200°C for 3 minutes; warm the dip gently. 4 min",
      comp: [["T", "Pretzel dough", "Bring together into a dough, roll into ropes and cut 2 cm bites onto a lined tray", "60 g self-raising flour; 75 g skyr; 1 pinch salt"],
        ["O",200,12,"Pretzel bites, until deep golden"],
        ["S", "Beer cheese dip", "55 g cottage cheese; 20 g light cheddar; 15 g light cream cheese; 1 tbsp lager; 0.5 tsp Dijon mustard",5,true]] },
    { id: "s-brookie", slot: "snack", name: "Brookie", time: "Batch: 30 min", tag: "Sweet",
      ing: [["eggs",50], ["whey",15], ["pb-powder",17], ["cocoa",5], ["oats",10], ["honey",20], ["skyr",40], ["dark-choc",8], ["milk",10]],
      method: ["Blitz the oats to flour and mix with everything except the cocoa and chocolate.", "Split the batter in two and stir the cocoa into one half.", "Marble both into a lined tin, press the chopped chocolate on top and bake at 180°C for about 20 minutes, until just set."],
      finish: "One square, cold or warmed for 20 seconds. 1 min",
      comp: [["T", "Brookie batters", "Blitz the oats to flour, mix everything except the cocoa and chocolate, split in two and stir the cocoa into one half; marble both into a lined tin and press the chopped chocolate on top", "1 x egg; 15 g vanilla whey; 17 g peanut butter powder; 10 g oats; 20 g honey; 40 g skyr; 5 g cocoa; 8 g dark chocolate; 2 tsp milk; 1 pinch salt"],
        ["O",180,20,"Brookie, until just set; cool and cut into squares"]] },
    { id: "s-scoreo", slot: "snack", name: "Cookies and cream thick shake", time: "4 min", tag: "Sweet",
      ing: [["whey",30], ["skyr",100], ["cocoa",10], ["honey",15], ["milk",100], ["oreo",22], ["squirty-cream",15]],
      sea: [["Thickener", "0.5 tsp xanthan gum"]],
      method: ["Blend two big handfuls of ice to snow.", "Add the skyr, whey, half the cocoa, the honey, the xanthan gum and the milk and blend until it holds a spoon.", "Stir the rest of the cocoa with a splash of milk to a sauce.", "Top with the cream, the crushed Oreos and the cocoa sauce."] },
    { id: "s-strawb-shake", slot: "snack", name: "Strawberry thick shake", time: "4 min", tag: "Sweet",
      ing: [["whey",30], ["skyr",100], ["strawberries",90], ["milk",100], ["honey",10], ["squirty-cream",10]],
      sea: [["Thickener", "0.5 tsp xanthan gum"]],
      method: ["Blend two big handfuls of ice to snow.", "Add the skyr, whey, frozen strawberries, honey, xanthan gum and milk and blend until it holds a spoon.", "Top with the cream."] },
    { id: "sh-choc-pb", slot: "shake", name: "Chocolate peanut butter shake", time: "3 min", tag: "Shake",
      ing: [["milk",300], ["skyr",150], ["whey",30], ["cocoa",10], ["peanut-butter",20], ["honey",10], ["dark-choc",5]],
      method: ["Into the blender: milk, skyr, vanilla whey, cocoa, peanut butter, honey and a big handful of ice.", "Blend 30–40 seconds until thick and frothy; grate the dark chocolate on top.", "Stir in your 5 g creatine."] },
    { id: "sh-strawberry", slot: "shake", name: "Berry cheesecake shake", time: "3 min", tag: "Shake",
      ing: [["greek-yog",200], ["milk",200], ["berries",150], ["cream-cheese",20], ["digestives",15], ["honey",10]],
      sea: [["Flavouring", "0.25 tsp vanilla extract"]],
      method: ["Into the blender: yoghurt, milk, frozen berries, cream cheese, honey, a few drops of vanilla and half the digestive.", "Blend until smooth; crumble the rest of the biscuit on top.", "Stir in your 5 g creatine. Optional: 1 scoop vanilla whey for +24 g protein."] },
    { id: "sh-mocha", slot: "shake", name: "Iced mocha shake", time: "4 min", tag: "Shake",
      ing: [["coffee",60], ["milk",250], ["skyr",150], ["whey",30], ["cocoa",8], ["honey",15], ["dark-choc",5]],
      method: ["Make a double espresso or 60 ml strong coffee and let it cool for a minute.", "Into the blender with milk, skyr, vanilla whey, cocoa, honey and a big handful of ice; blend until frothy; grate the chocolate on top.", "Doubles as your pre-gym coffee. Stir in your 5 g creatine."] },
    { id: "sh-lassi", slot: "shake", name: "Mango lassi", time: "3 min", tag: "Shake",
      ing: [["greek-yog",250], ["milk",150], ["mango",150], ["honey",10], ["granola",10]],
      sea: [["Flavouring", "1 pinch ground cardamom; 1 pinch salt"]],
      method: ["Into the blender: yoghurt, milk, frozen mango, honey, a pinch of ground cardamom and a pinch of salt.", "Blend until smooth and thick; a little granola on top for crunch.", "Stir in your 5 g creatine. Optional: 1 scoop vanilla whey."] },
    { id: "sh-berry-oat", slot: "shake", name: "PB and jam oat smoothie", time: "3 min", tag: "Shake",
      ing: [["milk",250], ["skyr",150], ["berries",100], ["oats",30], ["peanut-butter",10], ["jam",15]],
      method: ["Into the blender: oats first, then milk, skyr, frozen berries, peanut butter and jam.", "Blend 45 seconds so the oats go smooth.", "Stir in your 5 g creatine. Optional: 1 scoop vanilla whey."] },
    { id: "l-salmon-poke", slot: "lunch", name: "Salmon poke bowl", time: "15 min", late: "split",
      ing: [["sushi-rice",90], ["sushi-vinegar",15], ["salmon",140], ["edamame",80], ["cucumber",60], ["light-mayo",10], ["sriracha",10], ["soy",15], ["sesame-oil",2.5]],
      method: ["Season warm sushi rice with the vinegar.", "Cube the salmon; sear or roast at 200°C for 10 minutes if not sushi-grade.", "Build with edamame and cucumber; dress with soy and sriracha mayo."],
      finish: "Microwave the rice until steaming, top with the cold salmon and veg, add sauce. 3 min",
      comp: [["V", "cucumber", "half-moons"],
        ["M", "dry", "Salt and soy", "salmon", "0.5 tsp salt; 1 tsp soy",0],
        ["O",200,12,"Salmon fillets, then flake"],
        ["S", "Quick cucumber pickle", "1 tsp rice vinegar; 1 pinch salt",0],
        ["S", "Poke sauce", "10 g light mayo; 10 g sriracha; 10 ml soy; 0.5 tsp sesame oil",0],
        ["P", "rice, flaked salmon, cucumber, edamame; poke sauce pot"]] },
    { id: "l-tuna-poke", slot: "lunch", name: "Tuna poke bowl", time: "10 min", late: "split",
      ing: [["sushi-rice",100], ["sushi-vinegar",15], ["tuna",220], ["edamame",60], ["cucumber",60], ["light-mayo",15], ["sriracha",10], ["soy",10], ["lime",8.1]],
      method: ["Season warm sushi rice with the vinegar.", "Mix drained tuna with light mayo, sriracha and soy.", "Build with edamame and cucumber."],
      finish: "Microwave the rice until steaming, top with tuna and veg. 3 min",
      comp: [["V", "cucumber", "half-moons"],
        ["S", "Quick cucumber pickle", "1 tsp rice vinegar; 1 pinch salt; 1 pinch sugar",0],
        ["S", "Tuna mayo (stir into the drained tuna)", "15 g light mayo; 10 g sriracha; 10 ml soy; 0.125 x lime juice",0],
        ["P", "rice, cucumber, edamame; tuna mayo in a sealed pot (from Thursday, mix it on the day)"]] },
    { id: "l-teriyaki", slot: "lunch", name: "Teriyaki chicken bowl", time: "20 min", late: "freeze",
      ing: [["chicken-thigh",200], ["teriyaki",30], ["sushi-rice",100], ["greens",120], ["furikake",5], ["soy",5], ["garlic",5], ["ginger",5], ["sesame-oil",2.5]],
      sea: [["Greens", "0.5 tsp sesame oil; 1 pinch salt"]],
      method: ["Grill or air-fry thighs at 200°C for 18 minutes, glazing with teriyaki for the last 5.", "Steam or wok the greens.", "Slice over rice; finish with furikake."],
      finish: "Microwave until steaming throughout. 3 min",
      comp: [["V", "greens", "trimmed and halved"],
        ["M", "wet", "Teriyaki", "chicken-thigh", "15 ml teriyaki; 5 ml soy; 1 clove garlic; 1 tsp grated ginger",30],
        ["O",200,18,"Teriyaki thighs (brush with 15 ml more teriyaki per portion for the last 5 min), then slice"],
        ["H", "Steam the greens",5,"Steam 3 min, toss with a few drops of sesame oil and a pinch of salt"],
        ["P", "rice, sliced teriyaki chicken, greens; furikake in a twist of foil"]] },
    { id: "l-bulgogi", slot: "lunch", name: "Beef bulgogi bowl", time: "15 min", late: "freeze",
      ing: [["beef-mince",180], ["gochujang",20], ["soy",15], ["honey",5], ["garlic",5], ["sesame-oil",5], ["sushi-rice",100], ["kimchi",60], ["ginger",5], ["spring-onion",15]],
      sea: [["To finish", "1 x spring onion"]],
      method: ["Brown the mince hard in a dry pan.", "Add garlic, gochujang, soy and honey; reduce until sticky.", "Finish with sesame oil; serve over rice with kimchi."],
      finish: "Microwave until steaming, kimchi on top. 3 min",
      comp: [["S", "Bulgogi sauce", "1 clove garlic; 1 tsp grated ginger; 20 g gochujang; 15 ml soy; 5 g honey; 5 ml sesame oil",0],
        ["H", "Bulgogi mince",15,"Brown the mince hard in a dry pan in batches, add the bulgogi sauce, cook down until sticky"],
        ["P", "rice, bulgogi mince; kimchi in a separate pot"]] },
    { id: "l-prawn-egg", slot: "lunch", name: "Prawn and egg rice bowl", time: "10 min", late: "no",
      ing: [["prawns",150], ["eggs",100], ["sushi-rice",100], ["edamame",60], ["soy",10], ["light-mayo",10], ["furikake",5], ["sesame-oil",2.5], ["sriracha",5]],
      method: ["Jammy eggs: 7 minutes, then iced water.", "Toss prawns with soy.", "Build over rice with edamame, a little mayo and furikake."],
      finish: "Microwave the rice until steaming, add the cold prawns, halved eggs, mayo and furikake. 2 min",
      comp: [["H", "Boil eggs",12,"Boil 7 min, into iced water, peel"],
        ["S", "Prawn dressing (toss the prawns in it)", "10 ml soy; 0.5 tsp sesame oil; 1 pinch chilli flakes",0],
        ["S", "Sriracha mayo", "10 g light mayo; 1 tsp sriracha",0],
        ["P", "rice, edamame; dressed prawns and halved eggs in a separate tub; sriracha mayo pot"]] },
    { id: "l-shawarma", slot: "lunch", name: "Chicken shawarma bowl", time: "25 min", late: "split",
      ing: [["chicken-thigh",200], ["olive-oil",5], ["jasmine-rice",90], ["greek-yog",60], ["tahini",8], ["gherkins",30], ["cucumber",60], ["tomato",60], ["lemon",38], ["parsley",5]],
      sea: [["Salad pot", "5 g fresh parsley"]],
      method: ["Marinate thighs in shawarma spice, garlic, lemon and a little oil.", "Roast at 220°C for 20 minutes; rest and slice.", "Serve over rice with pickles, salad and tahini yoghurt."],
      finish: "Microwave chicken and rice until steaming, add the cold salad and sauce. 3 min",
      comp: [["V", "cucumber", "diced"],
        ["V", "tomato", "diced"],
        ["V", "gherkins", "sliced"],
        ["M", "yog", "Shawarma", "chicken-thigh", "30 g greek yoghurt; 1 tsp cumin; 1 tsp smoked paprika; 0.5 tsp turmeric; 0.5 tsp cinnamon; 0.5 tsp garlic granules; 0.25 x lemon juice; 0.5 tsp salt; 5 ml olive oil",60],
        ["O",220,20,"Shawarma thighs, rest and slice"],
        ["S", "Tahini yoghurt", "30 g greek yoghurt; 8 g tahini; 0.125 x lemon juice; 1 pinch salt",0],
        ["P", "rice, shawarma chicken; cucumber, tomato and pickle pot; tahini yoghurt pot"]] },
    { id: "l-spicy-salmon", slot: "lunch", name: "Spicy salmon rice bowl", time: "15 min", late: "split",
      ing: [["salmon",140], ["sushi-rice",100], ["sushi-vinegar",10], ["light-mayo",15], ["sriracha",15], ["cucumber",60], ["edamame",50], ["furikake",5], ["soy",5]],
      method: ["Roast salmon at 200°C for 12 minutes and flake.", "Mix with light mayo and sriracha.", "Serve over seasoned rice with cucumber, edamame and furikake."],
      finish: "Microwave the rice until steaming, top with the salmon mix. 2 min",
      comp: [["V", "cucumber", "sliced"],
        ["M", "dry", "Salt and pepper", "salmon", "0.5 tsp salt; 0.25 tsp black pepper",0],
        ["O",200,12,"Salmon fillets, then flake into the spicy mayo"],
        ["S", "Spicy mayo", "15 g light mayo; 15 g sriracha; 5 ml soy",0],
        ["P", "seasoned rice, spicy salmon, cucumber, edamame; furikake on top"]] },
    { id: "l-onigiri", slot: "lunch", name: "Tuna-mayo onigiri and edamame", time: "15 min", late: "no",
      ing: [["sushi-rice",120], ["tuna",150], ["light-mayo",20], ["furikake",5], ["edamame",100], ["sushi-vinegar",15], ["soy",5]],
      sea: [["Rice seasoning", "15 ml rice vinegar; 1 pinch salt"], ["Tuna filling", "20 g light mayo; 5 ml soy"]],
      method: ["Mix tuna with light mayo.", "Shape 3 rice triangles around the filling with wet, salted hands.", "Roll edges in furikake; edamame on the side."],
      finish: "Eat cold. 0 min",
      comp: [] },
    { id: "l-thai-beef-salad", slot: "lunch", name: "Thai beef salad", time: "15 min", tag: "Spicy", late: "no",
      ing: [["steak",160], ["rice-noodles",60], ["lettuce",80], ["cucumber",80], ["tomato",60], ["onion",20], ["lime",33], ["fish-sauce",15], ["honey",5], ["peanuts",10], ["chilli",7.5], ["garlic",2.5], ["mint",5], ["coriander",5]],
      sea: [["Herbs", "5 g fresh mint; 5 g fresh coriander"]],
      method: ["Sear the steak hard, rest and slice thin.", "Dressing: lime juice, fish sauce, honey, chilli and garlic.", "Toss noodles, leaves, cucumber, tomato, red onion, mint and coriander with the beef; top with crushed peanuts."],
      finish: "Toss everything with the dressing, peanuts on top. 2 min",
      comp: [["V", "cucumber", "batons"],
        ["V", "tomato", "wedges"],
        ["V", "onion", "thinly sliced (red)"],
        ["V", "lettuce", "torn"],
        ["M", "dry", "Salt and pepper", "steak", "0.5 tsp salt; 0.25 tsp black pepper",0],
        ["H", "Sear the salad steak",10,"Ripping-hot pan, 2 min a side, rest 5 min, slice thin"],
        ["S", "Thai dressing", "0.5 x lime juice; 15 ml fish sauce; 5 g honey; 0.5 x red chilli; 0.5 clove garlic",0],
        ["P", "noodles, sliced beef, veg, mint and coriander; dressing jar; crushed peanuts in a bag"]] },
    { id: "l-caesar", slot: "lunch", name: "Chicken Caesar salad", time: "15 min", late: "split",
      ing: [["chicken-breast",180], ["lettuce",120], ["sourdough",45], ["parmesan",15], ["greek-yog",50], ["light-mayo",10], ["garlic",5], ["olive-oil",5], ["lemon",25]],
      method: ["Grill the chicken and slice.", "Cube the sourdough and bake at 200°C for 8 minutes for croutons.", "Dressing: yoghurt, light mayo, garlic, lemon, parmesan and a little anchovy if you like.", "Toss with cos lettuce; dressing on the day."],
      finish: "Toss lettuce, chicken and dressing, croutons and the rest of the parmesan on top. 2 min",
      comp: [["V", "lettuce", "washed, dried and chopped"],
        ["M", "dry", "Lemon and herb rub", "chicken-breast", "5 ml olive oil; 0.5 tsp garlic granules; 0.5 tsp dried oregano; 0.5 tsp salt; 0.25 x lemon zest",0],
        ["O",200,18,"Caesar chicken (74°C inside), rest and slice"],
        ["O",200,8,"Croutons: cubed sourdough, oil spray, pinch of salt and garlic granules"],
        ["S", "Caesar dressing", "50 g greek yoghurt; 10 g light mayo; 1 clove garlic; 1 tsp Dijon mustard; 0.25 x lemon juice; 0.5 tsp Worcestershire; 1 tbsp grated parmesan",0],
        ["P", "lettuce, sliced chicken; dressing jar; croutons in a bag"]] },
    { id: "l-satay-noodle", slot: "lunch", name: "Satay chicken noodle salad", time: "20 min", tag: "Asian", late: "no",
      ing: [["chicken-breast",170], ["rice-noodles",70], ["peanut-butter",20], ["soy",15], ["lime",22], ["honey",5], ["sriracha",5], ["cucumber",60], ["peppers",60], ["beansprouts",50], ["garlic",2.5], ["ginger",5]],
      sea: [["Poaching water", "1 tsp grated ginger"]],
      method: ["Poach or grill the chicken; shred.", "Satay: peanut butter, soy, lime, honey, sriracha and hot water to loosen.", "Toss cold noodles, veg and chicken with the sauce."],
      finish: "Toss everything with the sauce, cold. Coriander if you have it. 2 min",
      comp: [["V", "cucumber", "julienned"],
        ["V", "peppers", "julienned"],
        ["H", "Poach the satay chicken",15,"Simmering water with a slice of ginger, 12 min; cool and shred"],
        ["S", "Satay sauce", "20 g peanut butter; 15 ml soy; 0.33 x lime juice; 5 g honey; 5 g sriracha; 0.5 clove garlic; 2 tbsp hot water",0],
        ["P", "noodles, shredded chicken, veg, beansprouts; satay jar"]] },
    { id: "l-prawn-mango", slot: "lunch", name: "Prawn, mango and avocado bowl", time: "10 min", tag: "Spicy", late: "no",
      ing: [["prawns",200], ["jasmine-rice",50], ["mango",100], ["avocado",40], ["lettuce",60], ["cucumber",60], ["lime",22], ["sriracha",10], ["honey",5], ["coriander",5]],
      sea: [["To finish", "5 g fresh coriander"]],
      method: ["Rice in the base.", "Prawns, mango, cucumber and leaves on top.", "Dress with lime, sriracha and honey; add avocado on the day so it doesn't brown."],
      finish: "Microwave the rice until steaming, add prawns, mango, avocado and dressing. 3 min",
      comp: [["V", "mango", "diced"],
        ["V", "cucumber", "diced"],
        ["V", "lettuce", "shredded"],
        ["S", "Lime and chilli dressing", "0.33 x lime juice; 10 g sriracha; 5 g honey; 1 pinch salt",0],
        ["P", "rice; prawns, mango, cucumber and lettuce; dressing jar; avocado stays whole until the day"]] },
    { id: "l-spicy-tuna-salad", slot: "lunch", name: "Spicy tuna rice salad", time: "10 min", tag: "Spicy", late: "split",
      ing: [["tuna",200], ["sushi-rice",60], ["sushi-vinegar",10], ["light-mayo",15], ["sriracha",15], ["lettuce",60], ["edamame",80], ["cucumber",60], ["furikake",5], ["lime",8.1]],
      method: ["Season the rice with sushi vinegar.", "Mix tuna with light mayo and sriracha.", "Build over leaves with edamame and cucumber; finish with furikake."],
      finish: "Mix the tuna with the sauce, build over the leaves and warm rice, furikake on top. 3 min",
      comp: [["V", "cucumber", "sliced"],
        ["V", "lettuce", "shredded"],
        ["S", "Sriracha mayo (stir into the tuna on the day)", "15 g light mayo; 15 g sriracha; 0.125 x lime juice",0],
        ["P", "seasoned rice, leaves, edamame, cucumber; sauce pot"]] },
    { id: "l-green-curry", slot: "lunch", name: "Thai green chicken curry", time: "25 min", tag: "Thai", late: "freeze", kind: "curry",
      ing: [["chicken-thigh",200], ["green-curry-paste",30], ["coconut-light",150], ["peppers",60], ["broccoli",60], ["fish-sauce",10], ["lime",16], ["jasmine-rice",80], ["basil",5]],
      sea: [["To finish", "5 g fresh basil"]],
      method: ["Fry the paste for a minute; add sliced thighs and seal.", "Pour in the coconut milk and a splash of water; simmer 12 minutes with the veg.", "Season with fish sauce and lime; basil if you have it. Serve with rice."],
      finish: "Microwave until steaming. 5 min",
      comp: [["V", "peppers", "sliced"],
        ["V", "broccoli", "small florets"],
        ["H", "Thai green curry",20,"Fry the paste 1 min, seal the sliced thighs, add the coconut milk and water, simmer 10 min with the veg, then season", "30 g green curry paste; 150 ml light coconut milk; 50 ml water; 10 ml fish sauce; 0.25 x lime juice; 1 pinch sugar"],
        ["P", "rice, green curry"]] },
    { id: "l-tikka", slot: "lunch", name: "Chicken tikka masala (lighter)", time: "35 min", tag: "Curry", late: "freeze", kind: "curry",
      after: {"3": [2]},
      ing: [["chicken-breast",200], ["greek-yog",60], ["curry-paste",25], ["onion",50], ["garlic",10], ["passata",120], ["coconut-light",60], ["jasmine-rice",80], ["lemon",25], ["ginger",5], ["coriander",5]],
      sea: [["To finish", "5 g fresh coriander"]],
      method: ["Marinate the chicken in yoghurt and half the paste; grill or air-fry at 220°C for 12 minutes.", "Soften onion and garlic, fry the rest of the paste, add passata and coconut milk; simmer 10 minutes.", "Blend smooth if you like, add the chicken. Serve with basmati."],
      finish: "Microwave until steaming, coriander on top. 5 min",
      comp: [["V", "onion", "finely diced"],
        ["M", "yog", "Tikka", "chicken-breast", "40 g greek yoghurt; 12 g curry paste; 1 clove garlic; 0.25 x lemon juice; 0.5 tsp salt",60],
        ["O",220,12,"Tikka chicken"],
        ["H", "Tikka masala sauce",20,"Soften the onion with the garlic and ginger, fry the paste 1 min, add passata and coconut milk, simmer 10 min, blend smooth, stir in the chicken and garam masala", "1 clove garlic; 1 tsp grated ginger; 13 g curry paste; 120 g passata; 60 ml light coconut milk; 0.5 tsp garam masala"],
        ["P", "rice, tikka masala"]] },
    { id: "l-jalfrezi", slot: "lunch", name: "Chicken jalfrezi", time: "30 min", tag: "Curry", late: "freeze", kind: "curry",
      ing: [["chicken-breast",200], ["curry-paste",25], ["onion",80], ["peppers",100], ["chopped-tom",150], ["olive-oil",5], ["jasmine-rice",80], ["garlic",5], ["ginger",5], ["chilli",15], ["coriander",5]],
      sea: [["To finish", "5 g fresh coriander"]],
      method: ["Fry chunky onion and peppers hot so they char a little; set aside.", "Fry the paste, brown the chicken, add tomatoes and green chilli.", "Simmer 12 minutes, return the veg. Serve with basmati."],
      finish: "Microwave until steaming, coriander on top. 5 min",
      comp: [["V", "onion", "chunks"],
        ["V", "peppers", "chunks"],
        ["H", "Jalfrezi",25,"Char the onion and peppers in a hot pan, set aside; fry the paste with garlic, ginger and chilli, brown the chicken, add the tomatoes, simmer 12 min, return the veg", "25 g curry paste; 1 clove garlic; 1 tsp grated ginger; 1 x green chilli; 150 g chopped tomatoes; 0.5 tsp garam masala; 0.5 tsp salt"],
        ["P", "rice, jalfrezi"]] },
    { id: "l-katsu-curry", slot: "lunch", name: "Chicken katsu curry", time: "35 min", tag: "Fakeaway", late: "freeze", kind: "curry",
      ing: [["chicken-breast",200], ["eggs",25], ["panko",30], ["olive-oil",5], ["curry-paste",20], ["onion",50], ["coconut-light",80], ["jasmine-rice",80], ["honey",7], ["garlic",5], ["ginger",5]],
      method: ["Flatten the breast, egg and panko; air-fry at 200°C for 12–14 minutes.", "Sauce: soften onion and carrot, add katsu paste and coconut milk with water; simmer and blend.", "Slice the chicken over rice and pour the sauce alongside."],
      finish: "Air-fry the chicken from frozen at 200°C for 18 min; reheat the sauce and rice. 20 min hands-off",
      comp: [["V", "onion", "diced"],
        ["B", "chicken-breast", "panko", "0.5 tsp salt; 0.25 tsp black pepper"],
        ["S", "Katsu sauce (soften the onion first, then simmer and blend)", "20 g curry paste; 1 tsp honey; 1 clove garlic; 1 tsp grated ginger; 80 ml light coconut milk; 100 ml water",10,true],
        ["P", "breaded chicken (freeze raw); katsu sauce; rice"]] },
    { id: "d-pad-thai", slot: "dinner", name: "Prawn and chicken pad thai", time: "25 min", tag: "Thai", type: "fresh",
      ing: [["rice-noodles",80], ["prawns",120], ["chicken-breast",80], ["eggs",50], ["beansprouts",80], ["onion",30], ["soy",15], ["fish-sauce",10], ["honey",10], ["lime",22], ["peanuts",10], ["sushi-vinegar",5]],
      sea: [["Sauce", "10 ml fish sauce; 15 ml soy; 10 g honey; 0.33 x lime juice; 1 tsp rice vinegar; 0.25 tsp chilli flakes"], ["Seasoning", "0.25 tsp salt"]],
      method: ["Soak the noodles 5 minutes in boiling water; mix the sauce.", "Season and pan-fry the sliced chicken; add the prawns for 2 minutes, push aside and scramble the egg.", "Add the sliced onion, noodles and sauce; toss with the beansprouts.", "Crushed peanuts and a wedge of lime on top."] },
    { id: "d-thai-basil", slot: "dinner", name: "Thai basil beef with a fried egg", time: "20 min", tag: "Thai", type: "fresh",
      ing: [["beef-mince",180], ["garlic",10], ["peppers",60], ["soy",15], ["fish-sauce",10], ["honey",5], ["eggs",50], ["jasmine-rice",80], ["chilli",15], ["basil",10]],
      sea: [["Aromatics", "2 clove garlic; 1 x red chilli"], ["Sauce", "15 ml soy; 10 ml fish sauce; 5 g honey"], ["To finish", "10 g fresh basil"]],
      method: ["Rice on.", "Pound the garlic with the chilli; fry in a hot wok 30 seconds, add the mince and brown hard.", "Add the sliced peppers and the sauce; cook until sticky, then stir in the basil.", "Fry an egg until the edges crisp and put it on top."] },
    { id: "d-peri-peri", slot: "dinner", name: "Peri-peri chicken and spicy rice", time: "25 min on the day", tag: "Fakeaway", type: "head",
      ing: [["chicken-thigh",220], ["peri-peri",30], ["jasmine-rice",70], ["peppers",60], ["corn",80], ["greek-yog",40], ["lemon",38], ["garlic",7.5]],
      sea: [["Spicy rice", "0.5 tsp smoked paprika; 0.25 tsp turmeric; 0.5 tsp garlic granules; 0.5 x stock cube"]],
      method: ["Coat the thighs in the peri-peri marinade; an hour is good, overnight is better.", "Cook the rice with the spicy rice seasoning and the diced peppers.", "Air-fry or grill the thighs at 200°C for 18–20 minutes.", "Stir the garlic dip together; warm the corn."],
      finish: "Rice on, cooked with ½ tsp smoked paprika, ¼ tsp turmeric, ½ tsp garlic granules, the diced peppers and ½ stock cube. Air-fry or grill the thighs at 200°C for 18–20 min. Warm the corn; dip on the side. 25 min",
      comp: [["M", "wet", "Peri-peri", "chicken-thigh", "30 g peri-peri sauce; 0.25 x lemon juice; 1 clove garlic; 0.5 tsp smoked paprika",60],
        ["S", "Garlic dip", "40 g greek yoghurt; 0.5 clove garlic; 0.125 x lemon juice; 1 pinch salt",0],
        ["P", "raw peri-peri thighs in their marinade, bagged flat; garlic dip pot"]] },
    { id: "d-burrito-bowl", slot: "dinner", name: "Chicken burrito bowl", time: "25 min on the day", tag: "Spicy", type: "head",
      ing: [["chicken-breast",180], ["jasmine-rice",70], ["kidney-beans",80], ["corn",60], ["salsa",60], ["lettuce",40], ["greek-yog",40], ["mozzarella",20], ["lime",16], ["coriander",5]],
      sea: [["Beans, corn and lime rice", "0.125 x lime juice; 1 pinch cumin; 1 pinch salt; 5 g fresh coriander"]],
      method: ["Rub the chicken with the burrito spice. Rice on.", "Air-fry or grill the chicken at 200°C for 18 minutes; rest and slice.", "Warm the beans and corn with the cumin and salt; stir the lime and chopped coriander through the rice.", "Build with shredded lettuce, salsa, yoghurt and cheese."],
      finish: "Rice on. Air-fry or grill the chicken at 200°C for 18 min, rest and slice. Warm the beans and corn with a pinch of cumin and salt. Stir the zest and juice of ¼ lime and chopped coriander through the rice. Build with shredded lettuce, salsa, yoghurt and cheese. 25 min",
      comp: [["M", "dry", "Burrito spice", "chicken-breast", "1 tsp smoked paprika; 0.5 tsp cumin; 0.5 tsp chilli powder; 0.5 tsp garlic granules; 0.25 tsp dried oregano; 0.5 tsp salt; 0.125 x lime juice",0],
        ["P", "spice-rubbed raw chicken, bagged flat"]] },
    { id: "d-chilli", slot: "dinner", name: "Beef chilli con carne", time: "5 min on the day", tag: "Spicy", type: "sunday",
      ing: [["beef-mince",180], ["kidney-beans",100], ["chopped-tom",200], ["onion",60], ["peppers",60], ["garlic",5], ["jasmine-rice",70], ["greek-yog",40], ["dark-choc",5]],
      method: ["Brown the mince; soften onion, peppers and garlic.", "Add cumin, smoked paprika and chilli; tomatoes and beans.", "Simmer 30 minutes. Rice and a spoon of yoghurt."],
      finish: "Microwave until steaming, yoghurt on top. 5 min",
      comp: [["V", "onion", "diced"],
        ["V", "peppers", "diced"],
        ["L", "Chilli con carne", "hob",40,"1 clove garlic; 1 tsp cumin; 1 tsp smoked paprika; 0.5 tsp chilli powder; 0.5 tsp dried oregano; 0.25 tsp cinnamon; 1 tsp tomato purée; 100 ml beef stock; 0.5 tsp salt; 5 g dark chocolate", "Brown the mince hard, soften the onion, peppers and garlic, add the spices and purée, then tomatoes, stock and beans; simmer 30 min, stir in the chocolate"],
        ["P", "rice, chilli; yoghurt pot"]] },
    { id: "l-massaman", slot: "lunch", name: "Beef massaman curry", time: "Sunday batch", tag: "Thai", late: "freeze", kind: "curry",
      ing: [["beef-shin",180], ["potatoes",150], ["coconut-light",120], ["curry-paste",25], ["onion",50], ["peanuts",10], ["jasmine-rice",50], ["fish-sauce",5], ["honey",7]],
      method: ["Brown the beef; fry the paste.", "Add coconut milk, water, onion and a little fish sauce and sugar; simmer low for 1½ hours.", "Add potato chunks for the last 30 minutes. Peanuts on top; a small portion of rice."],
      finish: "Microwave until steaming, peanuts on top. 5 min",
      comp: [["V", "onion", "sliced"],
        ["V", "potatoes", "chunks"],
        ["L", "Beef massaman", "ip",40,"25 g curry paste; 120 ml light coconut milk; 150 ml water; 5 ml fish sauce; 1 tsp honey; 1 x cinnamon stick; 1 x bay leaf", "Brown the beef on Sauté, fry the paste, add everything except the potatoes, pressure-cook 25 min, add the potatoes and pressure-cook 8 min more"],
        ["P", "rice, massaman; peanuts in a bag"]] },
    { id: "d-ragu", slot: "dinner", name: "Beef ragù pappardelle", time: "15 min on the day", tag: "Italian", type: "sunday",
      ing: [["beef-shin",180], ["onion",60], ["garlic",5], ["passata",200], ["olive-oil",5], ["pasta",100], ["parmesan",15]],
      method: ["Brown the shin in batches; soften onion and garlic.", "Add passata and a splash of stock; cook low for 3 hours (or 50 minutes in a pressure cooker).", "Shred and reduce. Toss with pappardelle, pasta water and parmesan."],
      finish: "Reheat the ragù until piping hot, toss with the pasta, a splash of water and parmesan. 6 min",
      comp: [["V", "onion", "finely diced"],
        ["L", "Beef ragù", "ip",50,"1 clove garlic; 1 tsp tomato purée; 200 g passata; 100 ml beef stock; 1 x bay leaf; 0.5 tsp dried oregano; 0.5 tsp salt", "Brown the shin in batches on Sauté, soften the onion and garlic, add everything else, pressure-cook 50 min, shred, reduce on Sauté until thick"],
        ["P", "ragù; pasta"]] },
    { id: "d-chicken-parm", slot: "dinner", name: "Chicken parmigiana", time: "25 min on the day", tag: "Italian", type: "head",
      ing: [["chicken-breast",200], ["eggs",25], ["panko",30], ["olive-oil",5], ["passata",120], ["mozzarella",50], ["parmesan",10], ["pasta",90], ["garlic",2.5]],
      method: ["Butterfly and flatten the breast; egg and panko.", "Air-fry at 200°C for 12 minutes, spritzed with the oil.", "Top with seasoned passata, mozzarella and parmesan; 3 more minutes.", "Serve with spaghetti tossed in the rest of the sauce."],
      finish: "Pasta on. Air-fry the chicken from frozen at 200°C for 18 min; spoon over a third of the marinara, mozzarella and parmesan on top, 3 min more. Toss the pasta in the rest of the sauce. 25 min",
      comp: [["B", "chicken-breast", "panko", "1 tsp dried oregano; 1 tbsp grated parmesan; 0.5 tsp garlic granules; 0.5 tsp salt"],
        ["S", "Marinara", "120 g passata; 0.5 clove garlic; 0.5 tsp dried oregano; 1 pinch chilli flakes; 1 pinch salt",10],
        ["P", "breaded chicken (freeze raw); marinara pot"]] },
    { id: "d-gyros", slot: "dinner", name: "Chicken gyros wrap and fries", time: "25 min on the day", type: "head",
      ing: [["chicken-thigh",200], ["greek-yog",60], ["wrap",62], ["potatoes",250], ["olive-oil",5], ["onion",30], ["lettuce",30], ["tomato",50], ["lemon",25], ["garlic",7.5], ["cucumber",30]],
      method: ["Mix the gyros marinade and coat the thighs; an hour is good, overnight is better.", "Cut the chips, toss in the oil and salt, air-fry at 200°C for 20 minutes; add the thighs for the last 18 (or grill them).", "Stir the tzatziki together. Slice the red onion, tomato and lettuce.", "Slice the chicken and build the wrap with tzatziki, salad and a few chips."],
      finish: "Cut the chips and air-fry at 200°C for 20 min; add the thighs for the last 18 min (or grill them). Slice the red onion, tomato and lettuce; slice the chicken and build the wrap with tzatziki and a few chips. 25 min",
      comp: [["M", "yog", "Gyros", "chicken-thigh", "30 g greek yoghurt; 0.25 x lemon juice; 1 clove garlic; 1 tsp dried oregano; 1 tsp smoked paprika; 0.5 tsp cumin; 0.5 tsp salt; 5 ml olive oil",60],
        ["S", "Tzatziki", "30 g greek yoghurt; 30 g cucumber, grated and squeezed; 0.5 clove garlic; 1 pinch dried mint; 1 pinch salt",0],
        ["P", "raw gyros thighs in their marinade, bagged flat; tzatziki pot"]] },
    { id: "d-smash", slot: "dinner", name: "Smash burgers and fries", time: "30 min", tag: "Fakeaway", type: "fresh",
      ing: [["beef-mince",180], ["cheese-slice",20], ["brioche",60], ["light-mayo",10], ["ketchup",10], ["gherkins",20], ["lettuce",20], ["onion",20], ["potatoes",250], ["olive-oil",5]],
      sea: [["Burger sauce", "10 g light mayo; 10 g ketchup; 1 tsp American mustard; 1 pinch smoked paprika"], ["Seasoning", "0.5 tsp salt; 0.25 tsp black pepper"]],
      method: ["Cut the chips, toss in the oil and a little salt, air-fry at 200°C for 20 minutes.", "Mix the burger sauce with a teaspoon of chopped gherkin and a splash of its brine. Slice the onion very thin.", "Roll two balls of mince per burger; smash each on a ripping-hot dry pan, season, 2 minutes, flip, cheese on, 1 minute.", "Build in a toasted bun with lettuce, gherkins, onion and sauce."] },
    { id: "d-crispy-burger", slot: "dinner", name: "Crispy chicken burger and fries", time: "25 min on the day", tag: "Fakeaway", type: "head",
      ing: [["chicken-breast",200], ["eggs",25], ["panko",30], ["brioche",60], ["light-mayo",15], ["sriracha",5], ["lettuce",30], ["potatoes",250], ["olive-oil",5], ["lime",8.1]],
      method: ["Butterfly the breast; egg and panko with paprika and garlic salt.", "Air-fry at 200°C for 12–14 minutes, spritzed with oil.", "Air-fry chips alongside.", "Bun with sriracha mayo and lettuce."],
      finish: "Cut the chips, toss in the oil and salt; air-fry with the chicken (from frozen) at 200°C for 20 min. Toast the bun, shred the lettuce, build with the sriracha mayo. 25 min",
      comp: [["B", "chicken-breast", "panko", "0.5 tsp smoked paprika; 0.5 tsp garlic granules; 0.25 tsp cayenne; 0.5 tsp salt"],
        ["S", "Sriracha mayo", "15 g light mayo; 5 g sriracha; 0.125 x lime juice",0],
        ["P", "breaded chicken (freeze raw); sriracha mayo pot"]] },
    { id: "d-philly", slot: "dinner", name: "Philly cheesesteak and fries", time: "30 min", tag: "Fakeaway", type: "fresh",
      ing: [["steak",180], ["onion",60], ["peppers",60], ["cheese-slice",40], ["sub-roll",90], ["potatoes",150], ["olive-oil",5]],
      sea: [["Seasoning", "0.5 tsp salt; 0.25 tsp black pepper; 0.5 tsp Worcestershire"]],
      method: ["Chips into the air fryer with the oil and a little salt, 200°C for 20 minutes.", "Slice the onion and peppers and cook in a little oil with a pinch of the salt for 12 minutes until soft and sweet.", "Slice the steak as thin as you can (20 minutes in the freezer first helps); flash-fry 2 minutes with the veg and the rest of the seasoning.", "Lay the cheese over to melt and pile into the toasted roll."] },
    { id: "d-fried-rice", slot: "dinner", name: "Chicken fried rice", time: "25 min", tag: "Fakeaway", type: "fresh",
      ing: [["chicken-breast",180], ["jasmine-rice",90], ["eggs",100], ["peas",60], ["onion",30], ["soy",20], ["sesame-oil",7]],
      sea: [["Seasoning", "0.5 tsp salt; 0.25 tsp white pepper; 20 ml soy; 7 ml sesame oil"]],
      method: ["Cook the rice first, spread it on a tray and let it steam dry (day-old rice is better still).", "Wok the diced chicken hard with the salt and white pepper; push aside and scramble the eggs.", "Add the rice, peas and chopped onion; season with the soy and sesame oil."] },
    { id: "d-beef-broccoli", slot: "dinner", name: "Beef and broccoli stir-fry", time: "25 min", tag: "Fakeaway", type: "fresh",
      ing: [["steak",180], ["broccoli",150], ["soy",21], ["cornflour",8], ["honey",10], ["garlic",5], ["jasmine-rice",90], ["sesame-oil",5], ["ginger",5]],
      sea: [["Steak coating", "4 g cornflour; 0.5 tsp soy; 1 pinch salt"], ["Sauce", "18 ml soy; 10 g honey; 1 clove garlic; 1 tsp grated ginger; 4 g cornflour; 60 ml water"], ["To finish", "5 ml sesame oil"]],
      method: ["Rice on.", "Slice the steak thin and toss in the steak coating; sear in batches in a very hot wok.", "Blanch the broccoli 2 minutes.", "Simmer the sauce until glossy, toss everything together and finish with the sesame oil."] },
    { id: "d-doner", slot: "dinner", name: "Doner kebab and chips", time: "25 min on the day", tag: "Fakeaway", type: "sunday",
      ing: [["lamb-mince",200], ["wrap",62], ["greek-yog",50], ["garlic",5], ["lettuce",40], ["onion",30], ["tomato",50], ["sriracha",10], ["potatoes",200], ["olive-oil",5], ["lemon",13]],
      method: ["Blitz mince with garlic, cumin, oregano and paprika to a paste; bake as a tight loaf at 180°C for 50 minutes.", "Chill, then slice paper-thin and crisp in a hot pan.", "Wrap with salad, garlic yoghurt and chilli; chips on the side."],
      finish: "Crisp the doner slices in a hot dry pan 3 min; air-fry the chips; wrap with salad, garlic sauce and chilli sauce. 15 min",
      comp: [["V", "onion", "thinly sliced"],
        ["V", "tomato", "sliced"],
        ["V", "lettuce", "shredded"],
        ["X", "Doner loaf", "Blitz the lamb mince to a paste with the spices, pack into a tight loaf, wrap in foil", "0.5 tsp salt; 0.5 tsp cumin; 0.5 tsp ground coriander; 0.5 tsp dried oregano; 0.5 tsp smoked paprika; 0.5 tsp garlic granules; 0.5 tsp onion powder; 0.25 tsp chilli flakes"],
        ["O",180,60,"Doner loaf (50 min in foil, 10 min uncovered); chill, then slice paper-thin"],
        ["S", "Garlic sauce", "50 g greek yoghurt; 1 clove garlic; 0.125 x lemon juice; 1 pinch dried mint; 1 pinch salt",0],
        ["P", "doner slices; garlic sauce; salad; wraps; par-boiled chips"]] },
    { id: "d-bigmac", slot: "dinner", name: "Big Mac bowl", time: "30 min", tag: "Fakeaway", type: "fresh",
      ing: [["beef-mince",200], ["onion",30], ["potatoes",350], ["olive-oil",5], ["lettuce",60], ["gherkins",30], ["cheese-slice",20], ["light-mayo",20], ["ketchup",10]],
      sea: [["Big Mac sauce", "20 g light mayo; 10 g ketchup; 1 tsp American mustard; 0.25 tsp smoked paprika; 0.25 tsp onion powder"], ["Mince seasoning", "0.5 tsp salt; 0.5 tsp black pepper; 0.5 tsp garlic granules; 0.5 tsp Worcestershire"]],
      method: ["Dice the potatoes, toss in the oil and a little salt, air-fry at 200°C for 20 minutes.", "Mix the Big Mac sauce with a teaspoon of finely chopped gherkin and a splash of its brine.", "Brown the mince hard with the finely diced onion and the mince seasoning.", "Build the bowl with shredded lettuce, cheese, gherkins and sauce."] },
    { id: "d-pizza", slot: "dinner", name: "Chicken and pepperoni pizza", time: "25 min", tag: "Fakeaway", type: "fresh",
      ing: [["pizza-base",150], ["passata",60], ["mozzarella",80], ["chicken-breast",120], ["turkey-pepperoni",40], ["garlic",2.5]],
      sea: [["Chicken seasoning", "0.5 tsp dried oregano; 0.5 tsp garlic granules; 0.25 tsp salt"], ["Pizza sauce", "60 g passata; 0.5 tsp dried oregano; 0.5 clove garlic; 1 pinch salt; 1 pinch sugar; 1 pinch chilli flakes"]],
      method: ["Oven and a tray to the hottest setting.", "Toss the chicken in the chicken seasoning; pan-fry or air-fry 10 minutes and slice.", "Stir the pizza sauce together and spread it thin on the base.", "Top with mozzarella, chicken and pepperoni; bake on the hot tray 8–10 minutes."] },
    { id: "d-meatball-sub", slot: "dinner", name: "Meatball marinara sub", time: "10 min on the day", tag: "Italian", type: "sunday",
      after: {"2": [1]},
      ing: [["beef-mince",180], ["panko",15], ["eggs",15], ["passata",120], ["garlic",7.5], ["mozzarella",40], ["parmesan",10], ["sub-roll",90], ["basil",3]],
      sea: [["To finish", "3 g fresh basil"]],
      method: ["Mix mince, panko, egg, garlic, parmesan and herbs; roll 6 meatballs.", "Brown, then simmer in seasoned passata for 12 minutes.", "Into the toasted roll, mozzarella on top, grill to melt."],
      finish: "Reheat until piping hot, fill the toasted roll, mozzarella on top, grill to melt. 8 min",
      comp: [["X", "Meatballs", "Mix the mince with the panko, egg and seasoning; roll 6 per portion", "1 clove garlic; 10 g grated parmesan; 0.5 tsp dried oregano; 0.5 tsp salt"],
        ["O",200,15,"Meatballs, to brown"],
        ["S", "Meatball marinara (simmer the cooked meatballs in it)", "120 g passata; 0.5 clove garlic; 0.5 tsp dried oregano; 1 pinch chilli flakes",12],
        ["P", "meatballs in marinara; mozzarella; rolls"]] },
    { id: "d-quesadilla", slot: "dinner", name: "Chicken quesadillas", time: "25 min", type: "fresh",
      ing: [["chicken-breast",180], ["wrap",124], ["mozzarella",50], ["peppers",60], ["onion",40], ["salsa",50], ["greek-yog",40], ["lime",8.1]],
      sea: [["Fajita spice", "1 tsp smoked paprika; 0.5 tsp cumin; 0.5 tsp garlic granules; 0.5 tsp chilli powder; 0.25 tsp dried oregano; 0.5 tsp salt; 0.125 x lime juice"]],
      method: ["Slice the chicken and toss in the fajita spice.", "Cook hot with the sliced peppers and onion, about 8 minutes.", "Fill the wraps with the filling and cheese; dry-fry 2 minutes a side.", "Salsa and yoghurt to dip."] },
    { id: "d-carbonara", slot: "dinner", name: "High-protein carbonara", time: "20 min", tag: "Italian", type: "fresh",
      ing: [["turkey-rashers",120], ["eggs",120], ["pecorino",25], ["pasta",110], ["chicken-breast",100], ["olive-oil",5]],
      sea: [["Seasoning", "0.5 tsp black pepper; 0.25 tsp salt; 5 ml olive oil"]],
      method: ["Spaghetti on in well-salted water.", "Dice the turkey rashers and crisp them in the oil; season the sliced chicken and pan-fry alongside.", "Whisk the eggs with the grated pecorino and the black pepper.", "Off the heat, toss the pasta with the meat, then the egg mix and a splash of pasta water until glossy."] },
    { id: "d-lasagne", slot: "dinner", name: "Lean beef lasagne", time: "5 min on the day", tag: "Italian", type: "sunday",
      ing: [["beef-mince",180], ["onion",50], ["garlic",5], ["passata",150], ["lasagne-sheets",70], ["skimmed-milk",150], ["cornflour",12], ["parmesan",15], ["mozzarella",30]],
      method: ["Ragù: brown mince, onion and garlic; passata and herbs; simmer 30 minutes.", "White sauce: skimmed milk thickened with cornflour, nutmeg and half the parmesan.", "Layer, top with mozzarella and parmesan; bake at 190°C for 40 minutes. Rest before cutting."],
      finish: "Microwave until piping hot. 5 min",
      comp: [["V", "onion", "finely diced"],
        ["H", "Lasagne ragù",30,"Brown the mince with the onion and garlic, add the passata and seasoning, simmer 30 min", "1 clove garlic; 1 tsp tomato purée; 150 g passata; 0.5 tsp dried oregano; 1 x bay leaf; 0.5 tsp salt"],
        ["S", "Lasagne white sauce (whisk over the heat until thick)", "150 ml skimmed milk; 12 g cornflour; 1 pinch nutmeg; 1 pinch salt; 8 g grated parmesan",5],
        ["X", "Build the lasagne", "Layer ragù, sheets and white sauce; finish with mozzarella and parmesan"],
        ["O",180,45,"Lasagne; rest 15 min before cutting"],
        ["P", "lasagne portions"]] },
    { id: "d-prawn-linguine", slot: "dinner", name: "Prawn arrabbiata linguine", time: "25 min", tag: "Italian", type: "fresh",
      ing: [["prawns",200], ["chopped-tom",200], ["garlic",10], ["olive-oil",10], ["pasta",110], ["parmesan",10], ["parsley",3]],
      sea: [["Arrabbiata", "10 ml olive oil; 2 clove garlic; 0.5 tsp chilli flakes; 200 g chopped tomatoes; 1 pinch sugar; 1 pinch salt"], ["To finish", "3 g fresh parsley"]],
      method: ["Linguine on.", "Arrabbiata: warm the oil with the sliced garlic and chilli flakes, add the tomatoes, sugar and salt, reduce 12 minutes.", "Prawns in for 2 minutes.", "Toss with the pasta and a splash of pasta water; parsley and parmesan on top."] },
    { id: "d-steak-chips", slot: "dinner", name: "Steak, chips and rocket", time: "30 min", type: "fresh",
      ing: [["steak",250], ["potatoes",350], ["olive-oil",8], ["rocket",40], ["parmesan",10], ["garlic",5]],
      sea: [["Seasoning", "0.5 tsp salt; 0.25 tsp black pepper; 5 g butter; 1 clove garlic; 1 pinch dried thyme"]],
      method: ["Take the steak out of the fridge 30 minutes ahead.", "Cut the chips, toss in the oil and a little salt, air-fry at 200°C for 20 minutes.", "Season the steak and sear 2–3 minutes a side, adding the butter, crushed garlic and thyme for the last minute; rest 5 minutes.", "Rocket and shaved parmesan alongside."] },
    { id: "d-pasta-bake", slot: "dinner", name: "Chicken and turkey bacon pasta bake", time: "5 min on the day", tag: "Italian", type: "sunday",
      ing: [["chicken-breast",180], ["turkey-rashers",60], ["penne",100], ["passata",150], ["garlic",5], ["mozzarella",50], ["parmesan",10], ["basil",3]],
      sea: [["To finish", "3 g fresh basil"]],
      method: ["Cook penne 2 minutes short.", "Brown the chicken and turkey rashers; add garlic and passata.", "Mix with the pasta, top with mozzarella and parmesan; bake at 200°C for 15 minutes."],
      finish: "Microwave until piping hot. 5 min",
      comp: [["H", "Pasta bake sauce",15,"Brown the diced chicken and turkey rashers, add the garlic, passata and seasoning, simmer 10 min", "1 clove garlic; 150 g passata; 0.5 tsp dried oregano; 1 pinch chilli flakes; 0.25 tsp salt"],
        ["X", "Build the pasta bake", "Stir the penne through the sauce; top with mozzarella and parmesan"],
        ["O",200,15,"Pasta bake"],
        ["P", "pasta bake portions"]] },
    { id: "d-pesto-chicken", slot: "dinner", name: "Chicken pesto pasta", time: "20 min", tag: "Italian", type: "fresh",
      ing: [["chicken-breast",180], ["pasta",100], ["pesto",25], ["tomato",100], ["rocket",30], ["parmesan",10], ["olive-oil",5], ["lemon",25]],
      sea: [["Chicken seasoning", "0.5 tsp salt; 0.25 tsp black pepper; 0.5 tsp garlic granules; 5 ml olive oil"], ["To toss", "25 g pesto; 0.25 x lemon juice"]],
      method: ["Spaghetti or linguine on.", "Slice the chicken, toss in the chicken seasoning and pan-fry in the oil until golden, 6–7 minutes.", "Add the halved tomatoes for 2 minutes.", "Toss with the pasta, pesto, lemon juice and a splash of pasta water; rocket and parmesan on top."] },
    { id: "d-rigatoni", slot: "dinner", name: "Creamy tomato chicken rigatoni", time: "25 min", tag: "Italian", type: "fresh",
      ing: [["chicken-breast",180], ["penne",100], ["passata",150], ["cream-cheese",40], ["garlic",5], ["spinach",60], ["parmesan",10], ["olive-oil",5]],
      sea: [["Chicken seasoning", "0.5 tsp salt; 0.5 tsp dried oregano; 0.25 tsp black pepper; 5 ml olive oil"], ["Sauce", "1 clove garlic; 0.25 tsp chilli flakes; 150 g passata; 40 g light cream cheese"]],
      method: ["Rigatoni on.", "Dice the chicken, toss in the chicken seasoning and brown in the oil.", "Add the garlic and chilli flakes for 30 seconds, then the passata; simmer 8 minutes.", "Stir in the cream cheese until smooth, wilt in the spinach, toss with the pasta and a splash of pasta water; parmesan on top."] },
    { id: "d-puttanesca", slot: "dinner", name: "Tuna puttanesca", time: "20 min", tag: "Italian", type: "fresh",
      ing: [["tuna",150], ["pasta",110], ["chopped-tom",200], ["olives",25], ["capers",10], ["garlic",10], ["olive-oil",8], ["parmesan",10], ["parsley",3]],
      sea: [["Sauce", "8 ml olive oil; 2 clove garlic; 0.5 tsp chilli flakes; 200 g chopped tomatoes; 25 g olives; 10 g capers; 0.5 tsp dried oregano"], ["To finish", "3 g fresh parsley"]],
      method: ["Spaghetti on.", "Warm the oil with the sliced garlic and chilli flakes; add the tomatoes, halved olives, capers and oregano; reduce 10 minutes.", "Fold in the drained tuna and toss with the pasta and a splash of pasta water.", "Parsley and parmesan on top. Taste before salting: the olives and capers are salty."] },
    { id: "d-meatballs", slot: "dinner", name: "Spaghetti and meatballs", time: "10 min on the day", tag: "Italian", type: "sunday",
      after: {"2": [1]},
      ing: [["beef-mince",180], ["panko",15], ["eggs",15], ["passata",150], ["garlic",7.5], ["pasta",90], ["parmesan",15], ["basil",3]],
      sea: [["To finish", "3 g fresh basil"]],
      method: ["Mix mince, panko, egg, garlic, parmesan and herbs; roll 6 meatballs.", "Brown, then simmer in seasoned passata for 12 minutes.", "Toss with spaghetti; parmesan on top."],
      finish: "Spaghetti on; reheat the meatballs in their sauce until piping hot, toss together with a splash of pasta water; parmesan on top. 10 min",
      comp: [["X", "Meatballs", "Mix the mince with the panko, egg and seasoning; roll 6 per portion", "1 clove garlic; 10 g grated parmesan; 0.5 tsp dried oregano; 0.5 tsp salt"],
        ["O",200,15,"Meatballs, to brown"],
        ["S", "Meatball marinara (simmer the cooked meatballs in it)", "150 g passata; 0.5 clove garlic; 0.5 tsp dried oregano; 1 pinch chilli flakes",12],
        ["P", "meatballs in marinara"]] },
    { id: "d-crispy-chilli", slot: "dinner", name: "Crispy chilli chicken", time: "25 min on the day", tag: "Fakeaway", type: "head",
      ing: [["chicken-breast",200], ["cornflour",20], ["olive-oil",8], ["peppers",80], ["onion",50], ["ketchup",20], ["honey",10], ["sriracha",10], ["soy",10], ["jasmine-rice",90], ["sushi-vinegar",15], ["garlic",5]],
      sea: [["Coating", "17 g cornflour"]],
      method: ["Rice on. Dice the chicken and toss in the five-spice seasoning, then the cornflour coating.", "Spritz with the oil and air-fry at 200°C for 12 minutes.", "Shake the sauce together. Wok the sliced onion and peppers hot for 3 minutes, add the sauce and bubble until glossy.", "Toss the chicken through. Serve with rice."],
      finish: "Rice on. Toss the chicken in the cornflour coating, spritz with the oil and air-fry at 200°C for 12 min. Wok the sliced onion and peppers hot for 3 min, add the sauce and bubble until glossy, toss the chicken through. 25 min",
      comp: [["M", "dry", "Five-spice seasoning (dice the chicken first)", "chicken-breast", "0.5 tsp salt; 0.5 tsp black pepper; 0.25 tsp five-spice",0],
        ["S", "Crispy chilli sauce", "20 g ketchup; 10 g honey; 10 g sriracha; 10 ml soy; 15 ml rice vinegar; 1 clove garlic; 3 g cornflour; 30 ml water",0],
        ["P", "diced seasoned raw chicken, bagged flat; sauce jar"]] },
    { id: "l-pesto-pasta", slot: "lunch", name: "Pesto chicken pasta salad", time: "20 min", late: "no",
      ing: [["chicken-breast",150], ["penne",80], ["pesto",20], ["tomato",80], ["rocket",30], ["mozzarella",30], ["lemon",25]],
      method: ["Roast the seasoned chicken at 200°C for 18 minutes; dice.", "Cook the penne, cool, toss with pesto, lemon and halved tomatoes.", "Box with the chicken and torn mozzarella; rocket on the day."],
      finish: "Add the rocket and eat cold. 1 min",
      comp: [["V", "tomato", "halved"],
        ["M", "dry", "Lemon and garlic rub", "chicken-breast", "0.5 tsp garlic granules; 0.5 tsp salt; 0.25 x lemon zest",0],
        ["O",200,18,"Pesto pasta chicken (74°C inside), rest and dice"],
        ["S", "Pesto dressing (toss through the cooled penne)", "20 g pesto; 0.25 x lemon juice",0],
        ["P", "pesto penne, diced chicken, tomatoes, torn mozzarella; rocket in a bag"]] },
    { id: "l-tuna-pasta", slot: "lunch", name: "Lemon tuna pasta salad", time: "15 min", late: "no",
      ing: [["tuna",140], ["penne",80], ["light-mayo",15], ["greek-yog",40], ["cucumber",60], ["corn",50], ["lemon",25]],
      method: ["Cook the penne and cool under cold water.", "Mix mayo, yoghurt, lemon zest and juice, salt and pepper.", "Fold through the pasta with the tuna, diced cucumber and corn."],
      finish: "Eat cold. 0 min",
      comp: [["V", "cucumber", "diced"],
        ["S", "Lemon tuna mayo (fold through the cooled penne, tuna, cucumber and corn)", "15 g light mayo; 40 g greek yoghurt; 0.25 x lemon juice; 0.25 x lemon zest; 1 pinch salt; 1 pinch black pepper",0],
        ["P", "tuna pasta salad, ready mixed"]] },
    { id: "l-ragu-box", slot: "lunch", name: "Beef ragù pasta box", time: "Sunday batch", late: "freeze",
      ing: [["beef-shin",150], ["onion",50], ["garlic",5], ["passata",170], ["olive-oil",5], ["pasta",85], ["parmesan",10]],
      method: ["Make the ragù as for the pappardelle (the same pot does both).", "Cook the pasta 2 minutes short and toss through the ragù.", "Box, cool and freeze; parmesan on after reheating."],
      finish: "Microwave until piping hot, parmesan on top. 5 min",
      comp: [["V", "onion", "finely diced"],
        ["L", "Beef ragù", "ip",50,"1 clove garlic; 1 tsp tomato purée; 170 g passata; 100 ml beef stock; 1 x bay leaf; 0.5 tsp dried oregano; 0.5 tsp salt", "Brown the shin in batches on Sauté, soften the onion and garlic, add everything else, pressure-cook 50 min, shred, reduce on Sauté until thick"],
        ["P", "pasta tossed through the ragù; parmesan in a twist of foil"]] },
    { id: "l-arrabbiata", slot: "lunch", name: "Spicy arrabbiata chicken pasta", time: "25 min", late: "freeze",
      ing: [["chicken-breast",160], ["penne",85], ["chopped-tom",200], ["garlic",10], ["olive-oil",8], ["parmesan",10]],
      method: ["Roast the chicken with oregano and chilli at 200°C for 18 minutes; slice.", "Arrabbiata: garlic and chilli flakes in the oil, tomatoes, reduce 15 minutes.", "Toss the penne through the sauce, chicken on top."],
      finish: "Microwave until piping hot, parmesan on top. 4 min",
      comp: [["M", "dry", "Chilli and oregano rub", "chicken-breast", "0.5 tsp dried oregano; 0.25 tsp chilli flakes; 0.5 tsp salt",0],
        ["O",200,18,"Arrabbiata chicken (74°C inside), rest and slice"],
        ["S", "Arrabbiata (toss the cooked penne through it)", "8 ml olive oil; 2 clove garlic; 0.5 tsp chilli flakes; 200 g chopped tomatoes; 1 pinch sugar; 1 pinch salt",15],
        ["P", "penne in arrabbiata, sliced chicken on top; parmesan in a twist of foil"]] }
  ];

  const VEG_EACH = {"onion":[150,"onion"],"peppers":[160,"pepper"],"cucumber":[300,"cucumber"],"tomato":[90,"tomato"],"broccoli":[350,"head of broccoli"],"lettuce":[250,"lettuce"],"mango":[200,"mango"],"greens":[250,"bunch of pak choi or greens"]};
  const BATCH_CARBS = ["sushi-rice", "jasmine-rice", "pasta", "penne", "rice-noodles", "potatoes"];
  const NO_BATCH = ["l-onigiri"];

  // Where the two phones meet to sync menus, ticks and timers. The household key is kept on the phones, never here.
  const SYNC_URL = "https://gym-app-6c933-default-rtdb.europe-west1.firebasedatabase.app";

  const RECIPES = {};
  R.forEach(function (r) { RECIPES[r.id] = r; });
  return { ING: ING, ALIAS: ALIAS, CUPBOARD: CUPBOARD, TRIM: TRIM, PACKS: PACKS, SYNC_URL: SYNC_URL, HOUSE: HOUSE, DEFAULTS: DEFAULTS, PRESETS: PRESETS, RECIPES: RECIPES, VEG_EACH: VEG_EACH, BATCH_CARBS: BATCH_CARBS, NO_BATCH: NO_BATCH };
})();
