// Form guides, shared by Gym-Bro and Gym-Gyal.
// m: muscles worked · s: setup · c: how to do it · x: common mistakes · q: form video search
// u: done one side at a time: "leg", "arm" or "side" (all reps one side, then the other); "-alt" = alternate sides each rep.
// GB_GUIDES is keyed by exercise id (gym versions). GB_HOME_GUIDES holds the home-only movements, and GB_HOME_MAP
// points each home exercise name at its guide in either table.
window.GB_GUIDES = {
  "bench": { m: ["Chest", "Front delts", "Triceps"],
    s: ["Eyes under the bar, feet flat and planted.", "Squeeze your shoulder blades together and down, keep a slight arch.", "Grip just outside shoulder width, wrists stacked over elbows."],
    c: ["Unrack and hold the bar over your shoulders.", "Lower under control to your lower chest, elbows about 45° from your body.", "Light touch, no bounce, then drive up and slightly back towards your face.", "Breathe in and brace before each rep."],
    x: ["Flaring elbows to 90°, which strains the shoulders.", "Bouncing off the chest or lifting your hips.", "Always use a spotter or safety arms on heavy sets."],
    q: "barbell bench press technique" },
  "assist-pullup": { m: ["Lats", "Upper back", "Biceps", "Grip"],
    s: ["Assisted pull-up machine: kneel on the pad and pick a counterweight that lets you do 6 clean reps. More weight on the stack makes it easier.", "No assisted machine free? Use the lat pulldown with the same grip and the same reps.", "Hands just outside shoulder width, palms away."],
    c: ["Start from straight arms and pull your shoulders down first.", "Drive your elbows down towards your back pockets until your chin clears the bar.", "Lower all the way under control.", "After the last set, do 2–3 slow negatives on a normal bar: step or jump to the top and lower yourself over 3–5 seconds."],
    x: ["Half reps that stop short of straight arms.", "Using so much assistance that the last reps are easy.", "Log the assistance or pulldown weight. Take 5 kg of help off once you hit 10 reps on every set; at 5 clean bodyweight pull-ups, ask Claude to switch this back to weighted pull-ups."],
    q: "assisted pull up machine technique" },
  "incline-press": { m: ["Upper chest", "Front delts", "Triceps"],
    s: ["Bench at 30°, not steeper, or it turns into a shoulder press.", "Kick the dumbbells up off your knees, shoulder blades pinned back."],
    c: ["Lower the dumbbells to the sides of your upper chest for a deep stretch.", "Press up and slightly in, stopping just short of the dumbbells touching.", "Take 2–3 seconds on the way down."],
    x: ["Bench set too steep.", "Cutting the bottom half of the rep short."],
    q: "incline dumbbell press technique" },
  "row": { m: ["Mid back", "Lats", "Rear delts"],
    s: ["Chest firmly on the pad, feet braced.", "Neutral or overhand grip, arms long at the start."],
    c: ["Pull your elbows back and slightly out until the handles reach your ribs.", "Squeeze your shoulder blades together for a second.", "Let your shoulders reach forward at the bottom for a full stretch."],
    x: ["Lifting your chest off the pad to heave the weight.", "Shrugging the weight up with your traps."],
    q: "chest supported row technique" },
  "fly": { m: ["Chest"],
    s: ["Pulleys at shoulder height, step forward into a split stance.", "Slight bend in the elbows and keep it fixed."],
    c: ["Open your arms wide until you feel a deep chest stretch.", "Hug the handles together in an arc in front of your chest.", "Control the return, don't let the stack yank you back."],
    x: ["Bending your elbows so it turns into a press.", "Going too heavy and losing the stretch."],
    q: "cable chest fly technique" },
  "lateral-mon": { m: ["Side delts"],
    s: ["Light dumbbells, slight forward lean, soft elbows."],
    c: ["Raise out to the sides, leading with your elbows.", "Stop at shoulder height, pinkies roughly level with thumbs.", "Lower slowly over 2–3 seconds."],
    x: ["Swinging your body to throw the weight up.", "Shrugging so your traps do the work."],
    q: "dumbbell lateral raise technique" },

  "ohp": { m: ["Front and side delts", "Triceps", "Upper chest", "Core"],
    s: ["Bar on your front delts, grip just outside your shoulders.", "Feet hip width, squeeze your glutes and brace your abs hard."],
    c: ["Press straight up, moving your head back slightly so the bar clears your chin.", "Once the bar passes your forehead, push your head through so the bar finishes over your mid-foot.", "Lock out fully, then lower under control to your collarbone."],
    x: ["Leaning back into a standing incline press.", "Pressing the bar out in front instead of straight up."],
    q: "standing overhead press technique" },
  "shrug": { m: ["Upper traps", "Grip"],
    s: ["Bar or dumbbells at arm's length, overhand grip just outside the thighs.", "Use lifting straps if your grip gives out before your traps."],
    c: ["Lift your shoulders straight up towards your ears.", "Hold the top for 1–2 seconds.", "Lower slowly to a full stretch."],
    x: ["Rolling your shoulders in circles.", "Bending your elbows to curl the weight."],
    q: "barbell shrug technique" },
  "cable-lateral": { u: "arm", m: ["Side delts"],
    s: ["Pulley at its lowest setting, the cable running behind your body.", "Stand side-on, working arm furthest from the stack."],
    c: ["Raise out to the side to shoulder height, leading with your elbow.", "Pause briefly at the top.", "Lower slowly until your hand is just behind your hip, for a stretch."],
    x: ["Leaning your body away to cheat the weight up.", "Going too heavy and cutting the range short."],
    q: "cable lateral raise behind the back" },
  "cgbench": { m: ["Triceps", "Chest", "Front delts"],
    s: ["Grip about shoulder width, no narrower, to spare your wrists.", "Same setup as bench: shoulder blades back, feet planted."],
    c: ["Lower to your lower chest with your elbows tucked close to your sides.", "Press up, finishing with your triceps."],
    x: ["Grip so narrow your wrists bend.", "Flaring your elbows out."],
    q: "close grip bench press technique" },
  "incline-curl": { m: ["Biceps (long head)"],
    s: ["Bench at 45–60°, arms hanging straight down behind your torso."],
    c: ["Curl up without letting your elbows drift forward.", "Squeeze at the top, turning your pinky up slightly.", "Lower all the way to a full stretch."],
    x: ["Swinging your elbows forward to finish the rep.", "Stopping short of the bottom stretch."],
    q: "incline dumbbell curl technique" },
  "facepull": { m: ["Rear delts", "Upper back", "Rotator cuff"],
    s: ["Rope at upper-chest to face height.", "Thumbs pointing back towards you."],
    c: ["Pull the rope towards your face, splitting it apart.", "Finish with your hands beside your ears, elbows high, like a double-biceps pose.", "Control the return."],
    x: ["Leaning back and turning it into a row.", "Going heavy enough that your elbows drop."],
    q: "face pull technique" },
  "neck-a": { m: ["Neck flexors and extensors"],
    s: ["Start very light: a folded towel, then a 2.5–5 kg plate on a towel, or a neck harness.", "Lie face-up on a bench with your head off the end for curls, face-down for extensions."],
    c: ["Move slowly through a comfortable range, chin to chest for curls, looking up for extensions.", "2 seconds up, 2 seconds down. Stop 2–3 reps short of failure."],
    x: ["Jerking or bouncing the weight.", "Going heavy early. Stop at once if anything feels sharp or pinched."],
    q: "neck curl and neck extension for beginners" },

  "deadlift": { m: ["Glutes", "Hamstrings", "Whole back", "Traps", "Grip"],
    s: ["Mid-foot under the bar, feet hip width.", "Hinge down and grip just outside your legs, shins touching the bar.", "Chest up, pull the slack out of the bar until your back tightens."],
    c: ["Big breath into your belly and brace.", "Push the floor away, keeping the bar touching your legs.", "Stand tall with your glutes; don't lean back.", "Lower by pushing your hips back, then bend your knees once the bar passes them. Reset each rep."],
    x: ["Rounding your lower back.", "Jerking the bar off the floor instead of pulling the slack out first.", "A trap bar is easier to learn and fine to use."],
    q: "deadlift technique for beginners" },
  "squat": { m: ["Quads", "Glutes", "Adductors", "Core"],
    s: ["Bar on your upper traps, hands just outside your shoulders.", "Feet shoulder width, toes turned out 15–30°.", "Set the safety bars just below your bottom position."],
    c: ["Brace, then sit down between your hips, knees tracking over your toes.", "Go to at least parallel (hip crease level with the knee).", "Drive up through your whole foot, chest leading."],
    x: ["Knees caving in on the way up.", "Heels lifting, or your hips shooting up first."],
    q: "back squat technique" },
  "bss": { u: "leg", m: ["Quads", "Glutes"],
    s: ["Back foot laces-down on a bench, front foot about a stride ahead.", "Dumbbells at your sides."],
    c: ["Drop straight down until your back knee nearly touches the floor.", "Drive up through your front heel and mid-foot.", "Finish all reps on one leg, then switch."],
    x: ["Front foot too close, so your heel lifts.", "Pushing off with the back leg."],
    q: "bulgarian split squat technique" },
  "legcurl": { m: ["Hamstrings"],
    s: ["Knees just off the edge of the pad, ankle pad above your heels.", "Seated version is best if your gym has it."],
    c: ["Curl the pad towards you while keeping your hips down.", "Squeeze for a second.", "Lower slowly to full stretch."],
    x: ["Lifting your hips off the pad.", "Letting the weight drop back."],
    q: "seated leg curl technique" },
  "calf": { m: ["Calves"],
    s: ["Balls of your feet on the step edge, knees straight but not locked."],
    c: ["Drop to a deep stretch and pause for 2 seconds.", "Rise as high as you can onto your big toes.", "Pause at the top."],
    x: ["Bouncing through fast half reps.", "Bending your knees to help."],
    q: "standing calf raise technique" },
  "carry": { m: ["Grip", "Traps", "Core", "Whole body"],
    s: ["Heaviest dumbbells or handles you can hold for the full distance.", "Deadlift them up with a flat back."],
    c: ["Stand tall, shoulders back, core braced.", "Walk with short, quick steps.", "Put them down under control, don't drop them."],
    x: ["Leaning to one side or letting your shoulders round forward.", "Choosing a weight so light it feels easy."],
    q: "farmers walk technique" },

  "dips": { m: ["Lower chest", "Triceps", "Front delts"],
    s: ["Parallel bars, arms straight, shoulders pulled down away from your ears.", "Add weight with a dip belt once you pass 12 clean reps."],
    c: ["Lean your torso slightly forward and lower until your shoulders are just below your elbows.", "Press back up to lockout."],
    x: ["Dropping too deep with your shoulders rolling forward.", "Shrugging up towards your ears."],
    q: "chest dip technique" },
  "bb-row": { m: ["Upper and mid back", "Lats", "Rear delts", "Lower back"],
    s: ["Grip just outside your knees, overhand.", "Hinge until your torso is 30–45° from the floor, flat back, knees soft."],
    c: ["Pull the bar to your lower ribs, driving your elbows back.", "Squeeze your shoulder blades together.", "Lower with control to straight arms."],
    x: ["Standing up more and more with each rep.", "Using your hips to heave the weight."],
    q: "barbell row technique" },
  "flat-db": { m: ["Chest", "Front delts", "Triceps"],
    s: ["Kick the dumbbells up off your knees, shoulder blades pinned back.", "Feet flat, slight arch."],
    c: ["Lower to the sides of your chest for a deep stretch, elbows about 45°.", "Press up and slightly in.", "Take 2–3 seconds on the way down."],
    x: ["Flaring your elbows wide.", "Cutting the bottom range short."],
    q: "flat dumbbell press technique" },
  "pulldown": { m: ["Lats", "Upper back", "Biceps"],
    s: ["Neutral (palms facing) handle, thighs locked under the pad.", "Lean back very slightly."],
    c: ["Pull your shoulders down first, then drive your elbows to your sides.", "Bring the handle to your upper chest.", "Let it rise until your arms are straight and your lats stretch."],
    x: ["Leaning way back and using momentum.", "Stopping short at the top."],
    q: "neutral grip lat pulldown technique" },
  "pecdeck": { m: ["Chest"],
    s: ["Seat set so the handles are at mid-chest height.", "Slight bend in the elbows."],
    c: ["Bring the handles together in front of your chest.", "Squeeze for a second.", "Open slowly to a big stretch."],
    x: ["Letting your shoulders roll forward.", "Short, fast reps."],
    q: "pec deck technique" },
  "reardelt": { m: ["Rear delts", "Upper back"],
    s: ["Reverse pec deck facing the pad, or bent over with light dumbbells.", "Arms slightly bent."],
    c: ["Sweep your arms out wide, leading with your elbows.", "Think \"out\", not \"back\"; don't squeeze your shoulder blades hard.", "Control the return."],
    x: ["Going heavy and turning it into a row.", "Swinging your torso."],
    q: "reverse pec deck rear delt fly technique" },

  "rackpull": { m: ["Traps", "Upper back", "Glutes", "Grip"],
    s: ["Bar on the rack pins or blocks, just below your knees.", "Set up like a deadlift: shins close, flat back, slack out of the bar."],
    c: ["Brace, then drive your hips through to stand tall.", "Squeeze your traps and upper back hard at the top.", "Lower under control back to the pins."],
    x: ["Leaning back hard at lockout.", "Bouncing the bar off the pins."],
    q: "rack pull technique" },
  "db-ohp": { m: ["Front and side delts", "Triceps"],
    s: ["Bench almost upright (about 80°), back flat against it.", "Dumbbells at shoulder height, palms forward or slightly turned in."],
    c: ["Press up until your arms are nearly straight, dumbbells above your shoulders.", "Lower until your elbows are just below shoulder height."],
    x: ["Arching off the bench.", "Clanging the dumbbells together at the top."],
    q: "seated dumbbell shoulder press technique" },
  "lateral-myo": { m: ["Side delts"],
    s: ["Light dumbbells or cable. Myo-reps: one activation set, then short mini-sets."],
    c: ["Do 15–20 reps to near failure.", "Rest 5 breaths, then do 3–5 more reps.", "Repeat the 5 breaths and 3–5 reps up to 3 times; that counts as 4 sets."],
    x: ["Swinging to keep the reps going.", "Resting too long between mini-sets."],
    q: "lateral raise myo reps" },
  "heavy-shrug": { m: ["Upper traps", "Grip"],
    s: ["Dumbbells at your sides, standing tall.", "Use straps if your grip fails before your traps do."],
    c: ["Lift straight up towards your ears.", "Hold for 1–2 seconds at the top.", "Lower slowly to a full stretch."],
    x: ["Rolling your shoulders.", "Cutting the range short with too much weight."],
    q: "dumbbell shrug technique" },
  "upright": { m: ["Side delts", "Traps"],
    s: ["Wide grip on the bar or cable, hands outside shoulder width."],
    c: ["Pull up leading with your elbows.", "Stop when your hands reach lower-chest height, elbows at shoulder height.", "Lower under control."],
    x: ["Narrow grip, which can pinch the shoulder.", "Pulling all the way up to your chin."],
    q: "wide grip upright row technique" },
  "ez-curl": { m: ["Biceps", "Forearms"],
    s: ["Grip the angled part of the EZ bar, elbows pinned at your sides."],
    c: ["Curl up without your elbows moving forward.", "Squeeze at the top.", "Lower over 2–3 seconds to straight arms."],
    x: ["Swinging your hips to start the rep.", "Stopping halfway down."],
    q: "ez bar curl technique" },
  "skull": { m: ["Triceps"],
    s: ["Lie on a flat bench with the EZ bar over your chest.", "Tilt your arms back slightly towards your head."],
    c: ["Bend only at the elbows, lowering the bar towards your forehead or just behind your head.", "Extend back up to the start without locking out hard."],
    x: ["Elbows flaring wide.", "Turning it into a press by moving your upper arms."],
    q: "skull crusher technique" },
  "hammer": { m: ["Brachialis", "Forearms", "Biceps"],
    s: ["Dumbbells at your sides, palms facing in."],
    c: ["Curl up keeping your palms facing each other.", "Lower slowly to straight arms."],
    x: ["Swinging the weights up.", "Letting your elbows drift forward."],
    q: "hammer curl technique" },
  "neck-b": { m: ["Neck flexors and extensors"],
    s: ["Same as Tuesday's: light plate on a towel, or a neck harness.", "Only add weight when 20 slow reps feel easy."],
    c: ["Slow, controlled reps through a comfortable range.", "2 seconds up, 2 seconds down."],
    x: ["Jerky reps or heavy loading.", "Stop at once if anything feels sharp or pinched."],
    q: "neck harness training for beginners" },
  // ---- Gym-Gyal exercises ----
  "hip-thrust": { m: ["Glutes", "Hamstrings"],
    s: ["Upper back on a bench edge, just below your shoulder blades.", "Padded bar across your hip crease; feet flat, shin vertical at the top.", "Smith machine or hip-thrust machine works too."],
    c: ["Tuck your chin and look forward, ribs down.", "Drive through your heels and squeeze your glutes to lift until your body is a straight line from knees to shoulders.", "Hold the top for a second, then lower under control."],
    x: ["Arching your lower back at the top instead of squeezing your glutes.", "Feet too far out (hamstrings take over) or too close (quads take over)."],
    q: "barbell hip thrust technique" },
  "rdl": { m: ["Hamstrings", "Glutes", "Lower back"],
    s: ["Barbell or dumbbells at your thighs, feet hip width, knees soft."],
    c: ["Push your hips straight back, sliding the weight down your legs.", "Keep your back flat and go until you feel a strong hamstring stretch, usually mid-shin.", "Drive your hips forward to stand, squeezing your glutes."],
    x: ["Rounding your back to reach lower.", "Bending your knees so it turns into a squat."],
    q: "romanian deadlift technique" },
  "bss-glute": { u: "leg", m: ["Glutes", "Quads"],
    s: ["Back foot laces-down on a bench, front foot a long stride ahead.", "Dumbbells at your sides."],
    c: ["Lean your torso slightly forward over the front leg; this shifts the work to your glutes.", "Lower until your back knee nearly touches the floor.", "Drive up through your front heel."],
    x: ["Front foot too close, so your heel lifts.", "Pushing off with the back leg."],
    q: "bulgarian split squat glute focus" },
  "abduction": { m: ["Glute medius", "Upper glutes"],
    s: ["Hip abduction machine, back against the pad, or lean forward slightly for more glute.", "Pads on the outside of your knees."],
    c: ["Push your knees out as far as they go.", "Hold for a second at the widest point.", "Return slowly; don't let the stack slam."],
    x: ["Short, fast reps.", "Going so heavy you can't reach the full range."],
    q: "hip abduction machine glutes technique" },
  "dead-bug": { u: "side-alt", m: ["Deep core", "Abs"],
    s: ["Lie on your back, arms straight up, knees bent at 90° over your hips.", "Press your lower back flat into the floor."],
    c: ["Slowly lower one arm behind your head and the opposite leg towards the floor.", "Keep your lower back pinned down the whole time.", "Return and switch sides. Breathe out as you lower."],
    x: ["Lower back arching off the floor.", "Rushing the reps."],
    q: "dead bug exercise technique" },
  "seated-press": { m: ["Shoulders", "Triceps"],
    s: ["Bench almost upright, dumbbells at shoulder height.", "Back flat against the pad."],
    c: ["Press up until your arms are nearly straight.", "Lower until your elbows are just below your shoulders.", "Breathe out on the way up."],
    x: ["Arching off the bench.", "Cutting the bottom half of the rep."],
    q: "seated dumbbell shoulder press technique" },
  "pallof": { u: "side", m: ["Obliques", "Deep core"],
    s: ["Cable at chest height, stand side-on to the machine.", "Hold the handle at your chest with both hands, feet hip width."],
    c: ["Press the handle straight out in front of you.", "Resist the cable pulling you round; hold for 2 seconds.", "Bring it back to your chest. Do all reps, then switch sides."],
    x: ["Letting your hips or shoulders twist.", "Going so heavy you lean away."],
    q: "pallof press technique" },
  "step-up": { u: "leg", m: ["Glutes", "Quads"],
    s: ["Box or bench about knee height, dumbbells at your sides."],
    c: ["Put your whole foot on the box and lean slightly forward.", "Drive up through that heel without pushing off the back foot.", "Lower slowly. Finish all reps on one leg, then switch."],
    x: ["Bouncing off the back foot.", "Box so high your hips have to twist."],
    q: "dumbbell step up glute technique" },
  "kickback": { u: "leg", m: ["Glutes"],
    s: ["Ankle strap on a low cable, hold the machine for balance.", "Slight forward lean, standing knee soft."],
    c: ["Kick your leg back and slightly out, leading with your heel.", "Squeeze your glute at the top for a second.", "Return slowly without letting the weight stack touch."],
    x: ["Arching your lower back to get the leg higher.", "Swinging the leg."],
    q: "cable glute kickback technique" },
  "back-ext": { m: ["Glutes", "Hamstrings", "Lower back"],
    s: ["45° back extension bench, pad just below your hip bones.", "Feet turned out slightly; round your upper back a little to bias the glutes."],
    c: ["Lower forward until you feel a stretch.", "Squeeze your glutes to lift until your body is in a straight line.", "Hold a plate to your chest when 15 reps feel easy."],
    x: ["Hyperextending past straight at the top.", "Using your lower back instead of your glutes."],
    q: "45 degree back extension glute focus" },
  "glute-bridge": { m: ["Glutes"],
    s: ["Lie on the floor, knees bent, feet flat; barbell or dumbbell across your hips with a pad."],
    c: ["Drive through your heels and squeeze your glutes to lift your hips.", "Hold the top for 2 seconds.", "Lower until your glutes just touch the floor."],
    x: ["Arching your lower back.", "Rushing the reps; the squeeze is the point."],
    q: "barbell glute bridge technique" },
  "rev-lunge": { u: "leg-alt", m: ["Glutes", "Quads"],
    s: ["Dumbbells at your sides, feet hip width."],
    c: ["Step one foot back and lower until both knees are at about 90°.", "Keep most of your weight in your front heel.", "Push through the front heel to return. Alternate legs."],
    x: ["Front knee caving in.", "Taking too short a step."],
    q: "dumbbell reverse lunge technique" },
  "db-row": { u: "arm", m: ["Lats", "Mid back"],
    s: ["One hand and knee on a bench, flat back, dumbbell in the other hand."],
    c: ["Pull the dumbbell towards your hip, elbow close to your body.", "Squeeze at the top.", "Lower to a full stretch."],
    x: ["Twisting your torso to lift.", "Shrugging the weight up."],
    q: "one arm dumbbell row technique" },
  "knee-raise": { m: ["Lower abs"],
    s: ["Hang from a bar or use a captain's chair with your back on the pad."],
    c: ["Curl your knees up towards your chest, tilting your pelvis.", "Lower slowly without swinging."],
    x: ["Swinging to build momentum.", "Only lifting your legs without curling your hips."],
    q: "hanging knee raise technique" },

  "sled": { m: ["Legs", "Conditioning", "Whole body"],
    s: ["Load the sled so it moves steadily, not in a crawl.", "Hands on the high or low handles, arms locked."],
    c: ["Lean in at about 45°, body in a straight line.", "Drive with short, powerful steps.", "Rest 60–90 seconds between pushes."],
    x: ["Standing too upright.", "Overloading it so your form breaks."],
    q: "sled push technique" }
};

window.GB_HOME_GUIDES = {
  "floor-press": { m: ["Chest", "Triceps", "Front delts"],
    s: ["Lie on the floor, knees bent, a dumbbell in each hand.", "Upper arms on the floor at about 45° from your body, shoulder blades pinched together."],
    c: ["Press both dumbbells up until your arms are straight.", "Lower over 3 seconds until your upper arms rest lightly on the floor.", "Pause for a second, then press again."],
    x: ["Bouncing your elbows off the floor.", "Flaring your elbows straight out to the sides."],
    q: "dumbbell floor press technique" },
  "band-pulldown": { m: ["Lats", "Upper back", "Biceps"],
    s: ["Anchor a band high: over a door with a door anchor, or a pull-up bar.", "Kneel or sit far enough away that the band is tight with your arms straight.", "If you have a bar and can do 6 or more clean pull-ups, do pull-ups instead."],
    c: ["Pull your shoulders down first.", "Drive your elbows down to your sides until your hands reach your upper chest.", "Hold for a second, then return slowly to straight arms."],
    x: ["Leaning back and turning it into a row.", "A slack band at the top, which takes the tension off."],
    q: "resistance band lat pulldown technique" },
  "db-fly-floor": { m: ["Chest"],
    s: ["Lie on the floor, knees bent, dumbbells pressed up over your chest, palms facing each other.", "Keep a slight bend in your elbows and hold it."],
    c: ["Open your arms wide until your upper arms touch the floor.", "Squeeze your chest to bring the dumbbells back together in an arc.", "Stop just short of them touching."],
    x: ["Bending and straightening your elbows, which turns it into a press.", "Going too heavy: this should feel like a stretch, not a strain."],
    q: "dumbbell floor fly technique" },
  "lean-lateral": { u: "arm", m: ["Side delts"],
    s: ["Hold a door frame or post with one hand and lean away until that arm is straight.", "Light dumbbell in the free hand, hanging straight down."],
    c: ["Raise the dumbbell out to the side to shoulder height, leading with your elbow.", "Pause briefly at the top.", "Lower slowly. Finish all reps on one arm, then switch."],
    x: ["Shrugging the weight up with your traps.", "Swinging from the hips."],
    q: "leaning dumbbell lateral raise technique" },
  "db-press-standing": { m: ["Shoulders", "Triceps", "Core"],
    s: ["Stand with feet hip width, dumbbells at shoulder height, palms forward or slightly turned in.", "Squeeze your glutes and brace your stomach."],
    c: ["Press straight up until your arms are locked out by your ears.", "Lower under control to shoulder height.", "Keep your ribs down throughout."],
    x: ["Leaning back to grind out reps.", "Using your legs to bounce the weight up."],
    q: "standing dumbbell overhead press technique" },
  "diamond-pushup": { m: ["Triceps", "Chest"],
    s: ["Hands together under your chest, thumbs and index fingers touching.", "Body in a straight line from head to heels."],
    c: ["Lower your chest to your hands, elbows brushing your sides.", "Press back up to straight arms.", "Too hard? Do them from your knees or with your hands on a bench."],
    x: ["Hips sagging or piking up.", "Elbows flaring wide, which takes it off the triceps."],
    q: "diamond push up technique" },
  "pushup": { m: ["Chest", "Triceps", "Front delts"],
    s: ["Hands just wider than your shoulders, body in a straight line.", "Squeeze your glutes and brace your stomach."],
    c: ["Lower until your chest is just off the floor, elbows about 45° from your body.", "Press back up to straight arms.", "Too easy? Raise your feet or wear a loaded backpack. Too hard? Hands on a bench."],
    x: ["Hips sagging.", "Half reps that stop well short of the floor."],
    q: "push up technique" },
  "db-curl": { m: ["Biceps"],
    s: ["Stand tall, dumbbells at your sides, palms forward.", "Elbows pinned to your ribs."],
    c: ["Curl both dumbbells up without moving your elbows.", "Squeeze at the top.", "Lower over 3 seconds to straight arms."],
    x: ["Swinging your body to start the rep.", "Letting your elbows drift forward."],
    q: "dumbbell curl technique" },
  "db-skull": { m: ["Triceps"],
    s: ["Lie on the floor or a bench, dumbbells held straight up, palms facing each other.", "Tilt your arms slightly back towards your head."],
    c: ["Bend only at the elbows and lower the dumbbells beside your ears.", "Feel the stretch, then straighten your arms.", "Keep your upper arms still throughout."],
    x: ["Elbows flaring out wide.", "Turning it into a press by moving your upper arms."],
    q: "dumbbell skull crusher technique" },
  "band-facepull": { m: ["Rear delts", "Upper back", "Rotator cuff"],
    s: ["Anchor a band at face height and hold an end in each hand.", "Step back until the band is tight with your arms straight.", "No band? Do a bent-over dumbbell fly instead."],
    c: ["Pull towards your face, elbows high and wide.", "Finish with your hands beside your ears, knuckles pointing back.", "Hold for a second, then return slowly."],
    x: ["Pulling to your chest with your elbows low.", "Leaning back to move the band."],
    q: "band face pull technique" },
  "bent-fly": { m: ["Rear delts", "Upper back"],
    s: ["Hinge forward until your chest is nearly parallel to the floor, back flat.", "Light dumbbells hanging under your chest, slight bend in the elbows."],
    c: ["Raise the dumbbells out to the sides, leading with your elbows.", "Stop when your arms are level with your back.", "Lower slowly."],
    x: ["Standing up as you lift.", "Going heavy and swinging."],
    q: "bent over dumbbell reverse fly technique" },
  "neck-towel": { m: ["Neck"],
    s: ["Curl: loop a towel across your forehead and hold both ends behind you.", "Extension: loop it across the back of your head and hold both ends in front.", "Sit tall and keep the resistance gentle."],
    c: ["Curl: bring your chin towards your chest against the towel, then return slowly.", "Extension: press your head back against the towel, then return slowly.", "Do every rep of the curl, rest, then every rep of the extension."],
    x: ["Jerking or pulling hard on the towel.", "Carrying on through any sharp pain, tingling or dizziness."],
    q: "neck curl and extension towel resistance" },
  "db-rdl": { m: ["Hamstrings", "Glutes", "Lower back"],
    s: ["Stand with feet hip width, dumbbells in front of your thighs.", "Soft knees, shoulders back, back flat."],
    c: ["Push your hips straight back and slide the dumbbells down your legs.", "Stop when you feel a strong hamstring stretch, usually just below the knee.", "Drive your hips forward to stand tall."],
    x: ["Rounding your back to reach lower.", "Bending your knees so it turns into a squat."],
    q: "dumbbell Romanian deadlift technique" },
  "goblet": { m: ["Quads", "Glutes", "Core"],
    s: ["Hold one dumbbell upright against your chest with both hands.", "Feet shoulder width, toes turned out a little."],
    c: ["Lower over 3 seconds, sitting between your hips, elbows inside your knees.", "Go as deep as you can with heels down and chest up.", "Drive up through your whole foot."],
    x: ["Heels lifting off the floor.", "Knees caving inwards."],
    q: "goblet squat technique" },
  "sl-bridge": { u: "leg", m: ["Hamstrings", "Glutes"],
    s: ["Lie on your back, one foot flat on the floor near your bum, the other leg raised.", "Arms on the floor at your sides."],
    c: ["Drive through the planted heel to lift your hips until knee, hip and shoulder are in line.", "Squeeze for a second at the top.", "Lower slowly. Finish all reps on one leg, then switch."],
    x: ["Arching your lower back instead of lifting with your glute.", "Letting your hips twist or drop to one side."],
    q: "single leg glute bridge technique" },
  "sl-calf": { u: "leg", m: ["Calves"],
    s: ["Stand on one foot on the edge of a step, heel hanging off.", "Dumbbell in the hand on the same side, other hand on a wall for balance."],
    c: ["Lower your heel below the step for a full stretch.", "Rise as high as you can onto your toes and pause for a second.", "Lower slowly. Finish all reps on one leg, then switch."],
    x: ["Bouncing out of the bottom.", "Short reps that skip the stretch."],
    q: "single leg calf raise technique" },
  "walking-lunge": { m: ["Quads", "Glutes"],
    s: ["Dumbbells at your sides, standing tall, clear space ahead."],
    c: ["Take a long step forward and lower until your back knee nearly touches the floor.", "Drive through the front heel and step straight into the next lunge.", "The distance is the total walked, both legs together."],
    x: ["Short steps that push your knee far past your toes.", "Leaning your chest forward over your thigh."],
    q: "dumbbell walking lunge technique" },
  "db-upright": { m: ["Side delts", "Traps"],
    s: ["Stand tall, dumbbells in front of your thighs, palms facing you."],
    c: ["Lift your elbows out and up, the dumbbells travelling close to your body.", "Stop at lower-chest height, elbows level with your shoulders.", "Lower slowly."],
    x: ["Pulling up to your chin, which pinches the shoulder.", "Leading with your hands instead of your elbows."],
    q: "dumbbell upright row technique" },
  "sl-hip-thrust": { u: "leg", m: ["Glutes", "Hamstrings"],
    s: ["Upper back against a sofa or bench, one foot flat on the floor, the other leg raised.", "Rest a dumbbell on the hip of the working leg."],
    c: ["Drive through the planted heel until your hips are level with your knee and shoulders.", "Tuck your chin, squeeze your glute and hold for a second.", "Lower slowly. Finish all reps on one leg, then switch."],
    x: ["Over-arching your lower back at the top.", "Pushing through your toes instead of your heel."],
    q: "single leg dumbbell hip thrust technique" },
  "band-abduction": { m: ["Side glutes"],
    s: ["Loop a band just above your knees.", "Sit on the edge of a chair leaning slightly forward, feet flat and hip width."],
    c: ["Push both knees out against the band as far as they go.", "Hold for a second.", "Return slowly without letting the band go slack."],
    x: ["Rocking your body to help.", "Fast, bouncy reps."],
    q: "seated banded hip abduction" },
  "band-kickback": { u: "leg", m: ["Glutes"],
    s: ["Loop a band around both ankles, or anchor one end low and the other around one ankle.", "Hold a wall or chair, lean slightly forward, standing knee soft."],
    c: ["Kick one leg back and slightly out, leading with your heel.", "Squeeze your glute for a second at the top.", "Return slowly. Finish all reps on one leg, then switch."],
    x: ["Arching your lower back to get the leg higher.", "Swinging the leg."],
    q: "banded glute kickback technique" },
  "band-pallof": { u: "side", m: ["Core", "Obliques"],
    s: ["Anchor a band at chest height and stand side-on to it.", "Hold the band at your chest with both hands, feet hip width, far enough out that it is tight."],
    c: ["Press your hands straight out in front of you.", "Resist the band pulling you round; hold for 2 seconds.", "Bring it back to your chest. Finish all reps facing one way, then turn round and repeat."],
    x: ["Letting your hips or shoulders rotate towards the anchor.", "Standing so close that there is no tension."],
    q: "band Pallof press technique" },
  "floor-bridge": { m: ["Glutes", "Hamstrings"],
    s: ["Lie on your back, both feet flat on the floor near your bum.", "For the weighted version, rest a dumbbell across your hips and hold it there."],
    c: ["Drive through your heels to lift your hips until knee, hip and shoulder are in line.", "Squeeze your glutes hard for 2 seconds.", "Lower slowly over 2–3 seconds."],
    x: ["Arching your lower back at the top.", "Feet too far away, which shifts the work to your hamstrings."],
    q: "glute bridge technique" },
  "reverse-crunch": { m: ["Lower abs"],
    s: ["Lie on your back, hands on the floor by your hips, knees bent at 90° over your hips."],
    c: ["Curl your hips off the floor and bring your knees towards your chest.", "Pause, then lower slowly until your hips touch down.", "Keep your knees bent at the same angle throughout."],
    x: ["Swinging your legs for momentum.", "Arching your lower back as you lower."],
    q: "lying reverse crunch technique" }
};

window.GB_HOME_MAP = {
  "DB floor press, 3-sec lowering": "floor-press", "Pull-ups or band pulldowns": "band-pulldown", "Band pulldowns or pull-ups": "band-pulldown", "Band pulldowns": "band-pulldown",
  "Incline DB press, 3-sec lowering": "incline-press", "Incline DB press or push-ups": "incline-press", "One-arm DB row": "db-row", "One-arm DB row, heavy": "db-row",
  "DB fly on the floor": "db-fly-floor", "DB lateral raise, 5–10 kg": "lateral-mon", "DB lateral raise": "lateral-mon", "DB lateral raise, lighter": "lateral-mon",
  "Standing DB press": "db-press-standing", "DB shrug, 2-sec hold at top": "heavy-shrug", "Heavy DB shrug, slow": "heavy-shrug", "DB shrug, slow": "heavy-shrug",
  "DB lateral raise, leaning away": "lean-lateral", "Diamond push-ups": "diamond-pushup", "Incline dumbbell curl": "incline-curl",
  "Band face pull or rear-delt fly": "band-facepull", "Band face pull": "band-facepull", "Neck curl + extension, towel resistance": "neck-towel",
  "DB Romanian deadlift": "db-rdl", "Goblet squat, 3-sec lowering": "goblet", "Bulgarian split squat with DBs": "bss", "Single-leg glute bridge": "sl-bridge",
  "One-leg calf raise holding a DB": "sl-calf", "Farmer's carry, heaviest DBs": "carry", "Walking lunges with DBs (optional)": "walking-lunge",
  "Push-ups to failure": "pushup", "Push-ups": "pushup", "Bent-over DB fly": "bent-fly", "Hammer curl": "hammer", "Seated DB shoulder press": "db-ohp",
  "DB upright row to lower chest": "db-upright", "DB curl, 3-sec lowering": "db-curl", "DB skull crusher": "db-skull",
  "Single-leg DB hip thrust": "sl-hip-thrust", "Banded hip abduction": "band-abduction", "Dead bug (each side)": "dead-bug", "Band Pallof press (each side)": "band-pallof",
  "Step-up onto a sturdy chair": "step-up", "Banded kickback": "band-kickback", "Glute bridge, slow": "floor-bridge", "DB glute bridge, 2-sec squeeze": "floor-bridge",
  "Lying reverse crunch": "reverse-crunch", "DB reverse lunge (each leg)": "rev-lunge"
};
